### ISSUE TITLE
Fabric 1.19.2 crash on launch - Require a version of create thats not released 

### ISSUE THREAD

**Issue by NetunooOG** [Layers-of-Railways/Railway#103]
The title basically explains it all. Requires version 0.5.0i-1000-1.19.2 of mod 'create' (create), but the wrong version is present (fill with current V of create patch 4)

**Comment by Sunconure11** [comment]
Having the same error.

**Comment by mixinspace** [comment]
Same

**Comment by Deceiverr13** [comment]
Im having the exact same problem.

**Comment by Inqie** [comment]
The same issue exists for Fabric 1.18.2. 
S&R: v1.2.2
Create: 0.5.0.i-**988**+1.18.2
Error: Unmet dependency - S&R requires v0.5.0.i-**998**+1.18.2

**Comment by NetunooOG** [comment]
Glad to see I was not the only one, was worried that no one else made a post haha

**Comment by techno-sam** [comment]
Note: if you are struggling to get fabric versions of the mod to run, please install the latest version of create and modify this line in `fabric.mod.json` (within the Steam 'n Rails jar)
from `"create": "0.5.0.i-1000+1.19.2"` - or something similar for 1.18
to `"create": "*"`

**Comment by NetunooOG** [comment]
Worked great, took me a sec to remember I had to use winrar on the .jar, Thanks!

**Comment by techno-sam** [comment]
fixed in 1.2.3
