### ISSUE TITLE
Monorails don't display signal guidelines

### ISSUE THREAD

**Issue by RUTHINAS** [Layers-of-Railways/Railway#104]
It appears that the guidelines indicating rail segments as divided by signals are not visible on monorail tracks. However, reloading the scene (for example by disabling or re-enabling shaders, or by adjusting render distance) makes them briefly visible until the monorail track models are rendered. It seems like the guidelines are actually inside the monorail tracks, and thus can not be seen by the player under regular gameplay circumstances.

**Comment by techno-sam** [comment]
There is, unfortunately, no current way to move them up when they are displaying inside a monorail
