### ISSUE TITLE
Placing Coupler Causes Client Crash

### ISSUE THREAD

**Issue by ground-fruit** [Layers-of-Railways/Railway#109]
Playing on a server with a fairy large set of mods.
Placing a coupler in the world after choosing a track causes the client to crash. The server continues running.
I have not encountered this in singleplayer, and was able to rejoin the server.

Versions
Minecraft 1.19.2
Fabric 0.14.19
Create 0.5.0.i-1003
Steam and Rails 1.2.4

Crash log is attached
[crash-2023-04-26_22.24.41-client.txt](https://github.com/Layers-of-Railways/Railway/files/11339317/crash-2023-04-26_22.24.41-client.txt)

**Comment by techno-sam** [comment]
not sure this is an SnR issue, try looking at something else that has a goggle overlay, such as a boiler - didn't see any mention of SnR in the crashlog
