### ISSUE TITLE
Create Steam 'n Rails is incompatible with Create 0.5.1

### ISSUE THREAD

**Issue by delgurth** [Layers-of-Railways/Railway#114]
I just tried to update to Create 0.5.1, but seems they moved the trains/track package which contains among others TrackBlock. It's no longer in the logistics subpackage.

https://github.com/Creators-of-Create/Create/blob/mc1.19/0.5.1/src/main/java/com/simibubi/create/content/trains/track/TrackBlock.java

So this line needs to get rid of logistics part. But I'm not sure if that's all that needs to be done...

https://github.com/Layers-of-Railways/Railway/blob/1.19/dev/common/src/main/java/com/railwayteam/railways/content/custom_tracks/CustomTrackBlock.java#L8

This is causing my server failing to start:

```
minecraft-java | [18:41:23] [modloading-worker-0/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: Could not find parent com/simibubi/create/content/logistics/trains/track/TrackBlock for class com/railwayteam/railways/content/custom_tracks/CustomTrackBlock in classloader cpw.mods.modlauncher.TransformingClassLoader@61cd1c71 on thread Thread[modloading-worker-0,5,main]
minecraft-java | [18:41:23] [modloading-worker-0/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
minecraft-java | java.lang.ClassNotFoundException: com.simibubi.create.content.logistics.trains.track.TrackBlock
```

**Comment by SpottyTheTurtle** [comment]
All addons will be broken for a little while, Steam 'n Rails especially due to the api merge and we may need to wait for 0.5.1 to come to fabric first.
