### ISSUE TITLE
Failed to load 1.19.2 forge

### ISSUE THREAD

**Issue by AnomalousDeity** [Layers-of-Railways/Railway#115]
Running just create 1.19.2 version 0.5.1.a
with steam n rails 1.19.2 version 1.2.6
 and crashes with java.lang.reflect.InvocationTargetException: null
[crash-2023-05-22_13.35.48-fml.txt](https://github.com/Layers-of-Railways/Railway/files/11536926/crash-2023-05-22_13.35.48-fml.txt)

I know create updated recently so it might be that, but im not 100% sure or im missing something then im just dumb.

**Comment by SpottyTheTurtle** [comment]
All create addon mods will be broken for at least a few days.
