### ISSUE TITLE
[Not an issue] READ ME BEFORE OPENING AN ISSUE

### ISSUE THREAD

**Issue by techno-sam** [Layers-of-Railways/Railway#116]
We've been getting reports that 0.5.1 breaks Steam 'n Rails. We know. We'll get out an update when we can, but please bear in mind that we are all volunteers and that we have other things in life - such as finals - demanding our attention.

Additionally, as a multiloader mod, SnR must wait for Create Fabric to update first.

**Comment by IThundxr** [comment]
fixed
