### ISSUE TITLE
slabs on tracks have broken textures

### ISSUE THREAD

**Issue by lumpenprol** [Layers-of-Railways/Railway#123]
any slab i place on the tracks has a broken texture like a bunch of yarn same for both variants using optifine but no shaders 
![Base Profile Screenshot 2023 06 02 - 21 30 00 63](https://github.com/Layers-of-Railways/Railway/assets/57878813/ae647ae8-57df-407e-a149-eab5e0607fb5)

**Comment by LemmaEOF** [comment]
Just in case, try without OptiFine installed - even without shaders enabled (and you *do* have a shader in this screenshot) it makes *drastic* changes to the Minecraft codebase that break a lot of mods and *cannot be developed against* due to OptiFine's closed-source nature

**Comment by lumpenprol** [comment]
yeah it works without optifine dose that mean i just shouldn't use it or do you think there's a fix

**Comment by LemmaEOF** [comment]
Making a fix would sadly be very difficult and finnicky - the team would have to decide if it's worth it to put in the effort.

**Comment by techno-sam** [comment]
Unfortunately supporting optifine is simply not worth the effort. There are two ways we could try to fix this:
1. Crack open optifine & decompile it - which depending on optifine's license would be *illegal*.
2. Spend obscene amounts of time trying to find a fix based on trial-and-error.

Please try optifine alternatives, such as Sodium and Iris on fabric (full list of fabric replacements for optifine [https://lambdaurora.dev/optifine_alternatives/](https://lambdaurora.dev/optifine_alternatives/)), or their Forge ports Rubidium and Oculus).
