### ISSUE TITLE
Wont load on 1.19.2 forge

### ISSUE THREAD

**Issue by Xsterium** [Layers-of-Railways/Railway#124]
Just using latest 1.19.2 create and flywheel. The mod doesn't load it just comes up with the message :
"Create: Steam 'n Rails (railways) has failed to load correctly"

**Comment by SpottyTheTurtle** [comment]
it isn't compatible with Create 0.5.1 yet

**Comment by Xsterium** [comment]
Yeah sorry I posted before I saw the message saying that it doesn't work on create which is why I closed it.
