### ISSUE TITLE
Crash on starting a modpack with "Create: Steam 'n' Rails"

### ISSUE THREAD

**Issue by GeheimagentNr1** [Layers-of-Railways/Railway#125]
Because my modpack was crashing with "Create: Steam 'n' Rails". I created a modpack with Minecraft 1.18.2, Forge 40.2.9 and only these 3 mods:  
Create: 0.5.1.b  
Create: Steam 'n' Rails: 1.2.6  
Flywheel: 0.6.8.a

![](https://github.com/Layers-of-Railways/Railway/assets/20889593/7d25412e-ac6e-4e3c-8b95-685cd87b317b)

The mod let Minecraft crash on startup with a "InvocationTargetException" because of a "RuntimeException: Cannot find class com/simibubi/create/content/logistics/trains/track/TrackBlock".

Crashlog:
[crash-2023-06-08\_19.31.38-fml.txt](https://github.com/Layers-of-Railways/Railway/files/11692518/crash-2023-06-08_19.31.38-fml.txt)

**Comment by jenchanws** [comment]
Steam n Rails has not been updated to support Create 0.5.1 yet (#116). Please roll back to Create 0.5.0 for now.
