### ISSUE TITLE
create fabric 5.1a github informing for work of start of updating mod

### ISSUE THREAD

**Issue by AceDrago** [Layers-of-Railways/Railway#127]
well just in case yall dont know this but the create fabric github page is saying it is at the 5.1a version and due to the recent attack on curseforge files, it has not been uploaded yet from the looks of it and has been at 5.1a sometime within the last week according the edits of their changelog time stamp.

**Comment by SpottyTheTurtle** [comment]
we've been using a dev build of it for around two weeks now
