### ISSUE TITLE
Mod fails to load

### ISSUE THREAD

**Issue by Aaero0** [Layers-of-Railways/Railway#128]
Im using version 1.9.2 of Steam and Rails and my 1.19.2 forge version is 43.2.14.

Whenever I load up the game with the mod in my mods folder, it says "mod has failed to load" and reason is "null"

![image](https://github.com/Layers-of-Railways/Railway/assets/135202967/652cee92-6d3a-486d-bf42-2e3991f25715)

**Comment by jenchanws** [comment]
The error message doesn't give us much. Please provide your full mod list and as much of the log as possible.

Having said that, I feel like this might have to do with a version mismatch, e.g. using _Create 0.5.1_ and _Steam 'n' Rails 1.2.6_ (for Create 0.5.0) in the same game. If so, please roll back to Create 0.5.0 until the next SnR update (#116).

If that is **NOT** the case, please reopen this issue with the error log.
