### ISSUE TITLE
failed to load

### ISSUE THREAD

**Issue by ghost** [Layers-of-Railways/Railway#129]
![image](https://github.com/Layers-of-Railways/Railway/assets/109978642/71eef704-c956-4667-a2b1-b569b09d0931)
here is mod list
![image](https://github.com/Layers-of-Railways/Railway/assets/109978642/b884f8df-757b-474e-a51a-ab150b865add)

**Comment by Plite7067** [comment]
U have 2 create mods

**Comment by ghost** [comment]
oops

**Comment by ghost** [comment]
lest try now

**Comment by ghost** [comment]
> U have 2 create mods

still having same error

**Comment by Plite7067** [comment]
Which create mod did u delete?

**Comment by Plite7067** [comment]
Steam and rails not yet compatible with latest create mod

**Comment by ghost** [comment]
![image](https://github.com/Layers-of-Railways/Railway/assets/109978642/385ab80a-d70e-4d82-b3cb-cc27acb6bc18)



> Steam and rails not yet compatible with latest create mod

**Comment by Plite7067** [comment]
Read - releases pulled due to a bug

**Comment by ghost** [comment]
oh dum me

**Comment by ghost** [comment]
well bye bye

**Comment by Plite7067** [comment]
Bye
