### ISSUE TITLE
[1.18] Arclight incompatibility

### ISSUE THREAD

**Issue by muriplz** [Layers-of-Railways/Railway#13]
Using arclight-1.18.2-1.0.7-40114eb
Railways 1.0.1

https://pastebin.com/sZrviqmY

https://github.com/Creators-of-Create/Create/blob/a92855254c9a7b85ba28781e2e3ce7169549cbf7/src/main/java/com/simibubi/create/content/logistics/trains/track/TrackBlockItem.java#L101

**Comment by techno-sam** [comment]
The error log you have linked is actually normal for this mod (no, I don't know why, but it isn't the cause of the issue).
Please submit the full log. And, one more thing, I'm not familiar with arclight, could you provide a link to what arclight is?

**Comment by muriplz** [comment]
[Arclight](https://github.com/IzzelAliz/Arclight) is a software/mod that implements Bukkit on forge.
I'm still not sure why the console error happens, since all works fine, but I dont know what a player is doing when the error pops up, it doesnt happen very often

**Comment by muriplz** [comment]
closing since it's not arclight-related
