### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by YousefAldhanhani** [Layers-of-Railways/Railway#133]
the game crashed when i place the Smokestack,  and can't join the world after reloading the game.

**Comment by IThundxr** [comment]
Update the mod

**Comment by YousefAldhanhani** [comment]
the problem is on the lateset update 1.3.0

**Comment by IThundxr** [comment]
> the problem is on the lateset update 1.3.0

You didn't update the mod like I said

**Comment by emilscukurs234-debug** [comment]
Issue still persists with the latest version of the mod
