### ISSUE TITLE
[Crash] On StartUp when ModernFix Mod is installed [FIXED with link]

### ISSUE THREAD

**Issue by f0kx** [Layers-of-Railways/Railway#134]
Latest Create Version
Latest Steam n Rails Version 1.3.2
Forge 43.2.14

https://pastebin.com/see4K29x

**Comment by Gantros** [comment]
I, too, am having this issue:
Same versions as OP
https://pastebin.com/dl/WcRqLMMi

**Comment by brisingraerowing** [comment]
Also getting this with 1.3.3-1.19.2

**Comment by f0kx** [comment]
So you Guys have an Mod called modern fix installed in your modpack? If so try top disable it

**Comment by Aulberon** [comment]
Had the same problem, disabling modern fix fixed it. Will be waitting for a fix to reactivate it.
[latest.log](https://github.com/Layers-of-Railways/Railway/files/11760374/latest.log)
[crash-2023-06-15_13.10.19-client.txt](https://github.com/Layers-of-Railways/Railway/files/11760375/crash-2023-06-15_13.10.19-client.txt)

**Comment by f0kx** [comment]
https://github.com/embeddedt/ModernFix/blob/1.16/README.md

this dev build will fix the issue

**Comment by crafting-Aaron** [comment]
This seemed to have fixed it! Thank you! Had trouble with Valhelsia 5 modpack by manually updating create (got impatient lol) but now I have this and Enchanting Industry working
