### ISSUE TITLE
SnR breaks Create

### ISSUE THREAD

**Issue by SangurianSoul** [Layers-of-Railways/Railway#142]
Latest update for both Create and SnR.

Playing on personal server, everything has worked. Installed todays updated SnR file for the first time.

In the very least, grinding stones and washing are broken, and you cannot look up anything Create related in JEI. There may be more, but that is what i noticed before removing SnR and everything returned to normal.

**Comment by SpottyTheTurtle** [comment]
update SnR

**Comment by SangurianSoul** [comment]
Awesome thank you, yes. 1.3.4 works just fine!
