### ISSUE TITLE
Crashes When Initializing The Game With Various Mods Installed

### ISSUE THREAD

**Issue by AlisonHuang777** [Layers-of-Railways/Railway#145]
Minecraft version: 1.19.2
Forge version: 43.2.14
Create version: 0.5.1.b
Steam 'n' Rails version: 1.3.5

Log file: [2023-06-18-1.log](https://github.com/Layers-of-Railways/Railway/files/11781684/2023-06-18-1.log)
Crash report: [crash-2023-06-18_21.21.29-client.txt](https://github.com/Layers-of-Railways/Railway/files/11781688/crash-2023-06-18_21.21.29-client.txt)

**Comment by techno-sam** [comment]
Optifine is not supported

**Comment by AlisonHuang777** [comment]
So this addon is no longer compactible with OptiFine? It seems to work fine with Optifine before.
