### ISSUE TITLE
1.18.2 steam and rails no longer works with latest create 1.18.2 update. 0.5.1b-patch 1

### ISSUE THREAD

**Issue by netcore10** [Layers-of-Railways/Railway#149]
https://paste.atlauncher.com/view/d7c5def7-ce94-4ca5-9d63-01dbbda4c4d2

**Comment by SpottyTheTurtle** [comment]
update Steam 'n Rails

**Comment by netcore10** [comment]
(1.6.2) 1.18.2 doesn't work, after create updated on 1.18 it stopped working.

**Comment by techno-sam** [comment]
You are using 1.2.6, you should be using 1.3.5

**Comment by netcore10** [comment]
oh is it not on fabric?

**Comment by SpottyTheTurtle** [comment]
We haven't published a fabric release compatible with 0.5.1 yet, no

**Comment by netcore10** [comment]
That would be my issue with searching for an update on my modloader then. Apologies.
