### ISSUE TITLE
[1.19.2]Crashes on Arclight server

### ISSUE THREAD

**Issue by ghost** [Layers-of-Railways/Railway#150]
Crashes on [Arclight](https://github.com/IzzelAliz/Arclight) server
I haven't reported this problem to them yet because they have dropped support for 1.19.2
[latest.log](https://github.com/Layers-of-Railways/Railway/files/11815959/latest.log)

Mod list:
create-1.19.2-0.5.1.b 
Steam_Rails-1.3.5+forge-mc1.19.2

**Comment by techno-sam** [comment]
Should be fixed in 1.4.0 with a fixed mixin priority

**Comment by IThundxr** [comment]
Fixed in 1.4.3 hopefully
