### ISSUE TITLE
Steam 'n' Rails Server breaks wirelessly connected Nixie Tubes and Semaphores 

### ISSUE THREAD

**Issue by Konrs2e** [Layers-of-Railways/Railway#153]
When I was making my train stop I had my semaphore connected to the train singal via display link. It would connected but then disconenct in an infinite cycle. The Nixie Tubes do not update when connected via display link to the train singal.
![2023-06-22_17 53 03](https://github.com/Layers-of-Railways/Railway/assets/103607859/173b9b90-ab79-430e-bd65-eac5b0683678)
![2023-06-22_17 53 01](https://github.com/Layers-of-Railways/Railway/assets/103607859/e42ac31f-3ca4-4588-a328-d23848ff38b1)

The one below is from a single player world
![2023-06-22_17 32 26](https://github.com/Layers-of-Railways/Railway/assets/103607859/6bcad450-ed67-46b2-acc2-6e36b2a0f9b8)

**Comment by techno-sam** [comment]
known issue, it will be fixed in 1.4.0

**Comment by Konrs2e** [comment]
Ah I see, Thanks for the information!
