### ISSUE TITLE
Please consider adding mod conditions for track compat

### ISSUE THREAD

**Issue by MuteTiefling** [Layers-of-Railways/Railway#155]
Recipes should have a load condition in them if their parent mod doesn't exist. Example, neither blue skies nor bop are in Enigmatica 9, so the logs get spammed with errors like these: 

![image](https://github.com/Layers-of-Railways/Railway/assets/9543430/4d74a7e0-416f-4821-b517-9ce68707dbf5)

**Comment by techno-sam** [comment]
fixed 1.4.0
