### ISSUE TITLE
Create Rollers break Steam n Rails rail variants 

### ISSUE THREAD

**Issue by Nyquil98** [Layers-of-Railways/Railway#157]
The new rollers when in "clear blocks and pave" mode, doesnt see the steam n rails tracks as normal tracks and breaks them. The normal behavior still works when I replace the tracks with the normal Create Mod tracks, they only break blocks in front of them and 1 below the tracks without breaking existing tracks.

**Comment by SpottyTheTurtle** [comment]
known issue, will be fixed in next update

**Comment by Nyquil98** [comment]
wow that was a fast response. Thanks for yalls work!
