### ISSUE TITLE
Mod is in with the right version of Minecraft and create mod (minecraft 1.19.2) (create mod 1.19.2) and with the right Steam 'n Rails 1.2.6 Fabric 1.19.2

### ISSUE THREAD

**Issue by Smiley69420** [Layers-of-Railways/Railway#158]
![Screenshot 2023-06-25 132722](https://github.com/Layers-of-Railways/Railway/assets/137697884/30e3ae2e-702e-4470-89c2-4e3aac23b8d8)
![image](https://github.com/Layers-of-Railways/Railway/assets/137697884/e3708949-2692-4ae9-86bc-7031e68c08b2)

**Comment by Smiley69420** [comment]
please someone help me i am so desperate to use mono rails in my hardcore create world and slabs on rails

**Comment by Smiley69420** [comment]
works fine when
![image](https://github.com/Layers-of-Railways/Railway/assets/137697884/2559bf17-80ed-45ac-9f21-54f9785ca7e0)

**Comment by techno-sam** [comment]
you are not using the right version of Create, you need Create 0.5.0 to use Steam 'n Rails 1.2.6

**Comment by Smiley69420** [comment]
oh I am using create 5.0.1 thank you so much
