### ISSUE TITLE
heavy tick lag as a result of the data fixer. 

### ISSUE THREAD

**Issue by m98bw** [Layers-of-Railways/Railway#159]
on the newest version of ATM8 with zero create entities, no trains and no ticking entities, this addon is responsible for 30% of the server load at any one time. In fact, spark reports it as more intensive than the 4 chunk destroyers running millions of actions a tick. 

on top of this, said addon creates zero log entries and according to the atm team seems to run a data fixer(?) 

https://spark.lucko.me/mOe6WKe0ta
simply removing the addon sees tps return to a stable 20. and server load drop 30% 
https://spark.lucko.me/RANzFHzObq 

railways (v1.3.5+forge-mc1.19.2) is the cited problem with 28.88% of the server load total. 
[2023-06-26-1.log.gz](https://github.com/Layers-of-Railways/Railway/files/11860287/2023-06-26-1.log.gz)

**Comment by techno-sam** [comment]
Sorry for the bug, thanks for the report. 1.4.0 will hopefully fix this bug, and otherwise there will be a config option to disable the Steam 'n Rails datafixer

**Comment by m98bw** [comment]
Thanks for the fix.

**Comment by techno-sam** [comment]
1.4.0 released, closing this issue
