### ISSUE TITLE
[1.19.2] [1.3.5] Mod failed to load

### ISSUE THREAD

**Issue by Subthy** [Layers-of-Railways/Railway#160]
Hello,

So the mod is failing to load properly for the pack that I am developing called PokeASub. I came here, cause I don't really know how to fix this and I really like the mod and I want it

[crash-2023-06-25_19.32.46-fml.txt](https://github.com/Layers-of-Railways/Railway/files/11861392/crash-2023-06-25_19.32.46-fml.txt)

**Comment by IThundxr** [comment]
Remove the modern fix mod it's current latest release is incompatible with snr but the dev has let us know they've fixed it for the next modern fix release
