### ISSUE TITLE
Crash on 1.18.2 (Forge)

### ISSUE THREAD

**Issue by MrChallenge** [Layers-of-Railways/Railway#161]
Addon crashing my modpack. I don't know what mod conflict with it, it's Create?! If its conflict. Maybe I'm dumb or wrong version? Crush report is [here](https://github.com/Layers-of-Railways/Railway/files/11883234/crash-2023-06-27_17.19.04-client.txt)

**Comment by IThundxr** [comment]
remove optifine

**Comment by MrChallenge** [comment]
> remove optifine

Can you recommend a replacement for Optifine with Forge?

**Comment by IThundxr** [comment]
> > remove optifine
> 
> Can you recommend a replacement for Optifine with Forge?

Rubidium paired with oculus for shaders

**Comment by MrChallenge** [comment]
> > > remove optifine
> > > 
> > Can you recommend a replacement for Optifine with Forge?
> > 
> Rubidium paired with oculus for shaders

thanks, all works
