### ISSUE TITLE
[Not a bug, a feature request] Fabric version update

### ISSUE THREAD

**Issue by thekrugers** [Layers-of-Railways/Railway#165]
Hi,

This is not a bug report, it is a humble request for your kind consideration.

Now that Create Fabric has been updated to 0.5.1, we'd love to see a Fabric version of the latest Steam & Rails ported to Fabric so we can get your awesome train expansion along with the new fancy stuff Create Fabric 0.5.1 adds in our Fabric based packs.

**Comment by LemmaEOF** [comment]
Already in progress.
