### ISSUE TITLE
Compatibility with Cucumber librairy

### ISSUE THREAD

**Issue by Arginou57** [Layers-of-Railways/Railway#166]
Hey, the 2 mods are working well together on solo client, so on server side i have this issue 

https://hastebin.com/share/aberaruvem.php

forge version: forge-1.19.2-43.2.11
Cucumber version : Cucumber-1.19.2-6.0.7.jar
Steams and rails version : Steam_Rails-1.3.5+forge-mc1.19.2.jar

**Comment by IThundxr** [comment]
Mystical ag and cucumber seem to be the issue when they try mixining something snr mixins i would suggest making a issue on their githubs aswell while we check this out

**Comment by IThundxr** [comment]
Can you try this on 1.4.3?

**Comment by IThundxr** [comment]
stale issue reopen if it still occurs
