### ISSUE TITLE
Invisible/Glitched Track Curves When Using Iris Shaders (Steam 'n' Rails 1.4.2)

### ISSUE THREAD

**Issue by JibGold** [Layers-of-Railways/Railway#169]
**ISSUE:** Steam n Rails train track curves exclusively appear invisible when shaders are on, while vanilla Create rail curves appear visible. (see images below)

**Mods/Versions:**
appleskin-fabric-mc1.19-2.4.1
BetterAdvancements-Fabric-1.19.2-0.2.2.142
create-fabric-0.5.1-b-build.1089+mc1.19.2
fabric-api-0.76.0+1.19.2
flywheel-forge-1.19.2-0.6.8.a
indium-1.0.9+mc1.19.2
iris-flywheel-compat-1.19.2-0.2.0
iris-mc1.19.2-1.6.4
jei-1.19.2-fabric-11.6.0.1016
JustEnoughResources-Fabric-1.19.2-1.2.2.200
MouseTweaks-fabric-mc1.19-2.22
oculus-mc1.18.2-1.6.4
rubidium-0.6.5
sodium-fabric-mc1.19.2-0.4.4+build.18
Steam_Rails-1.4.2+fabric-mc1.19.2
XaerosWorldMap_1.30.6_Fabric_1.19.1

Shaders on (BSL Shaders):
![image](https://github.com/Layers-of-Railways/Railway/assets/116314329/3e71113e-b77b-4ee6-8516-1d5f997bc0aa)

Shaders off:
![image](https://github.com/Layers-of-Railways/Railway/assets/116314329/f4589e3e-04d6-477a-87ff-d13316b19ecd)

**Note:**
Adding the unofficial "Iris Flywheel Compat" with "instanced" backend appears to solve the issue...

"Instanced" (Complementary Reimagined)
![image](https://github.com/Layers-of-Railways/Railway/assets/116314329/1c36443a-7aa8-430f-ab56-150bd1381aea)

 however, using "batching" creates extremely unpleasant rendering glitches:
 
 "Batching" (Complementary Reimagined)
![image](https://github.com/Layers-of-Railways/Railway/assets/116314329/125afffe-ae6f-4077-b4ea-1548c1297d8e)

**Comment by IThundxr** [comment]
For devs: https://discord.com/channels/706277846389227612/1053481573816750160/1126711352656924762 this is the fix for this

**Comment by HanatakeYurii** [comment]
@JibGold
Why do you have Sodium (Fabric mod) and Rubidium (Forge mod, unofficial port of Sodium) in the same list?
The same with Iris (Fabric) and Oculus (Forge port)? Not to mention Oculus is tagged 1.18.2...

**Comment by JibGold** [comment]
@HanatakeYurii I was just noticing that as well when I went to go set up a similar instance in Forge to see if the issue persisted across Fabric/Forge lines.

Best guess would be that CurseForge did some funky things to the modlist when installing required dependencies for the Iris/Flywheel Compatibility mod. Working on getting a fresh client to test the issue again and see if that was the issue all along, though I’m guessing removing the weird mods from the list won’t fix the issue since it existed prior to the compatibility mod download.

UPDATE: Issue still persists after removing the conflicting/incompatible mods.
![image](https://github.com/Layers-of-Railways/Railway/assets/116314329/44061a62-3c7b-47de-bb8b-6530be036c3a)

**Comment by techno-sam** [comment]
fixed in dev, will release with SnR 1.4.3

**Comment by TheInfamousAlk** [comment]
Still having this issue. Same setup as above.
