### ISSUE TITLE
Game won't start with Steam'N'Rails enabled.

### ISSUE THREAD

**Issue by P4YN-Ki** [Layers-of-Railways/Railway#170]
Minecraft [1.19.2] - Forge [43.2.14] - Create [0.5.1d](c Crashes for me)

I should note this is part of a massive modpack I have not tested it with just Create, nor am I able to. This mod isn't part of the main modpack yet as I intend it to be. I've attached the Crash Log which is really strange, when I enable this mod it simply errors out a bunch of other mods.
Pastebin Version: https://pastebin.com/bfmD0KMc

[crash-2023-07-07_05.17.18-client.txt](https://github.com/Layers-of-Railways/Railway/files/11974488/crash-2023-07-07_05.17.18-client.txt)

**Comment by SpottyTheTurtle** [comment]
SnR 1.4.1 isn't compatible with Creete 0.5.1c and 0.5.1d yet. Downgrade Create to 0.5.1b and the issue should be resolved

**Comment by IThundxr** [comment]
Will add c compat soon
