### ISSUE TITLE
Load stage error Minecraft 1.19.2 S&R 1.4.2 Forge 43.2.14

### ISSUE THREAD

**Issue by SleeplessF0X** [Layers-of-Railways/Railway#172]
## Description
Game stopped on loading stage (window didn't opened) because of the conflict with [SecurityCraft](https://www.curseforge.com/minecraft/mc-mods/security-craft) 1.9.6.1

## Reproduction
Launch the game, wait ~30 seconds, close the Java Minecraft process

## Logs
[error_log.txt](https://github.com/Layers-of-Railways/Railway/files/11981844/error_log.txt)

## Software Info
 - OS: Linux Mint 21
 - Minecraft version: 1.19.2
 - Minecraft launcher: Legacy Launcher
 - Forge version: 43.2.14
 - S&R version: 1.4.2

## Additional info
I've got a feeling that the error is more on the SecurityCraft side, but since I don't know much about mod development I've came here first because the error came up to me after I tried to update this mod on my private server. If this issue needs to be reported to the SecurityCraft devs, let me know. Also, even though I didn't worked on any mods, I am a professional programmer, so if someone can point me to how to fix this - I'll be happy to work on contributing to the fix maybe even today

**Comment by IThundxr** [comment]
looks like a mixin priority issue lemme try to fix this

**Comment by techno-sam** [comment]
This is a fundamentally tricky issue, since only one mod can redirect a certain method at a time, and it is a very similar redirector to SC's. A possible solution would be to increase the priority (since mixins follow natural ordering and priority 1 beats priority 2), make the redirect optional, and add a mixin into one of securitycraft's methods

**Comment by SleeplessF0X** [comment]
Oh, I see, thanks for the explanation! So it requires you to tune the mixin's priority and for SC to implement a compatibility with your mod?

**Comment by techno-sam** [comment]
Yep. That's precisely it. What IThundxr and I have done is made it so that our mixins load after SecurityCraft's, in the process replacing a few of SC's redirects. We patched our redirects to adopt the functionality of SC's where needed, so it should be fully compatible once 1.4.3 releases.

**Comment by SleeplessF0X** [comment]
Cool! Thank you for your time, really looking forward for the update :)

**Comment by techno-sam** [comment]
about to release, if you can confirm it works for you once it does, I can close this issue

**Comment by SleeplessF0X** [comment]
I will be able to test somewhere in an hour, so you can wait for information around this time

**Comment by kawaiicakes** [comment]
I am having the same issue. I will be able to test as well when the patch is released.

**Comment by IThundxr** [comment]
I've ran the release workflows now all we can do is wait for GitHub to build and publish the mod

**Comment by kawaiicakes** [comment]
Oh dear. Looks like the changes broke more things.

[crash-2023-07-07_09.56.08-fml.txt](https://github.com/Layers-of-Railways/Railway/files/11983882/crash-2023-07-07_09.56.08-fml.txt)

**Comment by IThundxr** [comment]
> Oh dear. Looks like the changes broke more things.
> 
> 
> 
> [crash-2023-07-07_09.56.08-fml.txt](https://github.com/Layers-of-Railways/Railway/files/11983882/crash-2023-07-07_09.56.08-fml.txt)
> 
> 

Disable datapack_reload_exceptions in modernfixes config

**Comment by kawaiicakes** [comment]
> > Oh dear. Looks like the changes broke more things.
> > [crash-2023-07-07_09.56.08-fml.txt](https://github.com/Layers-of-Railways/Railway/files/11983882/crash-2023-07-07_09.56.08-fml.txt)
> 
> Disable datapack_reload_exceptions in modernfixes config

Seems to have fixed it, I'm launching fine now. Little strange though how disabling that fixes the issue if it just hides erroring recipes and the like.

Thanks for your time mate.

**Comment by SleeplessF0X** [comment]
Everything works fine for me too (after disabling `datapack_reload_exceptions`), played around a bit and didn't see any other bugs or errors. Thanks for your time, you've got golden hands, people

**Comment by kawaiicakes** [comment]
I'm a little curious why disabling that fixes the problem though. Ideally I would like it on

**Comment by IThundxr** [comment]
> I'm a little curious why disabling that fixes the problem though. Ideally I would like it on

It's a modern fix thing that's been fixed but it's only in dev versions atm the modern fix dev told me that's they'll release a working (fixed) version soon and which should make changing that config not needed

**Comment by IThundxr** [comment]
Fixed in 1.4.3
