### ISSUE TITLE
Game crashed when selecting newly added bogey types with radial menu

### ISSUE THREAD

**Issue by AlisonHuang777** [Layers-of-Railways/Railway#173]
java.lang.NoSuchMethodError: 'com.jozufozu.flywheel.util.transform.Transform com.railwayteam.railways.content.custom_bogeys.CRBogeyRenderer$CoilspringBogeyRenderer.getTransformFromPartial(com.jozufozu.flywheel.core.PartialModel, com.mojang.blaze3d.vertex.PoseStack, boolean)'
[latest.log](https://github.com/Layers-of-Railways/Railway/files/11982540/latest.log)
[crash-2023-07-07_15.03.33-client.txt](https://github.com/Layers-of-Railways/Railway/files/11982545/crash-2023-07-07_15.03.33-client.txt)

**Comment by IThundxr** [comment]
Create 0.5.1c isn't supported yet only 0.5.1b
