### ISSUE TITLE
Incompatibility with ModernFix 1.19.2

### ISSUE THREAD

**Issue by jellyfishhunter** [Layers-of-Railways/Railway#177]
Occured after updating a working Modpack to the new Create version including the latest iteration of Steam 'n' Rails (1.4.3)

Here my crash report:
https://paste.ee/p/fihQi

**Comment by jellyfishhunter** [comment]
I've been too hasty. My ModernFix was outdated. Everything works like a charm.

**Comment by ColonelGerdauf** [comment]
In my case, it still causes startup crashing.

Research and inquiries point to the method of using redirects conflicting with many other mods including ModernFix.

**Comment by IThundxr** [comment]
> In my case, it still causes startup crashing.
> 
> Research and inquiries point to the method of using redirects conflicting with many other mods including ModernFix.

Disable the data pack exceptions config in modern fix configs

**Comment by ColonelGerdauf** [comment]
Looking at the config files, I do not see such a setting. 

More to the point, I have to raise questions to the need to do these special things to improve mod compatibility. Both this mod as well as ModernFix are a part of a major modpack (AllTheMods 8)

**Comment by IThundxr** [comment]
It's a modern fix issue since we suppress a error it also suppresses but this will be fixed by modern fixes next update and same with our next release if everyone goes to plan

**Comment by IThundxr** [comment]
> Looking at the config files, I do not see such a setting. 
> 
> 
> 
> More to the point, I have to raise questions to the need to do these special things to improve mod compatibility. Both this mod as well as ModernFix are a part of a major modpack (AllTheMods 8)

Disable datapack_reload_exceptions in modernfix mixins config

**Comment by ColonelGerdauf** [comment]
I have done this, and it still crashes at startup.

**Comment by IThundxr** [comment]
> I have done this, and it still crashes at startup.

Post log

**Comment by ColonelGerdauf** [comment]
https://mclo.gs/pp7tOgZ

This is a startup log. The error still points to a redirect conflict.

**Comment by IThundxr** [comment]
> https://mclo.gs/pp7tOgZ
>
> This is a startup log. The error still points to a redirect conflict.
Security craft conflict update snr to latest this was fixed in 1.4.3 I think

**Comment by ColonelGerdauf** [comment]
Security Craft is the latest version.

**Comment by IThundxr** [comment]
> Security Craft is the latest version.

Update steam n rails to latest

**Comment by ColonelGerdauf** [comment]
So what is the current status on the updates?

**Comment by IThundxr** [comment]
Latest update fixes this

**Comment by IThundxr** [comment]
> So what is the current status on the updates?

Latest update fixes this

**Comment by ColonelGerdauf** [comment]
So is the amendment of mixins redundant, or is it still needed?

**Comment by IThundxr** [comment]
> So is the amendment of mixins redundant, or is it still needed?

If this is regarding the modern fix mixins config change in 1.4.4 it won't be needed anymore
