### ISSUE TITLE
[Request] Add Forge and fabric conditionals to recipes

### ISSUE THREAD

**Issue by Mitchell5200** [Layers-of-Railways/Railway#178]
As per the title, please add the forge and fabric conditionals to your Data generated track recipes, as that'll then clear up any recipe errors that occur when a mod is not loaded, it also means you can then remove the error suppression mixin added in 1.4.0. Each loader should ignore the other loader's conditional code block as well, meaning no errors should occur due to this conditional addition.
*(Tested by datapack overwriting one of the erroring BOP recipes)*
Doing this will then correctly fix crashes like #171 
We'd be happy to provide a PR implementing this datagen change.

Forge docs, https://docs.minecraftforge.net/en/latest/resources/server/conditional/
Fabric PR (could not find the doc), https://github.com/FabricMC/fabric/pull/1656

Example of what will be added to each recipe once they are regenerated, copied from another multiloader mod, Ad Astra 
[Source](https://github.com/terrarium-earth/Ad-Astra/blob/b767e64dfccca21c7672a90d27c4a030eaa7d3aa/common/src/main/resources/data/create/recipes/pressing/calorite_ingot.json#L2-L15)
*snippet*
```
  "fabric:load_conditions": [
    {
      "condition": "fabric:all_mods_loaded",
      "values": [
        "biomesoplenty"
      ]
    }
  ],
  "conditions": [
    {
      "type": "forge:mod_loaded",
      "modid": "biomesoplenty"
    }
  ],
  ```

**Comment by techno-sam** [comment]
Make a pr and I'll make sure it gets merged in (assuming it works of course)

**Comment by IThundxr** [comment]
https://github.com/Layers-of-Railways/Railway/pull/179
