### ISSUE TITLE
Rails without half bricks cannot be removed

### ISSUE THREAD

**Issue by xuanlv797** [Layers-of-Railways/Railway#18]
Rails without half bricks cannot be removed(Sorry, English is not my language)
you can Look gif diagram
![12](https://user-images.githubusercontent.com/113533766/205660835-1f6dda80-0b6a-4e76-b637-bf9f2a9512be.gif)

**Comment by techno-sam** [comment]
Are you using Steam 'n Rails 1.0.2? If so, this is a known issue and is fixed in 1.0.3. Please let me know, so I can close this issue if it is resolved by updating.

**Comment by xuanlv797** [comment]
Oh, I didn't notice that 1.0.3 has been updated. After the update, this problem has been solved
