### ISSUE TITLE
SNR rail turns/S-bends invisible with Iris shaders (Fabric 1.4.3, 1.19.2)

### ISSUE THREAD

**Issue by programmer-137** [Layers-of-Railways/Railway#180]
When using shaders (Complementary) with Iris (and I assume also Occulus), turns and S-bends don't render. I've tried with default Create rails and they still work, and turning Flywheel backend off doesn't help. Default Create tracks don't appear to have this issue

Without shaders, Flywheel backend set to instancing
![Without shaders, Flywheel backend set to instancing](https://github.com/Layers-of-Railways/Railway/assets/120293861/232a2494-159e-48da-bf53-1179e81d46d6)
With shaders, Flywheel backend set to instancing
![With shaders, Flywheel backend set to instancing](https://github.com/Layers-of-Railways/Railway/assets/120293861/44dafb9d-6fc8-4128-919a-bfa151716e79)

**Comment by programmer-137** [comment]
(I was holding a phantom track in my hand while I took both these pictures)

**Comment by programmer-137** [comment]
It also appears that in [this issue](https://github.com/Layers-of-Railways/Railway/issues/169) it was fixed in 1.4.3, but I'm using 1.4.3 Fabric

**Comment by TheInfamousAlk** [comment]
I am also having this issue, 1.4.3 fabric.

**Comment by BraveCaperCat2** [comment]
this is a duplicate of #169

**Comment by techno-sam** [comment]
Fixed in 1.5.0 (not yet released)
Will close this issue when that releases

**Comment by BraveCaperCat2** [comment]
already fixed, this is a duplicate of a closed issue.

**Comment by techno-sam** [comment]
#169 (and this, they are the same) was *thought* to have been fixed but was not actually fixed. The issue was left closed because it is now a duplicate

**Comment by techno-sam** [comment]
Fixed in 1.5.0. Will close this early on August 30th unless you tell me it is still broken.

**Comment by programmer-137** [comment]
![2023-08-28_12 28 13](https://github.com/Layers-of-Railways/Railway/assets/120293861/bee36dde-db97-4787-8ea2-bf0490a8ecbe)
It works!
