### ISSUE TITLE
[1.19.2-1.3.5] Bogey Render Crash - Renamed methods in Create 0.5.1c

### ISSUE THREAD

**Issue by TigerWalts** [Layers-of-Railways/Railway#181]
Monorail Bogeys are crashing the render pipeline. The cause is this PR in Create:

- https://github.com/Creators-of-Create/Create/pull/4875

A few methods in the Create API were renamed.

This is a duplicate of https://github.com/Layers-of-Railways/Railway/issues/175 and https://github.com/Layers-of-Railways/Railway/issues/176 but those were closed and I see no commits correcting this codebase.

**Comment by SpottyTheTurtle** [comment]
downgrade Create to 0.5.1b. The reason you don't see any commits correcting it is because we build off Create fabric, which currently does not have a version for 0.5.1c.
