### ISSUE TITLE
Can someone please help me? Create: Steam N' Rails keeps on crashing when switching bogey type.

### ISSUE THREAD

**Issue by SmithJones2177** [Layers-of-Railways/Railway#182]
So whenever I press Alt to open the bogey type switching menu and click on one of the bogey types, the game instantly crashes. And there is a model of the bogey that appears beside it and I don't know if its related for when the model is being loaded, the model itself, or something else that's causing the issue.

Here are the mods that I have installed.

- Architect's Palette
- **Create 0.5.1.c**
- Create: Crafts and additions
- Create: Electric Trains
- **Create: Steam N' Rails 1.4.3**
- Framed Blocks
 
Here is a short video of it happening (I had to compress the video to put it on here lol)

https://github.com/Layers-of-Railways/Railway/assets/129133005/84d44269-8e9c-41ed-8744-a84933e53382

I really need to get this working because I wanna make a train (The GG1 Elec Loco to be exact) and I don't really know how to have more than 2 bogeys on 1 engine.

Thank you for helping me!

**Comment by IThundxr** [comment]
> So whenever I press Alt to open the bogey type switching menu and click on one of the bogey types, the game instantly crashes. And there is a model of the bogey that appears beside it and I don't know if its related for when the model is being loaded, the model itself, or something else that's causing the issue.
> 
> Here are the mods that I have installed.
> 
> * Architect's Palette
> * **Create 0.5.1.c**
> * Create: Crafts and additions
> * Create: Electric Trains
> * **Create: Steam N' Rails 1.4.3**
> * Framed Blocks
> 
> Here is a short video of it happening (I had to compress the video to put it on here lol)
> 
>  Whyyyyy-compressed.mp4 
> I really need to get this working because I wanna make a train (The GG1 Elec Loco to be exact) and I don't really know how to have more than 2 bogeys on 1 engine.
> 
> Thank you for helping me!

use create 0.5.1b the c version isnt compatible yet

**Comment by SmithJones2177** [comment]
It worked! Thank you IThundxr!
