### ISSUE TITLE
World crashed after constructing monorail

### ISSUE THREAD

**Issue by Timbosantes** [Layers-of-Railways/Railway#189]
Greetings.
I tried to create a new monorail train. By placing the train casing on the track, the game crashed and I am since unable to open the world.

`The game crashed whilst rendering block entity
Error: java.lang.NoSuchMethodError: 'com.jozufozu.flywheel.util.transform.Transform com.railwayteam.railways.content.custom_bogeys.monobogey.MonoBogeyRenderer$SmallMonoBogeyRenderer.getTransformFromPartial(com.jozufozu.flywheel.core.PartialModel, com.mojang.blaze3d.vertex.PoseStack, boolean)'`

The full mod list is in the attached crash report.
[crash-2023-07-21_11.51.43-client.txt](https://github.com/Layers-of-Railways/Railway/files/12122483/crash-2023-07-21_11.51.43-client.txt)

**Comment by IThundxr** [comment]
Downgrade create to 0.5.1b

**Comment by Timbosantes** [comment]
@IThundxr Thanks, that worked.
