### ISSUE TITLE
Mixin error

### ISSUE THREAD

**Issue by Sunconure11** [Layers-of-Railways/Railway#190]
https://pastebin.com/9yqP5wM2

**Comment by imaturtle0627** [comment]
having same issue on 1.18.2
mods I have are 
amplified nether
autoreglib
balm
citadel
create
cristelib
ctov
flywheel
iceandfire
jei
journymap
mantle
nullscape
quark
quarkoddities
selen
steamnrails
structory
supplemmentarys
tconstruct
tectonic
terralith
theoneprobe
travelersbackpack
and waystones.

**Comment by techno-sam** [comment]
please binary search to find which mod is causing the problem

**Comment by Sunconure11** [comment]
I cannot perform a binary search at this point in time, due to an unrelated mod causing a crash.

That being said, I do share some mods with the other guy.

Supplementaries
Structory
Various dependencies for Create

**Comment by Sunconure11** [comment]
Updated a few things, and it now blames Better Nether.

https://pastebin.com/k3rm9C4b

**Comment by techno-sam** [comment]
please narrow down to which mod is causing the problem, binary searching can be helpful
https://en.wikipedia.org/wiki/Binary_search_algorithm

**Comment by Sunconure11** [comment]
I believe I solved this one, actually, but the mod still has issues with newer builds of Create.
