### ISSUE TITLE
Crash when pondering conductor cap

### ISSUE THREAD

**Issue by Jammssangees** [Layers-of-Railways/Railway#191]
Every time i load the second part of the conductor cap ponder, my game crashes
[crash-2023-07-23_23.41.47-fml.txt](https://github.com/Layers-of-Railways/Railway/files/12140032/crash-2023-07-23_23.41.47-fml.txt)

**Comment by techno-sam** [comment]
Downgrade to Create 0.5.1b

**Comment by Jammssangees** [comment]
still crashes with 0.5.1.b
[crash-2023-07-24_16.17.12-client.txt](https://github.com/Layers-of-Railways/Railway/files/12146858/crash-2023-07-24_16.17.12-client.txt)

**Comment by techno-sam** [comment]
duplicate of #183
