### ISSUE TITLE
Minecraft 1.18.2, Create 0.5.1c, Game Crashes

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [Layers-of-Railways/Railway#192]
Mod crashes in my mod tester MultiMC instance, which is just Create 0.5.1c, this mod, and the libraries/dependencies of all the other mods I want to use.  Here's the crash log: https://paste.ee/p/6mCHl

**Comment by IThundxr** [comment]
```[23:01:10] [main/WARN] [mixin/]: @Mixin target net.minecraft.resources.RegistryReadOps was not found no_null_processors.mixins.json:RegistryReadOpsMixin```

Not a steam n rails crash this is from no null processors

**Comment by 7OOTnegaTerces** [comment]
No, it's definitely **this** mod, the game will run with all of the other mods, including No Null Processors, is active, but not when this one is added.  I do know how to debug to find the problem children! ;P  I removed No Null, here's the crash report that I got: https://paste.ee/p/bfk2C

**Comment by IThundxr** [comment]
Steam n rails isn't even mentioned in that crash it's smt with rubidium and radium

**Comment by 7OOTnegaTerces** [comment]
But then why does adding steam and rails cause this to happen, and removing it fixes the issue?!?

**Comment by IThundxr** [comment]
not sure but snr isnt compatible with create 0.5.1c yet downgrade to b and "railways" the internal name isnt mentioned even once in that log

**Comment by 7OOTnegaTerces** [comment]
Ah, okay, thanks for letting me know!  Maybe include the Create version compatibility in the file name/description so we can tell before we even download?!?

**Comment by 7OOTnegaTerces** [comment]
**I found the problem!!!**  I was using Steam and Rails for Minecraft 1.19 on Minecraft 1.18...  I feel so dumb, I don't know how I grabbed the wrong one!  Now, everything works, even with Create 0.5.1c!!!  At least now we both know what to look for.  If a mod is making Minecraft crash by it's mere presence, but isn't showing up in the crash log, then it's probably a Minecraft Version incompatibility issue!  Maybe re-label this as "Solved"?!

**Comment by SpottyTheTurtle** [comment]
You'll want to use Creete 0.5.1b even if c "works", otherwise, your game will crash every time it tries to render a bogey added by us.

**Comment by 7OOTnegaTerces** [comment]
Ah, thanks for the heads up!  In that case, please do **definitely** consider putting the compatible Create version somewhere in the file name/description!!!

**Comment by 7OOTnegaTerces** [comment]
Speaking of Create versions, which one works with 0.5.0i?!  I’m testing out that version of Create because I suspect more mods will work with it…

**Comment by IThundxr** [comment]
1.2.6

**Comment by 7OOTnegaTerces** [comment]
Thanks!  You guys are awesome!!!
