### ISSUE TITLE
Steam_Rails-1.4.3+forge-mc1.19.2 game crash

### ISSUE THREAD

**Issue by GmanAtheist** [Layers-of-Railways/Railway#193]
MC 1.19.2, Forge. I9 cpu, 64GB DDR. 24GB Vram. SSD. Placing Bogey on overhead rail beam crashes game. Tried different versions of mod and forge.  Here is a short video and crash report of problem. Please help. Thanks. Love this mod. 
https://youtu.be/FCHkkxA1454
http://www.gmanatheist2022.co.uk/Testarea/Steam_Rails-1.4.3%2Bforge-mc1.19.2%20crash%20log.txt

**Comment by techno-sam** [comment]
Create 0.5.1c is not currently supported. please downgrade to Create 0.5.1b

**Comment by GmanAtheist** [comment]
Thanks. I will do that . Will let you know if all is fine. Your reply is appreciated. :-)

**Comment by GmanAtheist** [comment]
@techno-sam . Works great now. Just one other issue. The conductor won't go in the opposite direction. With two control blocks on either side, he won't turn back as he does in the trains.  Can't find path.  Is this normal?. Thanks again for your help. Much appreciated. :-)

**Comment by techno-sam** [comment]
Could you please open a *new* issue for this, and include a video of the problem, including f3 with all the track debug options on
