### ISSUE TITLE
Concurrency crash on startup

### ISSUE THREAD

**Issue by NielsPilgaard** [Layers-of-Railways/Railway#194]
Relayed from https://github.com/mekanism/Mekanism/issues/7827 & https://github.com/EnigmaticaModpacks/Enigmatica9/issues/530

Most relevant section:

> I think the error occurs as a result of a mod injecting a modlauncher plugin service during mod construction. FML invokes mod constructors in parallel, and if the mod injects the plugin while modlauncher is [preparing](https://github.com/McModLauncher/modlauncher/blob/22f00f846494ff98678fa4a1f871914ba2d9fb62/src/main/java/cpw/mods/modlauncher/LaunchPluginHandler.java#L68C47-L68C47) to transform another class, a CME is thrown.
> 
> After a github search, I found a mod that perfectly matches this scenario and also happens to be installed in your instance: [Create: Steam 'n' Rails](https://legacy.curseforge.com/minecraft/mc-mods/create-steam-n-rails). See their injection code [here](https://github.com/Layers-of-Railways/Railway/blob/1584b7ae46452ded048ffcd9074967c1f4b286b7/forge/src/main/java/com/railwayteam/railways/forge/RailwaysImpl.java#L54). Advice for Steam n Rails maintainers: please perform injection in a transformation service or mixin plugin, before the transformable layer is even created. CC @techno-sam @IThundxr

**Comment by Su5eD** [comment]
So after looking at the actual transformer [code](https://github.com/Layers-of-Railways/Railway/blob/03d9ed8bf31f8be11c8bce41517994130dc9c5c1/forge/src/main/java/com/railwayteam/railways/forge/CRLaunchPluginService.java#L23), I see you only transform a single class. Therefore there is no need for a launch plugin or injection hacks at all.

The easiest way to do this is without dealing with Forge JS coremods is to register a [mixin config plugin](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/extensibility/IMixinConfigPlugin.java), and then applying the transformation in either `preApply` or `postApply`. These plugin methods are wired up from mixin's launch service so the provided `ClassNode` will be exactly the same, no need to worry about having to adjust the transformer code.

**Comment by techno-sam** [comment]
Thanks for the info!
Does the mixin config plugin fire `preApply`/`postApply` even if no mixins target the relevant class?

**Comment by Su5eD** [comment]
I don't think so, but defining an empty mixin for the class should do it.

**Comment by techno-sam** [comment]
Yep, that worked! Had to add a method into the mixin to get it to actually apply, but all good now.
Will be fixed in 1.4.4

**Comment by NielsPilgaard** [comment]
Do you have a rough estimate on when you'll be releasing 1.4.4? The next update of Enigmatica 9 is dependant on it :)

**Comment by IThundxr** [comment]
> Do you have a rough estimate on when you'll be releasing 1.4.4? The next update of Enigmatica 9 is dependant on it :)

So this depends on whenever create fabric releases but.... for create fabric to release (which is ready) it needs a Quilt Fabric API update that includes the new model api but thats blocked by 2 PRs but hopefully soonish that should be done

if you really need forge releases you can get them off the maven over [here](https://maven.ithundxr.dev/#/releases/com/railwayteam/railways/Steam_Rails) but these are untested and could have bugs etc

**Comment by NielsPilgaard** [comment]
Alrighty, thanks 👍
