### ISSUE TITLE
Crash in radial menu for new bogey types.

### ISSUE THREAD

**Issue by EmpiXuZ** [Layers-of-Railways/Railway#195]
When using Create 0.5.1c and Create: Steam 'n' Rails version 1.4.3 on 1.18.2, opening the radial menu and trying to select a newly added type of bogey causes a client-side crash. This does not happen on create 0.5.1b nor does it crash servers at all.
Using windows 10, tested on forge 40.2.4 and 40.2.10.

**Comment by SpottyTheTurtle** [comment]
As you have discovered, it works perfectly fine on 0.5.1b. Changes to the bogey api were made in 0.5.1c which Create fabric does not yet support, rendering us unable to accommodate them
