### ISSUE TITLE
crash when trying to put different types of bogeys on newer versions of create

### ISSUE THREAD

**Issue by BreadGodIsReal** [Layers-of-Railways/Railway#196]

**Comment by BreadGodIsReal** [comment]
[crash-2023-07-26_04.01.52-client.txt](https://github.com/Layers-of-Railways/Railway/files/12166851/crash-2023-07-26_04.01.52-client.txt)

**Comment by SpottyTheTurtle** [comment]
Steam 'n Rails is not currently compatible with 0.5.1c. If you wish to use it, downgrade Create to 0.5.1b or wait however long for us to be compatible
