### ISSUE TITLE
compat: edified slab (hexcasting) renamed

### ISSUE THREAD

**Issue by CdRGit** [Layers-of-Railways/Railway#199]
akashic_slab from hexcasting was renamed to edified_slab, breaking the edified rails compat recipe

**Comment by IThundxr** [comment]
I'll fix it

**Comment by IThundxr** [comment]
Hmm it seems to already be endified?

**Comment by CdRGit** [comment]
weird, might be running on a slightly outdated version?

**Comment by IThundxr** [comment]
Latest version is 1.4.3 what version are you on?

**Comment by CdRGit** [comment]
1.4.3 (forge 1.19.2)

**Comment by IThundxr** [comment]
Could you take a screenshot showing the issue? Checking the code the name is correct

**Comment by CdRGit** [comment]
edified recipe was changed 3 weeks ago according to the code changes
![image](https://github.com/Layers-of-Railways/Railway/assets/44026139/dcac06a1-01a0-4842-9164-cfa39aa4cde5)

**Comment by CdRGit** [comment]
it looks good in the code but maybe this change wasn't included in the forge build? that's the only guess i have

**Comment by IThundxr** [comment]
That's possible I'll decompile the jar and take a look

**Comment by IThundxr** [comment]
> it looks good in the code but maybe this change wasn't included in the forge build? that's the only guess i have

checked it out and you were correct the jar references the old slab but seems its ben fixed since then so next release should fix this!

**Comment by CdRGit** [comment]
alright, glad we both found the same issue and I'm not dealing with some weird edge case, thanks
