### ISSUE TITLE
Invisible Train Wheels not available [1.19] [0.5.1] [forge]

### ISSUE THREAD

**Issue by BraveCaperCat2** [Layers-of-Railways/Railway#200]
As in the title above when i go to make my train on my phantom rails i can't seem to select the invisible wheels option.

**Comment by Primitive-Human** [comment]
Explain why you are abusing the title like that.

**Comment by BraveCaperCat2** [comment]
because it's funny. next time fix the problem.

**Comment by IThundxr** [comment]
> As in the title above when i go to make my train on my phantom rails i can't seem to select the invisible wheels option.

Have you held alt while holding a train casing to bring up the bogey menu?

Also please do not abuse titles

**Comment by xiaoyang5202480** [comment]
Me too.
The game crashes and exits when using the new train casing gear added by this mod.
I hope this bug can be fixed as soon as possible.

**Comment by SpottyTheTurtle** [comment]
@xiaoyang5202480 downgrade Create to 0.5.1b

**Comment by BraveCaperCat2** [comment]
hold alt that makes it work with or without 0.5.1b!

**Comment by Vasya564** [comment]
The same problem when i held alt while holding a train casing and try to change bogey type game crashes.
Playing on 1.18.2 and using create 0.5.1c

**Comment by IThundxr** [comment]
> The same problem when i held alt while holding a train casing and try to change bogey type game crashes. Playing on 1.18.2 and using create 0.5.1c

downgrade to 0.5.1b
