### ISSUE TITLE
Game crashes upon attempting to navigate bogey styles menu [1.19.2] [v0.5.1] [Forge]

### ISSUE THREAD

**Issue by ghost** [Layers-of-Railways/Railway#201]
FML 43.2.17 / Create 0.5.1 / Steam 'n' Rails 1.4.3 / Singleplayer

Using the particular set of mods that I have, everything runs smoothly up until I try to click on "Single Bogey Styles" and "Double Bogey Styles". When I try to navigate to those menus, the game crashes, and returns with [crash-2023-07-27_11.07.19-client.txt](https://github.com/Layers-of-Railways/Railway/files/12186164/crash-2023-07-27_11.07.19-client.txt).

Mods of note will likely be ESSENTIAL, Rubidium, and Rubidium Extra because i have had issues with those particular mods in the past.

**Comment by IThundxr** [comment]
Downgrade to create 0.5.1b

**Comment by ghost** [comment]
Incompatible flywheel version or something?

**Comment by IThundxr** [comment]
> Incompatible flywheel version or something?

No create just changed some code we use
