### ISSUE TITLE
Custom Bogey types from Steam n' rails crash the game

### ISSUE THREAD

**Issue by SpringerPlayz29** [Layers-of-Railways/Railway#202]
The game crashed whilst rendering block entity
Error: java.lang.NoSuchMethodError: 'com.jozufozu.flywheel.util.transform.Transform com.railwayteam.railways.content.custom_bogeys.monobogey.MonoBogeyRenderer$SmallMonoBogeyRenderer.getTransformFromPartial(com.jozufozu.flywheel.core.PartialModel, com.mojang.blaze3d.vertex.PoseStack, boolean)'

[crash-2023-07-28_22.19.04-client.txt](https://github.com/Layers-of-Railways/Railway/files/12197692/crash-2023-07-28_22.19.04-client.txt)

**Comment by SpottyTheTurtle** [comment]
Downgrade Create to 0.5.1b
