### ISSUE TITLE
Minecraft Crash when I use the extra bogeys. (Forge)

### ISSUE THREAD

**Issue by Seemuffel** [Layers-of-Railways/Railway#206]
Hi,
I want to use the extra bogeys but when i am in the alt menu thingy then and I click on a Steam n rails bogey
The game crashes.
Idk why so I would be thankful to help me/fix the problem
1.19.2
Forge 43.2.21
All mods updated

Ty yall you do a great job!
[crash-2023-07-30_02.25.28-fml.txt](https://github.com/Layers-of-Railways/Railway/files/12208299/crash-2023-07-30_02.25.28-fml.txt)

**Comment by IThundxr** [comment]
use create 0.5.1b

**Comment by Seemuffel** [comment]
OU that was fast!
It works
Thanks a lot!
