### ISSUE TITLE
Game crash when trying to place a monorail bogey when using Rubidium [1.19.2] [0.5.1] [forge]

### ISSUE THREAD

**Issue by ModnMaster** [Layers-of-Railways/Railway#208]
Got a crash that happens when placing a monorail bogey.
Managed to get by it by switching to an older version of Create (switched from 0.5.1.c -> 0.5.1.b)

[crash-2023-07-31_13.17.12-client.txt](https://github.com/Layers-of-Railways/Railway/files/12214913/crash-2023-07-31_13.17.12-client.txt)

**Comment by IThundxr** [comment]
Downgrade to 0.5.1b
