### ISSUE TITLE
Large single wheel bogey seems to be unavailable

### ISSUE THREAD

**Issue by Lilygabe** [Layers-of-Railways/Railway#209]
### Describe the Bug

You know the normal variant of the bogey that create gives? The one that's already in the base mod? It doesn't appear anymore when switched in my game, it just goes to the invisible bogey. Is this an issue on my fault? How am I supposed to get it?

### Reproduction Steps

1. Place a train casing on a rail (with the standard set)
2. Use the wrench on it
3. Turns into invisible
4. repeat steps 2 and 3

### Expected Result

The engine bogey should appear at least once

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/72508863/9e6115ab-c40e-48db-844c-768cce75c104)
![image](https://github.com/Layers-of-Railways/Railway/assets/72508863/c148ecdf-9555-460c-90e9-9d10edecf269)

### Operating System

Windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1b

### Minecraft Version

1.18.2

### ModLoader and Version

Forge 40.2.8

### Other Mods

![image](https://github.com/Layers-of-Railways/Railway/assets/72508863/831ab1ed-cbf4-4466-a940-f39c41c82708)

**Comment by IThundxr** [comment]
Hold ALT on a train casing to view all the bogey options

**Comment by SpottyTheTurtle** [comment]
Or if you want to swap through it normally, right click the track below the bogey with an empty hand

**Comment by Lilygabe** [comment]
That is what I've been trying to do
![image](https://github.com/Layers-of-Railways/Railway/assets/72508863/634d1948-0cbe-4eda-bbe3-1656d4cd1e92)
![image](https://github.com/Layers-of-Railways/Railway/assets/72508863/d7723826-3841-4841-8a3a-fdcdf00f6e47)

![image](https://github.com/Layers-of-Railways/Railway/assets/72508863/0c167c17-354c-48fb-8953-4a0b2957a2e4)
![image](https://github.com/Layers-of-Railways/Railway/assets/72508863/cb08ae92-d299-4f49-bc86-9b11ad59789b)

**Comment by SpottyTheTurtle** [comment]
Right click the track beneath the bogey, not the bogey itself.

**Comment by Lilygabe** [comment]
Nevermind I figured it out. you have to click the *track*. Thanks. It would have been nice if there was a ponder or something

**Comment by IThundxr** [comment]
Right click the track to change it between the 2 styles

**Comment by SpottyTheTurtle** [comment]
It's how they work in base Create, not sure what you expect us to do about it.

**Comment by Lilygabe** [comment]
I have always used the wrench in base create, I don't know what you're talking about

**Comment by SpottyTheTurtle** [comment]
You can do either, I just always clicked the track so it never occurred to me people wouldn't know about it.

**Comment by Lilygabe** [comment]
well, thankfully that's what github issues are useful for, I guess now you know

**Comment by Lilygabe** [comment]
Thanks you both
