### ISSUE TITLE
Crash when placing Bogey on Monorail Train Track

### ISSUE THREAD

**Issue by geegaz** [Layers-of-Railways/Railway#212]
### Describe the Bug

When trying to place a bogey on a Monorail Train Track, the game crashes.

### Reproduction Steps

1. Place a Monorail Train Track
2. Place a Train Station on the track and start assembling a new train
4. Place a Train Casing on the blue highlighted area
5. Notice the crash at the moment the casing is placed

Reproduced with:
- Minecraft 1.18.2, 1.19.2
- Forge 40.2.9, 43.2.20
- Create 0.5.1c

The screenshots below show:
- A setup to reproduce the crash
- The regular Create Train Track working correctly

### Expected Result

No crash should happen and a bogey should be created at the clicked position

### Screenshots and Videos

![2023-08-02_09 25 18](https://github.com/Layers-of-Railways/Railway/assets/39198556/a49f5d22-f01d-4e29-accd-2869e6332722)
![2023-08-02_09 26 32](https://github.com/Layers-of-Railways/Railway/assets/39198556/2a894d8a-906a-46c2-84a3-6a8e94bea843)

### Crash Report or Log

https://mclo.gs/OkH6NML

### Operating System

Windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.18.2

### ModLoader and Version

Forge 40.2.9

**Comment by Szedann** [comment]
snr isn't currently compatible with create 0.5.1c

**Comment by geegaz** [comment]
Ahhhhh damn
Thought I saw it on another post, thanks for the clarification !
