### ISSUE TITLE
1.19.2 index out of bounds

### ISSUE THREAD

**Issue by netcore10** [Layers-of-Railways/Railway#214]
### Describe the Bug

Index out of bounds due to amethyst imbuement, i was suggested the problem is here.

### Reproduction Steps

I'm not really sure?

### Expected Result

To not crash

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/181536/361eade8-b9c4-41e2-a353-83dfc554f191)
![image](https://github.com/Layers-of-Railways/Railway/assets/181536/a701236e-1ce1-4d82-b5ad-a8ca733e9375)
https://github.com/fzzyhmstrs/ai/issues/107#issuecomment-1662897307

### Crash Report or Log

https://paste.atlauncher.com/view/63a73bfd-ae52-408b-826a-6758630ffe69

### Operating System

windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Latest fabric

**Comment by netcore10** [comment]
this happens server side, figured it would be relevent.

**Comment by BraveCaperCat2** [comment]
please respond with a list of all other mods or the curseforge modpack you were using.

**Comment by netcore10** [comment]
it's in the log, here you go:
[list.txt](https://github.com/Layers-of-Railways/Railway/files/12322500/list.txt)

**Comment by IThundxr** [comment]
Could you update to 0.5.1c and SnR's to 1.5.1 and try to reproduce this?
