### ISSUE TITLE
Phantom Track Render

### ISSUE THREAD

**Issue by DemDumbb** [Layers-of-Railways/Railway#216]
### Describe the Bug

Phantom Tracks are visible from Top and side. Not really sure what the issue could be.

### Reproduction Steps

You could play the Rabbit Hole SMP Modpack V1.4 to play with other mods included.

### Expected Result

Invisible Tracks

### Screenshots and Videos

![2023-08-04_01 04 04](https://github.com/Layers-of-Railways/Railway/assets/69367396/e51f0a67-5a4f-4de9-8d6b-da7affc38d24)

### Operating System

Windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.21

### Other Mods

[Mari Modpack-1.4.zip](https://github.com/Layers-of-Railways/Railway/files/12257258/Mari.Modpack-1.4.zip)

**Comment by techno-sam** [comment]
Please use binary search to find which mod is causing this problem.
https://en.wikipedia.org/wiki/Binary_search_algorithm

**Comment by IThundxr** [comment]
Closing since cant replicate
