### ISSUE TITLE
Monorail Bogey Crash.

### ISSUE THREAD

**Issue by SunderSoul** [Layers-of-Railways/Railway#217]
### Describe the Bug

After making a monorail bogey, the world crashes and rejoining insta crashes you, effectively bricking the save.

### Reproduction Steps

1. Place a monorail
2. Create a bogey
3. Hooray the bug appeared.

### Expected Result

Crash, bricking the save.

### Crash Report or Log

https://pastebin.com/rKaQaMy1

### Operating System

Windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 43.2.20

### Other Mods

Available in the crashlog.

**Comment by IThundxr** [comment]
Downgrade Create to 0.5.1b since Create 0.5.1c isnt supported yet
