### ISSUE TITLE
Render crash when placing monorail bogey

### ISSUE THREAD

**Issue by Elle199** [Layers-of-Railways/Railway#218]
### Describe the Bug

When I place a train casing on the monorail that is activated to build a train / monorail by a train station the game instantly crashes and continues to crash every time you load the world. 

### Reproduction Steps

1. Place monorail
2. Attach train station to monorail and activate it
3. Place train casing on the blue part of the mono rail

### Expected Result

Bogey to be created attached to the monorail

### Crash Report or Log

https://pastbin.net/monobogey-crash

### Operating System

Windows 11

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge - 43.2.21

### Other Mods

Thermal Dynamics (by TeamCoFH)
Ars Nouveau (by baileyholl2)
Fuel Goes Here (by LobsterJonn)
Thermal Expansion (by TeamCoFH)
Inventory Sorter (by cpw)
Configured (by MrCrayfish)
Rechiseled (by SuperMartijn642)
AppleSkin (by squeek502)
Build Guide (Forge+Fabric) (by brentmaas)
Titanium (by Buuz135)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Towns and Towers (by Biban_Auriu)
Better Advancements (by way2muchnoise)
Naturalist (by Starfish_Studios)
EverlastingAbilities (by kroeser)
Thermal Integration (by TeamCoFH)
Ender Storage 1.8.+ (by covers1624)
ConnectedTexturesMod (by tterrag1098)
HT's TreeChop (by hammertater)
Just Enough Items (JEI) (by mezz)
World Pre Generator (by GeheimagentNr1)
Jade 🔍 (by Snownee)
Mouse Tweaks (by YaLTeR)
Thermal Foundation (by TeamCoFH)
Fusion (Connected Textures) (by SuperMartijn642)
Silent Lib (silentlib) (by SilentChaos512)
Scalable Cat's Force (by Kotori316)
Waystones (by BlayTheNinth)
Entity Culling Fabric/Forge (by tr7zw)
Item Collectors (by SuperMartijn642)
Cloth Config API (Fabric/Forge) (by shedaniel)
JEITweaker (by Jaredlll08)
ZeroCore 2 (by ZeroNoRyouki)
Thermal Innovation (by TeamCoFH)
Thermal Locomotion (by TeamCoFH)
Handcrafted (by kekie6)
Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
Architectury API (Fabric/Forge) (by shedaniel)
Create Chunkloading (by embeddedt)
Rechiseled: Create (by SuperMartijn642)
Visual Workbench [Forge & Fabric] (by Fuzs)
SuperMartijn642's Config Lib (by SuperMartijn642)
Corail Woodcutter (by Corail_31)
YUNG's Bridges (Forge) (by YUNGNICKYOUNG)
Sophisticated Backpacks (by P3pp3rF1y)
Ore Excavation (by Funwayguy)
Default Options (by BlayTheNinth)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
Extreme sound muffler (Forge) (by LeoBeliik)
Create Confectionery (by Furti_Two)
Global Packs (by JTK222)
OpenBlocks Elevator (by vsngarcia)
Just Enough Resources (JER) (by way2muchnoise)
Create: Steam 'n' Rails (by mattentosh)
Experience Obelisk (by cyanog3n)
Nature's Compass (by Chaosyr)
Placebo (by Shadows_of_Fire)
Thermal Cultivation (by TeamCoFH)
FTB Teams (Forge) (by FTB)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
SuperMartijn642's Core Lib (by SuperMartijn642)
YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)
Functional Storage Extra (by Mrthomas20121)
Jade Addons (Forge) (by Snownee)
Curios API (Forge) (by TheIllusiveC4)
Silent Gear (by SilentChaos512)
Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)
Applied Energistics 2 (by thetechnici4n)
AutoRegLib (by Vazkii)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
XyCraft (by Soaryn)
Easier Sleeping (by GeheimagentNr1)
Sophisticated Core (by P3pp3rF1y)
Ars Creo (by baileyholl2)
Chisels & Bits - For Forge (by AlgorithmX2)
Create: Crystal Clear (by singularity_cyvack)
Quartz (by RogueLogix)
Cooking for Blockheads (by BlayTheNinth)
FTB Chunks (Forge) (by FTB)
Pipez (by henkelmax)
Carry On (by Tschipp)
Quark (by Vazkii)
CodeChicken Lib 1.8.+ (by covers1624)
XyCraft: Override (by Soaryn)
Building Gadgets (by Direwolf20)
Phosphophyllite (by RogueLogix)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Chipped (by terrariumearth)
Flux Networks (by sonar_sonic)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Create (by simibubi)
Balm (Forge Edition) (by BlayTheNinth)
FramedBlocks (by XFactHD)
Resourceful Lib (by ThatGravyBoat)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
Corail Tombstone (by Corail_31)
Crafting Tweaks (by BlayTheNinth)
Functional Storage (by Buuz135)
Cyclops Core (by kroeser)
GeckoLib (by Gecko)
Additional Enchanted Miner (by Kotori316)
Silent's Gems (by SilentChaos512)
Create Crafts & Additions (by MRHminer)
Torchmaster (by xalcon)
NoMoWanderer (by TheJDill)
Puzzles Lib [Forge & Fabric] (by Fuzs)
Controlling (by Jaredlll08)
FTB Library (Forge) (by FTB)
CraftTweaker (by Jaredlll08)
Patchouli (by Vazkii)
PackMenu (by Shadows_of_Fire)
CoFH Core (by TeamCoFH)
YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)
Toast Control (by Shadows_of_Fire)
Create Enchantment Industry (by DragonsPlus)
Bigger Reactors (by RogueLogix)
XyCraft: World (by Soaryn)
Create Cafe (by Myst)
Botania (by Vazkii)

**Comment by IThundxr** [comment]
Downgrade Create to 0.5.1b since Create 0.5.1c isnt supported yet
