### ISSUE TITLE
Unable to Render Scene for new bogeys 

### ISSUE THREAD

**Issue by Gabeself** [Layers-of-Railways/Railway#219]
### Describe the Bug

when selecting a bogey in a creative or survival game will crash. This happened even with just steam and rails an and create.

### Reproduction Steps

1. create a new world 
2. place a test track along with a station
3. start train build
4. hold alt to select bogey (three axel in my case)
5. Game crashes
6.
...

### Expected Result

place the desired bogey

### Operating System

windows 11

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.21

**Comment by IThundxr** [comment]
Downgrade Create to 0.5.1b since Create 0.5.1c isnt supported yet
