### ISSUE TITLE
Game crashes when clicking on custom bogey type

### ISSUE THREAD

**Issue by curryducker** [Layers-of-Railways/Railway#220]
### Describe the Bug

When i try to select a custom bogey type the game crashes

### Reproduction Steps

1. Hold a train casing
2. Open the bogey select menu
3. Click on a bogey

### Expected Result

I expected the game to select the bogey.

### Crash Report or Log

https://gist.github.com/curryducker/737bffe7b6f977d632a6152dbcd9c3ab

### Operating System

Windows 11

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge - 43.2.11

### Other Mods

- Pehkui-3.7.4
- architectury-6.5.85
- AutoRegLib-1.8.2
- blueprint-6.1.2
- clayworks-2.0.1
- cloth-config-8.3.103
- create_central_kitchen-1.3.9.c
- Create crafts and additions -1.0.0
- create_enchantment_industry-1.2.6
- CreateShrunk-0.3.2
- sliceanddice-2.3.0
- create_factory-0.0.2
- create-structures-0.1.0
- environmental-3.0.0
- expandingtechnologies-1.0.0
- FarmersDelight-1.2.3
- geckolib-forge-3.1.40
- jei-11.6.0.1016
- kotlinforforge-3.12.0
- moonlight-2.2.43
- MouseTweaks-2.23
- NethersDelight-3.0
- Quark-3.4-405
- seamless-1.3.0
- supplementaries-2.3.20

**Comment by IThundxr** [comment]
Downgrade Create to 0.5.1b since Create 0.5.1c isnt supported yet
