### ISSUE TITLE
monorail crash

### ISSUE THREAD

**Issue by wavesplitter09** [Layers-of-Railways/Railway#221]
### Describe the Bug

theres a bug where when you try to put a bogey on it and it crashes the game

### Reproduction Steps

1.get a line of the monorail
2.put a train station on the track and assemble
3.right-click with train casing on blue part
...

### Expected Result

you crash

### Operating System

m1 mac

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

forge 1.19.2-43.2.21

**Comment by IThundxr** [comment]
Downgrade Create to 0.5.1b since Create 0.5.1c isnt supported yet
