### ISSUE TITLE
Game crashes when selecting bogie styles

### ISSUE THREAD

**Issue by KittyKhrysty** [Layers-of-Railways/Railway#222]
### Describe the Bug

Pressing alt with the train casing and selecting any of the bogie styles except for the standard style crashes the game after freezing for a few seconds

### Reproduction Steps

1. Hold train casing in hand and press alt to select a style of bogie
2. Select any of the styles except for the standard styles (single, double, or triple in this case)

### Expected Result

Select a style of bogie without any game crashing

### Crash Report or Log

https://pastebin.com/7zzDadpV

### Operating System

windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.18.2

### ModLoader and Version

forge 1.18.2 40.2.10

### Other Mods

balm 3.2.0
betterfpsdist 1.18.2 1.5
blueprint 1.18.2 5.4.0
cookingforblockheads-forge 1.18.2 12.1.1
create 1.18.2 0.5.1.c
createdeco 1.3.3 1.18.2
dbExtended 1.18.2 5.0.7
DistantHorizons 1.6.5a 1.18.2
effective_fg 1.1
extendedslabs 1.18.2 2.0.0
fantasyfurniture 1.18.2 3.10.0
jei-1.18.2 9.7.1.225
kotlinforforge-3.4.0 obf
lock_and_key 1.18.2 1.1.0
mcw bridges 2.1.0 mc1.18.2forge
mcw-furniture 3.1.0 mc1.18.2forge
neoncraft2-2.2.
pamhc2crops 1.18.2 1.0.4
pamhc2foodcore 1.18.2 1.0.3
pamhc2foodextended 1.18.2 1.0.4
pamhc2trees 1.18.2 1.0.3
Steam_Rails 1.4.3+forge-mc1.18.2
sweetconcrete 1.18.2 1.8.1
worldedit-mod 7.2.10

**Comment by IThundxr** [comment]
Downgrade Create to 0.5.1b since Create 0.5.1c isnt supported yet
