### ISSUE TITLE
Bogeys have problems rendering, causing game crash

### ISSUE THREAD

**Issue by The-Shortman** [Layers-of-Railways/Railway#223]
### Describe the Bug

When using the alt menu to select bogey types, selecting a bogey group that is not part of the base Create mod causes the game to stop responding, save the world and crash.

Furthermore, upon assembling a train using invisible bogeys, the same thing happens where the game freezes, saves, and crashes.

The error message is the following for selecting the bogey type:
```
The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'com.jozufozu.flywheel.util.transform.Transform com.railwayteam.railways.content.custom_bogeys.CRBogeyRenderer$CoilspringBogeyRenderer.getTransformFromPartial(com.jozufozu.flywheel.core.PartialModel, com.mojang.blaze3d.vertex.PoseStack, boolean)'
```
The error message is the following for assembling a train with invisible bogeys:
```
The game crashed whilst unexpected error
Error: java.lang.AbstractMethodError: Receiver class com.railwayteam.railways.content.custom_bogeys.invisible.InvisibleBogeyRenderer does not define or inherit an implementation of the resolved method 'abstract void initialiseContraptionModelData(com.jozufozu.flywheel.api.MaterialManager, com.simibubi.create.content.trains.entity.CarriageBogey)' of abstract class com.simibubi.create.content.trains.bogey.BogeyRenderer.
```
both with an exit code of 255

### Reproduction Steps

1. Load Create mod and Steam 'n' Rails
2. Make a new single player world
3. Grab a train casing and hold alt to select a bogey style group
4. Select a bogey style group that is added by Steam 'n' Rails
5. Game will crash

AND:

3. Place a rail and station to assemble a new train
4. Place the initial bogey and right click on it with a wrench to turn it to the invisible variant, add controls, glue, etc.
5. Assemble the train
6. Game will crash

### Expected Result

The game to not crash when assembling a train with invisible bogeys or selecting bogey styles.

### Screenshots and Videos

https://github.com/Layers-of-Railways/Railway/assets/78680166/3863970b-2130-48d8-888b-91e1ff84e184

### Crash Report or Log

Selecting via alt menu: https://mclo.gs/Hh11TgT
Assembling with invisible bogeys: https://mclo.gs/xDYGh5x

### Operating System

macOS X 10.15.7

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.21

### Other Mods

Create

### Additional Context

The invisible bogey issue mentioned in the description occurred on a server, and is preventing anyone on the operating systems macOS 10.15 and Windows 10 (although these are the only 2 OS that players on the server have) from joining the game. Based on the fact that the server doesn't crash, this seems to be a rendering issue with clients that attempt to render any Steam 'n' Rails bogeys.

I am unable to test if it is **only** if the bogey is rendered that causes the client's crash, as everyone that had access to the server was affected by this, and the bogey is within sight of world spawn.

**Comment by Szedann** [comment]
Steam 'n' Rails isn't compatible with Create 0.5.1.c yet
