### ISSUE TITLE
Issue Rendering Monorail Bogey

### ISSUE THREAD

**Issue by DebugStix** [Layers-of-Railways/Railway#224]
### Describe the Bug

When suspended monorail bogey was created, the minecraft instance immediately crashed and put out error code -1 and returned me to the launcher. I reattempted creating the bogey and had the same error.

### Reproduction Steps

1. Place down train station on monorail
2. Make it create a train
3. Place train block to make a bogey
...

### Expected Result

Sucessfully created bogey with no error codes

### Crash Report or Log

Link: https://mclo.gs/YRJTv8v

### Operating System

Windows 11

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 42.2.21

**Comment by IThundxr** [comment]
Downgrade Create to 0.5.1b since Create 0.5.1c isnt supported yet
