### ISSUE TITLE
Game Crashes when selecting New Bogey Types

### ISSUE THREAD

**Issue by Snwmexican** [Layers-of-Railways/Railway#226]
### Describe the Bug

Selecting any of the new type of bogeys (Single/Triple) Game crashes to desktop, happens for me and my friend on the same server.

### Reproduction Steps

1. Enter Game
2.Try to select Bogey Type
3.Game Crashes when desired bogey selected
...

### Expected Result

Working Mod? lol Older version worked flawless just new update broken for me

### Crash Report or Log

https://mclo.gs/68IBGTI

### Operating System

Windows 11

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Curseforge

### Other Mods

All the Mods 8 from Curseforge

**Comment by SpottyTheTurtle** [comment]
Downgrade Create to 0.5.1b
