### ISSUE TITLE
Render Fail

### ISSUE THREAD

**Issue by baboonery1** [Layers-of-Railways/Railway#227]
### Describe the Bug

whenever a bogey is placed on monorail it causes the game to crash

### Reproduction Steps

1. Add steam and rails to the stoneblock 3 modpack
2. Launch
3. Place bogey on mono rail
...

### Expected Result

Bogey to place on monorail without crashing

### Crash Report or Log

https://pastebin.com/sJSgKL4F

### Operating System

Windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.18.2

### ModLoader and Version

Forge 40.2.7

**Comment by IThundxr** [comment]
Downgrade Create to 0.5.1b since Create 0.5.1c isnt supported yet

Next time please read the pinned message that you were told to read before making a issue
