### ISSUE TITLE
[forge][1.19.2]Crash when using version 0.5.1c of create

### ISSUE THREAD

**Issue by Diemoerm** [Layers-of-Railways/Railway#228]
### Describe the Bug

Using rails: track_ Monorail creating trains can cause the game to crash

### Reproduction Steps

1.Using create: track_ Station selected track
2.Assembling trains
3.Handheld train casing right click on the rail
...

### Expected Result

No crash created train

### Operating System

window 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

forge 43.2.14

**Comment by IThundxr** [comment]
Downgrade Create to 0.5.1b since Create 0.5.1c isnt supported yet

Read the pinned issue next time

**Comment by Diemoerm** [comment]
But this is Forge, not Fabric ...

**Comment by IThundxr** [comment]
> But this is Forge, not Fabric ...

doesn't matter you still have to downgrade
