### ISSUE TITLE
Lagging when upgrade from steam 'n' rails 1.3.5 to 1.4.3

### ISSUE THREAD

**Issue by Pecl-ffdd** [Layers-of-Railways/Railway#229]
### Describe the Bug

I have an aternos server (Aternos has a function that the server can't crash on OutOfMemory because it decreases ticks per second). I had old versions of Create and Steam n rails so I upgraded them to the newest version. But when I started playing (only myself) the server started lagging. When I moved it returned me back. And this continued. Then I tried to remove the steam and rails and it stopped lagging. I uploaded older version of the mod and it was running like normal.

### Reproduction Steps

.

### Expected Result

I expected no lagging.

### Operating System

Server side aternos (Linux) Client side Windows

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.21

### Other Mods

- CC tweaked
- ConnectedTexturesMod
- Framed Blocks
- Chipped forge
- Chunk loaders
- Immersive Engineering
- Journey map
- Resource ful lib
- Serene Seasons
- Supermarinjn642configlib
- Supermarinjn642corelib
- World edit

**Comment by techno-sam** [comment]
Create 0.5.1c is not supported. it is likely that SnR's datafixers were running, if you can 'optimize world' then you can run the datafixers while you are not playing
