### ISSUE TITLE
Monorail bug

### ISSUE THREAD

**Issue by DominionMaster** [Layers-of-Railways/Railway#230]
### Describe the Bug

When placing bogies on station section on Monorail, it will crash the world save everytime.

### Reproduction Steps

1. Build Monorail
2. Place station
3. Start assembly
4. place train block to create bogie
5. crash
...

### Expected Result

I expected to have a bogie for the monorail and not have the world crash everytime I try to open it.

### Crash Report or Log

https://pastebin.com/tevtD70s

### Operating System

Windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.21

**Comment by SpottyTheTurtle** [comment]
Downgrade Create to 0.5.1b. Next time read the pinned issue before making a new one.
