### ISSUE TITLE
Config option to either make separate gauges compatible or to remove them completely 

### ISSUE THREAD

**Issue by 20captainx12** [Layers-of-Railways/Railway#231]
### Describe the Suggestion

I run a server basically, and we like to encourage and see the endgame to be when players have all made a railway network and then connected them up. Players tend to focus on railway networks within their territory first however, and then later decide on combining them. However, this gauge update, while great for some, can be disastrous to me and other owners as you will run into situations where one faction has made a network in one gauge and another in a different gauge and then they cannot easily link their factions together. I simply ask that you add a way to either make these compatible or to have a way to optionally remove them. Thank you.

P.S. I love this mod and keep up the good work :)

**Comment by techno-sam** [comment]
Vanilla includes a way to optionally remove them: datapacks. You are free to make a datapack that makes these gauges uncraftable
