### ISSUE TITLE
Port to 1.20(.1)?

### ISSUE THREAD

**Issue by myron-obsolete-account** [Layers-of-Railways/Railway#234]
### Describe the Suggestion

I wanted to ask/suggest (but mostly ask) if a port to 1.20 and 1.20.1 is planned or already in development?

### Screenshots and Videos

N/A

### Additional Context

N/A

**Comment by IThundxr** [comment]
Awaiting create fabric 0.5.1c to release our update

**Comment by myron-obsolete-account** [comment]
> Awaiting create fabric 0.5.1c to release our update

what about forge?

**Comment by IThundxr** [comment]
We can't release the forge version until we can release the fabric version which is gonna be after create fabrics update comes out
