### ISSUE TITLE
Slab on custom rail types invisible when using shaders

### ISSUE THREAD

**Issue by ajmcquilkin** [Layers-of-Railways/Railway#235]
### Describe the Bug

I cannot place slabs covering non-default Create rails. I would expect to be able to cover all rails with any slab as described in the description of the mod. This only happens when using shaders.

### Reproduction Steps

1. Apply shaders using Sodium and Iris (e.g., BSL)
1. Place a custom rail type (e.g., "Ender Train Track")
2. Right click on the rail with a slab (e.g., "Deepslate Brick Slab")
3. Slab will not place on the rail as with the default create rail

### Expected Result

I expect the slab to cover the rail as with the default create rail. This does not happen.

### Screenshots and Videos

![2023-08-23_15 08 44](https://github.com/Layers-of-Railways/Railway/assets/46639306/8180720f-f169-4c91-a0fc-b1dba39af467)

### Crash Report or Log

N/A

### Operating System

Windows 11

### Mod Version

1.4.3

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.14.22

### Other Mods

N/A, no crash occurred.

**Comment by ajmcquilkin** [comment]
Update on this bug -- this only seems to happen when using shaders with the pack. I'm imagining this might be the same issue as #169 and #180.

**Comment by techno-sam** [comment]
Please let me know if this issue persists with 1.5.0 @ajmcquilkin

**Comment by CityScrambler** [comment]
Fixed it for me. Non straight track pieces were formerlly invisible but with 1.50 the same track pieces are no longer invisible
(Fabric 1.19.2, Iris 1.50)
