### ISSUE TITLE
Train Casing: Minecraft crashes when selecting the boogey type

### ISSUE THREAD

**Issue by psujettna8** [Layers-of-Railways/Railway#236]
### Describe the Bug

So, when I use Minecraft and select the Train casing with Alt, I see some options, but when selecting them, it pops up:
Saving world
and minecraft closes.

### Reproduction Steps

1. Get a train casing
2. Hold Alt and select the triple axle type and click on it
3. Highlight an option
==CRASH HAPPENED HERE==

### Expected Result

I would select the option and then spawn the boogey that has triple wheels.

### Crash Report or Log

https://pastebin.com/u4emUxhL

### Operating System

Windows 11, version 23H2 (OS build 25931.1000)

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.21

### Other Mods

Create
Create Decoration Casing
GeckoLib
Create Modern Train Parts

### Additional Context

If this mod is incompatible with the Decoration Casing mod, please check it first.

**Comment by AngelTechnic** [comment]
downgrade your create version to 0.5.1b, steam n rails doesn't support 0.5.1c yet.
