### ISSUE TITLE
Special Redering of Flywheel does not work when updating from 1,92.2 to 1.20.1

### ISSUE THREAD

**Issue by Port06** [Layers-of-Railways/Railway#240]
### Describe the Bug

I want to update my world to 1.20.1 and all special models don't get render as well as trains get aplied wierd colors
![2023-08-31_14 00 47](https://github.com/Layers-of-Railways/Railway/assets/115357047/64153327-ec59-48a1-97e4-ad273ddd5a70)
![2023-08-31_14 00 13](https://github.com/Layers-of-Railways/Railway/assets/115357047/183f987a-b618-48f3-b18b-e5fb390f64f4)

### Reproduction Steps

1.Get a world with the mods in 1.19.2
2.Update to 1.20.1
3.
...

### Expected Result

Wrong rendering

### Screenshots and Videos

![2023-08-31_14 00 13](https://github.com/Layers-of-Railways/Railway/assets/115357047/028843c8-fa5f-4057-8df3-6b42458aa0d5)
![2023-08-31_14 00 47](https://github.com/Layers-of-Railways/Railway/assets/115357047/e393c46a-9a64-424f-b70e-494f0f107dbb)

### Crash Report or Log

none

### Operating System

Windows 10

### Mod Version

1.5.0

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.1.39

### Other Mods

Advancement Plaques
AI Improvements Apple skin
Jei
Rubidium
Rubidium Extras
Magnesium
Magnesium Extras
Canary
Fast load
Fast Suit
Cull Leaves
Clumps
Create
Create Steam and Rails
Essential Ferrite Core
Not enough Crashes
World Edit Biome's o Plenty
Terra blender
Moonlight Lib
Placebo
Sound Physics Remastered
Soul Fire'd

### Additional Context

Everything works as intended, however it does not render properly as well as being laggier

**Comment by IThundxr** [comment]
you probs have some sort of debug mode on for create

also this doesnt seem snr related? does this happen without snr?

**Comment by Port06** [comment]
After updating my world to 1.20.1 again without snr this time around the same happens, (plus of course, everything from snr is deleted). 
It surely is a file that I have to copy over from 1.19.2 to 1.20.1 right? It is likely not a bug.

**Comment by Port06** [comment]
Thanks for your help!

**Comment by Port06** [comment]
Does anyone know anything that could help me update the world?

**Comment by IThundxr** [comment]
Make a new instance and just copy over the world and mods folder

**Comment by Port06** [comment]
Well sorry, creating a new instance and copying the world over is exactly what I did. Then that happens, but I could maybe go everywhere on my world and brake and replace everything glitched as i comes back to normal. It would just take to long.
Using f3 + A, a  /flywheel command,  or switching dimension does not solve anything.
I'll search if somebody else has the same issue, but so far I found no one

**Comment by Port06** [comment]
Sorry again, I've found the issue!
it turns out that you musn't use rubidium and flywheel together otherwise there are some rendering issues.
But now my game is way to laggy, is there an other optimization mod for forge other than rubidium?
