### ISSUE TITLE
Conductor crashing server

### ISSUE THREAD

**Issue by hexo27** [Layers-of-Railways/Railway#241]
### Describe the Bug

Whenever I spawn in a conductor it crashes the server after a bit and when I control the conductor with the Remote Lens it crashes the server almost instantly. I have tried it in singleplayer and it worked fine and didn't crash.

### Reproduction Steps

1. Get a server
2. Spawn a conductor
3. Wait a while or control the conductor

### Expected Result

I expected the conductor to not crash the server but it did.

### Crash Report or Log

https://pastebin.com/KzS4BW89

### Operating System

Windows 11

### Mod Version

1.5.0

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Forge - 47.1.44

### Other Mods

CC: Tweaked
Ars Creo
Ars Nouveau
Biomes O' Plenty
Blue Skies
Botarium
Chisels & Bits - For Forge
Create
Create Crafts & Additions
Create Steam 'n' Rails
Curios API (Forge)
Deeper And Darker
Dimensional Expansion
Eureka! Ships! for Valkyrien Skies
Gaia Dimension
Kotlin for Forge
Lucky TNT Lib
Lucky TNT Mod (Too Much TNT)
Macaw's Bridges
Macaw's Bridges (Biomes O' Plenty)
Macaw's Doors
Macaw's Fences (Biomes O' Plenty)
Macaw's Fences and Walls
Macaw's Lights and Lamps
Macaw's Paths and Pavings
Macaw's Roofs
Macaw's Roofs - Biomes O' Plenty
Macaw's Trapdoors
Nullscape
Patchouli
Pehkui
Resourceful Config
Resourceful Lib
Structure Gel API
SuperMartijn642's Config Lib
SuperMartijn642's Core Lib
TerraBlender (Forge)
The Twilight Forest
Valkyrien Skies
Vanishmod
WorldEdit
Wormhole (Portals)

**Comment by randomnessyt92** [comment]
I made a typo the server actually runs on 47.1.43 not 47.1.44

**Comment by hexo27** [comment]
i downgraded to create 1.5.1c to see if that would help but it still crashes
i also updated the server to forge 47.1.44 and it still crashed

**Comment by IThundxr** [comment]
Could you try the latest update?
