### ISSUE TITLE
Game Crashes when placing a train casing onto Wide or Narrow train tracks in train creation.

### ISSUE THREAD

**Issue by LimeShep** [Layers-of-Railways/Railway#242]
### Describe the Bug

Error when the game crashed: The game crashed whilst rendering block entity
Error: java.lang.NoSuchMethodError: 'com.simibubi.create.content.trains.bogey.BogeyRenderer$BogeyModelData[] com.railwayteam.railways.content.custom_bogeys.CRBogeyRenderer$NarrowSmallBogeyRenderer.getTransform(com.jozufozu.flywheel.core.PartialModel, com.mojang.blaze3d.vertex.PoseStack, boolean, int)'

Issue is explained in the title

### Reproduction Steps

1. Place a wide or narrow train track
2. Place a train station and bind it to the track
3. Place a casing block onto the blue train track
And here is the crash.
...

### Expected Result

Instead of the crash, the game should just put a small or wide train bogey.

### Crash Report or Log

https://pastebin.com/t1yqaKWF

### Operating System

Windows 11

### Mod Version

1.5.0

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.21

### Other Mods

Architect's Palette
Architectury
Biomes O' Plenty
CC - Tweaked
Chunkloaders
Cloth Config
Create
CreateDeco
Essential
FantasyFurniture
FramedBlocks
GeckoLib
Item Fiters
JustEnoughItems
Macaw's Furniture
Moving Elevators
MrCrayfish's Furniture
NoChatReports
Optifine
Rechiseled
Shulkerboxtooltip
Steam n' Rails
Supermartjin's Core and Config Lib
TerraBlender
Travelers Backpack
Ultimate Car Mod
WorldEdit

**Comment by IThundxr** [comment]
update create
