### ISSUE TITLE
recipes don't show in REI

### ISSUE THREAD

**Issue by vlad1m** [Layers-of-Railways/Railway#244]
### Describe the Bug

majority of rail items don't show their recipes when using REI, both vanilla wood types and modded wood types are affected.

### Reproduction Steps

1.Enter a world
2.Use REI function of vewing recipes.

### Expected Result

To see the recipes 

### Operating System

windows 10

### Mod Version

1.5.0

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.11

**Comment by IThundxr** [comment]
This would be a issue for REI since we dont actually ship any compat and the compat thats used is on create/(jei/rei/emi)'s side since we just add recipes that it should automatically pickup
