### ISSUE TITLE
Doesn't load past mojang screen with Automobility (MOD INCOMPAT)

### ISSUE THREAD

**Issue by ConqAra** [Layers-of-Railways/Railway#246]
### Describe the Bug

Crashes during loading screen (right after launch)

### Reproduction Steps

Use latest version (fyi im using my modpack so mod incompats are bewared.)

### Expected Result

Load up the game without crashing.

### Crash Report or Log

https://mclo.gs/Fbr0IN2

### Operating System

Windows 10

### Mod Version

1.4.4

### Create Mod Version

0.5.1c

### Minecraft Version

1.18.2

### ModLoader and Version

Fabric 0.14.22

**Comment by IThundxr** [comment]
Try with just Steam 'n' Rails + Create

**Comment by Norai0** [comment]
Delete a mod called "MemoryLeakFix"

**Comment by ConqAra** [comment]
> Delete a mod called "MemoryLeakFix"

Okay that worked, it doesn't crash but it still wont get off the "mojang" screen. here's another log: [https://mclo.gs/xyEfENh](https://mclo.gs/xyEfENh)
![image](https://github.com/Layers-of-Railways/Railway/assets/76233356/8368ad28-7ff8-49ad-af0b-309f4e539428)

**Comment by IThundxr** [comment]
Can you try just steam n rails + create?

**Comment by ConqAra** [comment]
It works with just those two, the problem is that I want to know whats causing it to not work in the modpack. I'm trying to find the other incompatibilities as well and maybe hopefully get them fixed or at least known about.

**Comment by IThundxr** [comment]
Try a binary search and if you find out what causes it let me know and I'll see if it's fixable on our side https://en.m.wikipedia.org/wiki/Binary_search_algorithm

**Comment by Negative232** [comment]
I just tested it, found out it was "dynamiccrosshair-3.5.2+1.18.2" that was causing the crash.

**Comment by ConqAra** [comment]
@IThundxr Found it. It was [Automobility](https://github.com/FoundationGames/Automobility). Game wouldn't load pass the loading screen with it in. And yeah, memoryleakfix won't load with it either, but that was already known I think.

Log: [https://paste.ee/p/SJNMP](https://paste.ee/p/SJNMP)

Automobility Version: automobility-0.3+1.18.2 (latest release for 1.18.2)

**Comment by IThundxr** [comment]
That's weird it works on 1.20 I guess this version is just too old and doesn't work

**Comment by SpottyTheTurtle** [comment]
@ConqAra https://modrinth.com/mod/autos_n_rails should fix it
