### ISSUE TITLE
game crashes when assembling train

### ISSUE THREAD

**Issue by spacedragon06** [Layers-of-Railways/Railway#248]
### Describe the Bug

when assembling a train on th narrow gauge track (haven't tested on the other gauges) the game crashes and when you try to open the world again the game crashes and gives me the exit code 255

### Reproduction Steps

1.Load into a world
2.Place down some tracks
3.Place down a station and start building a train
4.Assemble the train
5.Game crashes

### Expected Result

the train would assemble into a train contraption

### Screenshots and Videos

[steam_n_rails_bug_av1.webm](https://github.com/Layers-of-Railways/Railway/assets/138886021/1c855d11-d2aa-4cf6-92c9-04ee102f4b3c)

### Operating System

Debian 12

### Mod Version

1.5.0

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 0.14.22

### Other Mods

![modslist](https://github.com/Layers-of-Railways/Railway/assets/138886021/99bfb15c-68a8-424d-b9bd-a67746d0db3e)

### Additional Context

hardware and software info(source: crash log):
Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.1.0-11-amd64
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1402630664 bytes (1337 MiB) / 4127195136 bytes (3936 MiB) up to 25769803776 bytes (24576 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7600 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Raphael
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x164e
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 23230.09
	Virtual memory used (MB): 14769.61
	Swap memory total (MB): 7628.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Loaded Shaderpack: YoFPS+High+(Chocapic13+Edit).zip
		Profile: Custom (+0 options changed by user)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.22-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon Graphics (gfx1036, LLVM 15.0.6, DRM 3.49, 6.1.0-11-amd64) GL version 4.6 (Core Profile) Mesa 22.3.6, AMD
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/More_Music_Discs (incompatible), file/VanillaTweaks_r632112.zip (incompatible), fabric
	Current Language: en_gb
	CPU: 12x AMD Ryzen 5 7600 6-Core Processor
	Server Running: true
	Player Count: 1 / 8; [class_3222['spacedragon06'/340, l='ServerLevel[bug test]', x=-241.75, y=75.44, z=39.51]]
	Data Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental

**Comment by IThundxr** [comment]
Please send your crash log from crash-reports/

**Comment by spacedragon06** [comment]
[crash-2023-09-09_10.58.08-client.txt](https://github.com/Layers-of-Railways/Railway/files/12565640/crash-2023-09-09_10.58.08-client.txt)
here is the crash report

**Comment by IThundxr** [comment]
remove starlight from your client its only needed on the server now
