### ISSUE TITLE
Create Steam 'n' Rails New Bogey Crashes Game

### ISSUE THREAD

**Issue by TheGrayAllay** [Layers-of-Railways/Railway#251]
### Describe the Bug

Game crashes when clicking on a new bogey in the radial menu from create Steam And Rails

### Reproduction Steps

1. Pressing Alt.
2. Hovering over Bogey Style
3. Click It

### Expected Result

Game should not crash and allow me to place the bogeys from the menu.

### Crash Report or Log

https://mclo.gs/T7NS62E

### Operating System

Windows 10

### Mod Version

1.5.0

### Create Mod Version

0.5.1a

### Minecraft Version

1.18.2

### ModLoader and Version

Forge

### Other Mods

Supplementary
Worldedit
CreateDeco
Geckolib
cBAndB
Architects palate
CreateTeleporters
FramedBlocks
Create-Stuff-Additions
JEI
LaboratoryBlocks
DungeonBlocks
Mantle
CreateArmory
Create-Misc.-And-Things
Twigs
Create Dreams and Desires
Excessive Building
Patchouli-1.18.2-71.1
flywheel-forge-1.18.2-0.6.8.a
supermartijn642corelib-1.1.12-forge-mc1.18
Decorative+Blocks-forge-1.18.2-2.1.2
Fusion-1.18.2-4.1.1.1
shetiphiancore-1.18-3.10.12
selene-1.18.2-1.17.9
DustrialDecor-1.3.3-1.18.2
CreateCasing-1.18.2-1.3
GottschCore-mc1.18.2-f40.1.0-v2.1.0
stonier_stones-+2.0.1+[forge-1.18.2]
movingelevators-1.4.3a-forge-mc1.18 (1)
curios-forge-1.18.2-5.0.9.1
create_tweaked_controllers-1.18.2-1.2.1
create_crystal_clear-0.2.1-1.18.2
labels-1.18.2-1.0
supermartijn642configlib-1.1.7-forge-mc1.18
CTM-1.18.2-1.1.4+4
armortrims-1.18.2-1.3.3
SimpleCoreLib-1.18.2-4.3.1.4
Masonry_Blocks_1.18.2_1.0
betterfpsdist-1.18.2-1.5

### Additional Context

I already downdated create to 0.5.1a, so the version is not the issue.

**Comment by UnitingMatrixXCV** [comment]
You've got an old version of Create that's unsupported by that version of SnR.
Update Create to 0.5.1c

**Comment by Krinkov74u** [comment]
Im having this issue in create 0.5.1c to let ya know.
