### ISSUE TITLE
placement bug with bogeys

### ISSUE THREAD

**Issue by Hans-Frans** [Layers-of-Railways/Railway#252]
### Describe the Bug

when creating a train on narrow gauge tracks, when a bogey is placed, the game crashes, I also noticed some issues with texture loading in the log

### Reproduction Steps

1. open world with newest Create Steam n' Rails in 1.19.2
2. place narrow gauge tracks
3. create a station on that track and make new train
4. place bogey

### Expected Result

normally should show prompt to choose bogey style, but bug causes game to crash

### Crash Report or Log

https://pastebin.com/c6um2tcB

### Operating System

Windows 11

### Mod Version

1.5.0

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.3

### Other Mods

AppleSkin
Chipped
ConnectedTexturesMod
CreateDeco
Decorative Blocks
Just Enough Items
Oh the Biomes You'll Go
ResourcfulLib
Sophisticated Backpacks
Sophisticated Core
Storage Drawers
Terrablender

### Additional Context

might occur with wide tracks, haven't tested it with those

**Comment by IThundxr** [comment]
Update create mod
