### ISSUE TITLE
ConductorCapItem returns null as its repair ingredient

### ISSUE THREAD

**Issue by MartinTheDragon** [Layers-of-Railways/Railway#253]
### Describe the Bug

Instead of `Ingredient.EMPTY`, `null` is being returned, which can lead to issues like <https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/issues/66>. To summarize, other mods might depend on the repair ingredient in certain ways, and returning `null` will lead to a null pointer exception.

### Reproduction Steps

Refer to <https://github.com/MartinTheDragon/Nuclear-Tech-Mod-Remake/issues/66>.
Hovering over a conductor cap in the inventory will also cause this.

### Expected Result

No null pointers being returned if constant values such as `Ingredient.EMPTY` exist.

### Operating System

EndeavourOS, based on Arch Linux

### Mod Version

1.4.4

### Create Mod Version

0.5.1c

### Minecraft Version

1.18.2

### ModLoader and Version

Forge 40.2.10

### Other Mods

[Nuclear Tech Mod Remake for 1.18](https://codeberg.org/MartinTheDragon/Nuclear-Tech-Mod-Remake)

**Comment by IThundxr** [comment]
I'll have to check however I think ingredient is annotated with @Nullable

**Comment by IThundxr** [comment]
Alright I've checked and this is 100% our fault I'll patch it up and release a new version hopefully today

**Comment by IThundxr** [comment]
Fixed in https://github.com/Layers-of-Railways/Railway/commit/b30b1f8203475cd7cb7fa2d19420089435f1e212
