### ISSUE TITLE
Crash when spawning wide bogey

### ISSUE THREAD

**Issue by fishauchocolat** [Layers-of-Railways/Railway#254]
### Describe the Bug

When i wanna create a bogey on the wide tracks it crashes the game , so i am now softlocked from my world until i can fix this bug because every time i load up my world it crashes immediatly , please help.

### Reproduction Steps

1.Place wide tracks
2.Right click on it while in building mode to create bogey
3.crash

### Expected Result

I dont really know what to put here , i just wanted to make a cool freight train

### Crash Report or Log

The game crashed whilst rendering block entity Error: java.lang.NoSuchMethodError: 'com.simibubi.create.content.trains.bogey.BogeyRenderer$BogeyModelData[] com.railwayteam.railways.content.custom_bogeys.CRBogeyRenderer$WideDefaultBogeyRenderer.getTransform(net.minecraft.world.level.block.state.BlockState, com.mojang.blaze3d.vertex.PoseStack, boolean, int)'

### Operating System

Windows 10

### Mod Version

1.5.0

### Create Mod Version

0.5.1d

### Minecraft Version

1.19.2

### ModLoader and Version

1.19.2-forge-43.2.3

**Comment by IThundxr** [comment]
Update create mod to 0.5.1c also 1.19 doesn't have 0.5.1d so not sure where you got that from
