### ISSUE TITLE
Crash 1.19.2 1.3.5 spongepowered error

### ISSUE THREAD

**Issue by DanniDesign** [Layers-of-Railways/Railway#255]
### Describe the Bug

Launching the game with these mods
![image](https://github.com/Layers-of-Railways/Railway/assets/70161891/f3f87052-6169-4e00-a785-1a788efd9c3c)
crashes when opening and returns [this crash log](https://mclo.gs/ezxDh0H).

### Reproduction Steps

Use the mods i used and it crashes

### Expected Result

a fine working game 

### Operating System

Windows 10

### Mod Version

1.3.5

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.23

### Other Mods

![image](https://github.com/Layers-of-Railways/Railway/assets/70161891/aa0903d9-fc0e-4e3a-a915-1f25c6c0ee4f)

**Comment by IThundxr** [comment]
We do not support optifine please use something else like rubidium + oculus

**Comment by DanniDesign** [comment]
@IThundxr Ah that explains. Thanks!
