### ISSUE TITLE
Crashes when trying to construct a monorail

### ISSUE THREAD

**Issue by Negative232** [Layers-of-Railways/Railway#256]
### Describe the Bug

I was trying to construct a monorail, only for the same to game to crash once I tried to play down train castings to form a bogey.

### Reproduction Steps

1.Use Train Station block with monorail track 
2.Try to use Train Casting block to form a bogey (only the bogey, no other blocks)
3.Crash
...

### Expected Result

I expected the bogey to form once the train casting was placed, allowing me to create a monorail car.

### Crash Report or Log

https://paste.ee/p/TFuoV

### Operating System

Windows 10

### Mod Version

1.4.4

### Create Mod Version

0.5.1c

### Minecraft Version

1.18.2

### ModLoader and Version

Fabric 0.14.22

**Comment by IThundxr** [comment]
Update steam n rails

**Comment by Negative232** [comment]
@IThundxr What do you mean update? I am on the latest version possible for 1.18.2, there is no 1.5.0 for it.
![image](https://github.com/Layers-of-Railways/Railway/assets/102703605/9e752570-2aaa-4e5c-9543-94296733222c)

**Comment by IThundxr** [comment]
> @IThundxr What do you mean update? I am on the latest version possible for 1.18.2, there is no 1.5.0 for it. ![image](https://user-images.githubusercontent.com/102703605/266855653-9e752570-2aaa-4e5c-9543-94296733222c.png)

try reinstalling create & also steam n rails

**Comment by Negative232** [comment]
nvm, reinstall worked, sorry for wasting your time
