### ISSUE TITLE
crash when creating an narrow and an wide boogy

### ISSUE THREAD

**Issue by VRPioneerPaul** [Layers-of-Railways/Railway#258]
### Describe the Bug

when i tried to create an narrow and an wide boogy my game crashed instantly and in the crash report it says boogy rendering error on my pc with 16 gb ram and an gtx 1060

### Reproduction Steps

1. make an track (narrow/wide)
2. make an train staition
3. create new train
4. create boogy

### Expected Result

game will crash direktly at placing

### Operating System

windows 10

### Mod Version

1.5.0

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

forge 43.2.6

**Comment by IThundxr** [comment]
Update create mod
