### ISSUE TITLE
Crashes upon choosing a bogey with farmer's delight installed

### ISSUE THREAD

**Issue by destined-to-wander** [Layers-of-Railways/Railway#260]
### Describe the Bug

Bogey selection screen for tracks results in a crash. This only happens when using farmer's delight version 1.4.0 to 1.4.2.

### Reproduction Steps

1. Have farmers delight version 1.4.0, 1.4.1 or 1.4.2 and create version 1.5.1 for 1.20.1 on a modrinth modpack
2. Begin assembling a train
3. hold down the schematic focus key while holding a train casing and looking at a track
4. It will freeze immediately.

### Expected Result

For the game to let me select a bogey and not crash

### Crash Report or Log

https://pastebin.com/W0chfyzy

### Operating System

MacOS Ventura Ver 13.0.1

### Mod Version

1.5.1

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 0.14.22

### Other Mods

Create Fabric 0.5.1
Fabric API
Farmer's delight [fabric]

### Additional Context

i haven't tried farmer's delight 1.4.1 yet but I'm guessing the result will be the same. Also I was using the modrinth launcher.

**Comment by IThundxr** [comment]
This is a farmers delight fabric issue and should be reported on their github
