### ISSUE TITLE
Bogey Selector crash in custom Forge modpack

### ISSUE THREAD

**Issue by N8rtot** [Layers-of-Railways/Railway#261]
### Describe the Bug

Trying to place, or select bogey type from the toolbox-esque menu will result in a crash

### Reproduction Steps

1. Open bogey selection menu whilst holding train casing (left alt + right click)
2. Select any option 
3. Minecraft either hangs indefinitely or crashes

1. Place a Train Casing on any Narrow/Wide gauge rails
2. Same results as above

### Expected Result

I was hoping to be able to use the narrow/wide gauge rail types and try out the new bogey types

### Crash Report or Log

https://mclo.gs/SZXGHdY

### Operating System

Windows 10

### Mod Version

1.5.0

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.23

### Other Mods

[modlist.txt](https://github.com/Layers-of-Railways/Railway/files/12602799/modlist.txt)

### Additional Context

Swapping mod versions up or down seems to make the mod 'Entity Model Features' crash on any of its versions too, and I cant get rid of that mod as the game will crash due to another error. So im not sure if its still secretly something wrong with mod versions or something else entirely.

**Comment by IThundxr** [comment]
update create mod to 0.5.1c
