### ISSUE TITLE
Trains with triple axle bogeys stop halfway between blocks at stations

### ISSUE THREAD

**Issue by GJdude** [Layers-of-Railways/Railway#262]
### Describe the Bug

When stopping at stations, trains using either of the triple axle bogey styles won't stop on a block, but halfway between two. Naturally, this will cause some problems when trying to align the train with something at a station.

(Interestingly, the front and rear-most axles on the bogey line up with the block grid, if that's at all related)

### Reproduction Steps

1. Create a train with either of the triple-axle bogeys
2. Assemble, reverse from station
3. Approach station, train will stop in the wrong position.

### Expected Result

The train should align with the block grid when stopped at a station, as it would with any other bogey type.

### Screenshots and Videos

![misalignment](https://github.com/Layers-of-Railways/Railway/assets/83022658/9f83d3fa-f16a-4a47-9e1d-189cce1a8d0a)

### Operating System

Windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 0.14.22

**Comment by GJdude** [comment]
The bogey type will also change to the Heavyweight style when disassembling the train if it was set to Radial.

**Comment by IThundxr** [comment]
> The bogey type will also change to the Heavyweight style when disassembling the train if it was set to Radial.

Are you using any other mods?

**Comment by GJdude** [comment]
> Are you using any other mods?

Just the bare minimum for testing. create, fabric api, steam 'n' rails, sodium and indium. The halfway-stopping issue also occurs on this minimum setup.

**Comment by IThundxr** [comment]
Hmm I can't seem to reproduce this

**Comment by GJdude** [comment]
I've set up a new install and started a new world in singleplayer creative with the following:
fabric loader 0.14.22-1.20.1
mods:
fabric-api-0.88.1+1.20.1
create-fabric-0.5.1-d-build.1161
indium-1.0.21+mc1.20.1
sodium-fabric-mc1.20-0.4.10+build.27
Steam_Rails-1.5.1+fabric-mc1.20.1

And sure enough, when backing the train up then returning it to the station, it stops like so.
![Untitled](https://github.com/Layers-of-Railways/Railway/assets/83022658/f3be6392-d105-4630-a722-f3dfbf28d2b4)

**Comment by Krinkov74u** [comment]
On 1.19.2 fabric I get this issue as well with a large modpack, I also get an issue with pressing alt with a train casing causing the game to crash. Lovely mod btw

**Comment by IThundxr** [comment]
> On 1.19.2 fabric I get this issue as well with a large modpack, I also get an issue with pressing alt with a train casing causing the game to crash. Lovely mod btw

For the crash issue send logs/make a new issue

**Comment by IThundxr** [comment]
Closed since cant reproduce in latest dev

**Comment by IThundxr** [comment]
Reopen the issue if it still happens in 1.6.0 once its out
