### ISSUE TITLE
Game crashes when trying to render new bogey types (including in selection menu)

### ISSUE THREAD

**Issue by ParsnipThePossum** [Layers-of-Railways/Railway#263]
### Describe the Bug

When I try to place any new type of bogeys added by the mod the game crashes, if bogey is placed it crashes immediately and repeats every time I open the world as it loads the chunk with said bogey

### Reproduction Steps

1. Open world in 1.19.2 with Create 0.5.1b and Create Steam n' Rails v. 1.5.1 or 1.5.0
2. Place down tracks and station and assemble train
3. Open bogey selection and try selecting any of the steam n' rails bogeys

### Expected Result

Train bogey selects without crashing and places down

### Screenshots and Videos

First I place track, station and open assembly
![2023-09-16_20 13 51](https://github.com/Layers-of-Railways/Railway/assets/145223143/9f797c0a-2507-429b-9070-da13ebed404a)
then when I try to even open the bogey selection of the new bogeys it crashes 
![image](https://github.com/Layers-of-Railways/Railway/assets/145223143/a5bc9e28-4bb5-4296-a60c-ce994e66e3f2)

### Crash Report or Log

https://mclo.gs/i8akKDW

### Operating System

Windows 11

### Mod Version

1.5.1

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.21

### Other Mods

mod:create_things_and_misc, mod:easyanvils (incompatible), mod:netherportalfix (incompatible), mod:infernalexp, mod:scena (incompatible), mod:botarium, mod:paragon, mod:sophisticatedcore (incompatible), mod:forgeendertech, mod:xaeroworldmap, mod:ctm (incompatible), mod:controlling (incompatible), mod:mixinextras (incompatible), mod:upgradednetherite_items (incompatible), mod:sophisticatedbackpacks (incompatible), mod:create_dragon_lib, mod:simpleplanes (incompatible), mod:create_compressed, mod:railways (incompatible), mod:balm (incompatible), mod:jeresources, mod:more_villager_trades, mod:leavesbegone (incompatible), mod:dummmmmmy (incompatible), mod:supplementaries (incompatible), mod:upgradednetherite (incompatible), mod:chipped (incompatible), mod:farmersdelight, mod:handcrafted, mod:ambientsounds (incompatible), mod:stacking_potions, mod:endersdelight, mod:do_a_barrel_roll (incompatible), mod:supermartijn642corelib (incompatible), mod:resourcefulconfig, mod:create_sabers, mod:curios, mod:patchouli (incompatible), mod:suppsquared (incompatible), mod:rightclickharvest (incompatible), mod:collective, mod:camera (incompatible), mod:alloyedguns, mod:biomebackport, mod:resourcefullib (incompatible), mod:constructionwand, mod:deeperdarker, mod:chimes, mod:productivebees, mod:jadeaddons (incompatible), mod:framework (incompatible), mod:infinitetrading, mod:easyshulkerboxes (incompatible), mod:geckolib3 (incompatible), mod:betteradvancements (incompatible), mod:elytraslot, mod:inventorysorter (incompatible), mod:gourmet, mod:cgm (incompatible), mod:easymagic (incompatible), mod:jei (incompatible), mod:visualworkbench (incompatible), mod:universalbonemeal (incompatible), mod:epicsamurai, mod:caelus (incompatible), mod:sootychimneys (incompatible), mod:fallingleaves (incompatible), mod:clumps (incompatible), mod:comforts, mod:naturescompass (incompatible), mod:sereneseasons, mod:decorative_blocks (incompatible), mod:create_confectionery, mod:explorerscompass (incompatible), mod:terralith, mod:blueprint (incompatible), mod:savage_and_ravage (incompatible), mod:clayworks (incompatible), mod:woodworks (incompatible), mod:buzzier_bees (incompatible), mod:ars_nouveau, mod:toomanyglyphs (incompatible), mod:forge, mod:moderntrainparts (incompatible), mod:ironchest (incompatible), mod:treeplacer, mod:terrablender, mod:moonlight (incompatible), mod:mousetweaks, mod:magnumtorch (incompatible), mod:jade (incompatible), mod:creativecore (incompatible), mod:createutilities (incompatible), mod:adlods, mod:spectrelib (incompatible), mod:nethersdelight (incompatible), mod:create_so (incompatible), mod:brewinandchewin (incompatible), mod:farmersrespite (incompatible), mod:flywheel (incompatible), mod:alloyed (incompatible), mod:create, mod:createdeco (incompatible), mod:create_central_kitchen, mod:ars_creo (incompatible), mod:create_crystal_clear (incompatible), mod:xaerominimap, mod:decoration_delight, mod:create_sa, mod:polymorph, mod:justenoughprofessions, mod:storagedrawers (incompatible), mod:nocubescreateexp, mod:ars_elemental, mod:crittersandcompanions (incompatible), mod:iknowwhatimdoing (incompatible), mod:upgradedcore (incompatible), mod:bettertridents (incompatible), mod:oceansdelight, mod:automobility (incompatible), mod:appleskin, mod:connectedglass (incompatible), mod:upgradednetherite_ultimate (incompatible), mod:puzzleslib (incompatible), mod:charmofundying, mod:delightful (incompatible), mod:cosmeticarmorreworked (incompatible), mod:valhelsia_core (incompatible), mod:forbidden_arcanus (incompatible), mod:chiselsandbits (incompatible), mod:create_enchantment_industry (incompatible), mod:overflowingbars (incompatible), mod:treeplacer_terralithaddon_mr, mod:createaddition (incompatible), mod:ad_astra (incompatible)

**Comment by IThundxr** [comment]
Update create mod
