### ISSUE TITLE
Invalid path for 'railways:models/block/bogey/wide/scotch_yoke/Broad_Gauge_L_0-2-0.bbmodel'

### ISSUE THREAD

**Issue by Xyphenore** [Layers-of-Railways/Railway#264]
### Describe the Bug

An error is printed on console for 'railways:models/block/bogey/wide/scotch_yoke/Broad_Gauge_L_0-2-0.bbmodel'.

Console: 'Invalid path in pack: railways:models/block/bogey/wide/scotch_yoke/Broad_Gauge_L_0-2-0.bbmodel, ignoring'

### Reproduction Steps

1. Install the mod
2. Run the game with the console
3. Warning is printed on console after game loaded

### Expected Result

No error

### Operating System

Windows 10 22H2

### Mod Version

1.5.1

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.1.47

**Comment by IThundxr** [comment]
fixed in a56ce3c90ac2d56c5fdd8ffa389af52991fe55a9
