### ISSUE TITLE
Invalid path for TODO.txt

### ISSUE THREAD

**Issue by Xyphenore** [Layers-of-Railways/Railway#265]
### Describe the Bug

The error 'Invalid path in pack: byg:textures/block/track/TODO.txt, ignoring' is printed on console.

### Reproduction Steps

1. Install the mod
2. Run the game with console
3. Error is printed on console

### Expected Result

No error

### Operating System

Windows 10 22H2

### Mod Version

1.5.1

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.1.47

**Comment by IThundxr** [comment]
fixed in a56ce3c90ac2d56c5fdd8ffa389af52991fe55a9
