### ISSUE TITLE
Warnings about mixin injection

### ISSUE THREAD

**Issue by Xyphenore** [Layers-of-Railways/Railway#266]
### Describe the Bug

I got these warnings:

- @Inject(@At("INVOKE")) Shift.BY=2 on railways-common.mixins.json:client.MixinBlockElement_Deserializer::handler$zeg000$shutUpSizeLimitFrom exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
- @Inject(@At("INVOKE")) Shift.BY=2 on railways-common.mixins.json:client.MixinBlockElement_Deserializer::handler$zeg000$shutUpSizeLimitTo exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

### Reproduction Steps

1. Install the mod
2. Run the game with the output console
3. Warnings are printed on console

### Expected Result

No warnings

### Operating System

Windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.1.47

**Comment by IThundxr** [comment]
This doesn't actually crash your game or anything so it's fine

**Comment by IThundxr** [comment]
Actually I'll fix the warning anyway

**Comment by Xyphenore** [comment]
The game works. Just warnings are printed.

**Comment by IThundxr** [comment]
dont think this can actually be fixed and might be a upstream mixin thing
