### ISSUE TITLE
Create unlimited support

### ISSUE THREAD

**Issue by ghost** [Layers-of-Railways/Railway#267]
### Describe the Bug

I guess this is not really a bug, but the game crashes if you also have create unlimited installed.
This was not a problem before 1.5.0 or later versions. If I understood correctly they overright a file that you try to mixin to. Isn't there a way to fix this

### Reproduction Steps

1.install create Steam n rails
2.install create unlimited 
3. Open game and see it crash
...

### Expected Result

Working game

### Operating System

Windows 11

### Mod Version

1.5.1

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Forge

### Other Mods

Create unlimited

### Additional Context

It says it's missing track tile entity or something like that in the crash log

**Comment by IThundxr** [comment]
This is gonna be fixed on create unlimited's side and iirc it already has been they just need to put out a new release

**Comment by Exagerat** [comment]
What does iirc mean?

**Comment by IThundxr** [comment]
It means "if I recall correctly"

**Comment by rhysdh540** [comment]
New release coming never (for legal reasons this is a joke, mixin just hates me)
