### ISSUE TITLE
Crash on rendering custom bogeys

### ISSUE THREAD

**Issue by Gayowulf** [Layers-of-Railways/Railway#270]
### Describe the Bug

Immediately on placing a train casing to create a bogey on Wide or Narrow tracks, and subsequently on any attempt to load the chunk, the game crashes trying to render the bogey entity. This does not occur on default Create tracks, only the Wide and Narrow variants added by CSnR.
_UPDATE: I've now observed this with a monorail bogey as well. So, possibly it's all custom bogeys._

See attached crash report.

[crash-2023-09-21_22.01.14-client.txt](https://github.com/Layers-of-Railways/Railway/files/12695974/crash-2023-09-21_22.01.14-client.txt)

### Reproduction Steps

1. Place a straight length of wide or narrow track (minimum length 3)
2. Bind a Train Station to the track
3. Activate the Train Station and select "Create new Train"
4. Place a Train Casing on the highlighted track block to create a new bogey. The client immediately crashes.

### Expected Result

Expect to be able to render trains on Wide and Narrow tracks without crashing.

### Crash Report or Log

https://github.com/Layers-of-Railways/Railway/files/12695974/crash-2023-09-21_22.01.14-client.txt

### Operating System

Ubuntu 23.04

### Mod Version

1.5.0

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.14.22

### Other Mods

advancedcompass: Advanced Compass 1.2.14
advancementinfo: AdvancementInfo 1.19.1-fabric0.58.5-1.3.1
advdebug: Advancements Debug 2.3.0
animatica: Animatica 0.5+1.19
antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
appleskin: AppleSkin 2.4.1+mc1.19
badpackets: Bad Packets 0.2.1
betterclouds: Better Clouds 1.2.10+1.19.2
betterf3: BetterF3 4.0.0
bettermounthud: Better Mount HUD 1.2.0
borderlessmining: Borderless Mining 1.1.5+1.19
byg: Oh The Biomes You'll Go 2.0.1.4
cem: Custom Entity Models 0.7.1
charm: Charm 4.4.4
chipped: Chipped 2.1.4
citresewn: CIT Resewn 1.1.2+1.19.2
cloth-config: Cloth Config v8 8.2.88
collective: Collective 6.53
comforts: Comforts 6.0.4+1.19.2
continuity: Continuity 2.0.1+1.19
corgilib: CorgiLib 1.0.0.34
create: Create 0.5.1-b-build.1079+mc1.19.2
create_enchantment_industry: Create Enchantment Industry 1.0.1
createdeco: Create Deco 1.3.3-1.19.2
cull-less-leaves: Cull Less Leaves 1.0.6
darkkore: DarkKore 0.3.0-1.19
debugify: Debugify 2.8.0
decorative_blocks: Decorative Blocks 3.0.0
dramaticdoors: Dramatic Doors (Fabric) 1.19.2-2.0.1
dynamicfps: Dynamic FPS 2.2.0
easyanvils: Easy Anvils 4.0.11
elytraslot: Elytra Slot 6.1.0+1.19.2
emi: EMI 0.7.3+1.19.2
enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
entity_texture_features: Entity Texture Features 4.3.0
entityculling: EntityCulling-Fabric 1.5.2-mc1.19
fabric-api: Fabric API 0.76.0+1.19.2
fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
fabricloader: Fabric Loader 0.14.22
fabricskyboxes: FabricSkyBoxes 0.6.1+mc1.19.2
farmersdelight: Farmer's Delight 1.19.2-1.3.10.1
farsight: Farsight Mod 1.19-2.4
ferritecore: FerriteCore 5.0.3
freecam: Freecam 1.1.6
fsb-interop: FabricSkyBoxes Interop 1.1.3+mc1.19.2-build.25
fscript: FScript Lib 3.2.0+1.19.2
fwaystones: Fabric Waystones 3.0.7+mc1.19.2
geckolib3: Geckolib 3.1.40
gravestones: Gravestones v1.13
guiclock: GUI Clock 4.2
handcrafted: Handcrafted 2.0.6
horsestatsvanilla: Horse Stats Vanilla 4.2.2
immersive_paintings: Immersive Paintings 0.6.0+1.19.2
indium: Indium 1.0.9+mc1.19.2
inventoryhud: Inventory HUD + 3.4.7
inventorysorter: Inventory Sorter 1.8.10-1.19
iris: Iris 1.6.6
irisflw: Iris Flywheel Compat 0.2.1
isxander-main-menu-credits: Main Menu Credits 1.1.1
itemmodelfix: Item Model Fix 1.0.3+1.19
jade: Jade 8.7.3
jadeaddons: Jade Addons 3.2.0
java: OpenJDK 64-Bit Server VM 17
kronhud: KronHUD 1.19.2-2.2.3
lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
languagereload: Language Reload 1.4.1
lazydfu: LazyDFU 0.1.3
linearxp: Linear XP 1.0.1
litematica: Litematica 0.12.7
lithium: Lithium 0.10.4
malilib: MaLiLib 0.13.0
mambience: MAmbience 5.2.0+1.19
minecraft: Minecraft 1.19.2
minihud: MiniHUD 0.23.3
mixin-conflict-helper: Mixin Conflict Helper 1.2.0
mixintrace: MixinTrace 1.1.1+1.17
modmenu: Mod Menu 4.1.2
more_slabs_stairs_and_walls: More Slabs, Stairs, and Walls 2.4.0+1.19.2
morechathistory: MoreChatHistory 1.1.1
mousetweaks: Mouse Tweaks 2.22
nochatreports: No Chat Reports 1.19.2-v1.13.12
noclip: noclip 1.1.5+1.19.2-fabric
nocreativedrift: NoCreativeDrift 1.19-4.0.4.0-fabric
nofade: No Fade 1.18-2.0.1
optigui: OptiGUI 1.1.6
owo: oωo 0.8.2+1.19
pack_it_up: Pack It Up! 0.3.0+1.19
pfm: Paladin's Furniture 1.1.1
polymorph: Polymorph 0.46.1+1.19.2
puzzle: Puzzle 1.4.0-1.19
puzzleslib: Puzzles Lib 4.4.0
railways: Create: Steam 'n' Rails 1.5.0+fabric-mc1.19.2-build.14
raisedclouds: Raised Clouds 1.2.0
reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
resourcefullib: Resourceful Lib 1.1.24
sliceanddice: Create Slice & Dice 2.3.1
smoothboot: Smooth Boot 1.19-1.7.1
sodium: Sodium 0.4.4+build.18
sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
starlight: Starlight 1.1.1+fabric.ae22326
survivalflight: Survival Flight 1.2.4
terrablender: TerraBlender 2.0.1.166
treeharvester: Tree Harvester 8.0
trinkets: Trinkets 3.4.2
veinmining: Vein Mining 1.1.1+1.19.2
worldedit: WorldEdit 7.2.12+6240-87f4ae1
worldeditcui: WorldEditCUI 1.19.2+01
xaerominimap: Xaero's Minimap 23.4.4
xaeroworldmap: Xaero's World Map 1.30.3
yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
yosbr: YOSBR 0.1.1
zoomify: Zoomify 2.9.0

**Comment by Gayowulf** [comment]
Just tested in a fresh instance where the only mods are Fabric API, Create, and Create: Steam 'n' Rails. Same behavior; it crashes immediately when trying to place a bogey on wide tracks.

[crash-2023-09-21_22.55.59-client.txt](https://github.com/Layers-of-Railways/Railway/files/12696285/crash-2023-09-21_22.55.59-client.txt)

**Comment by IThundxr** [comment]
Update create to 0.5.1c

**Comment by Gayowulf** [comment]
Tested with Create 0.5.1-c and it works. Closing this issue.
