### ISSUE TITLE
1.20.1 java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by CubeTwo** [Layers-of-Railways/Railway#271]
### Describe the Bug

game dont start get java.lang.reflect.InvocationTargetException: null  eror
forge 47.1.47
create-1.20.1-0.5.1.e
Steam_Rails-1.5.1+forge-mc1.20.1

### Reproduction Steps

1.
2.
3.
...

### Expected Result

run a game

### Screenshots and Videos

![2023-09-22_12 18 53](https://github.com/Layers-of-Railways/Railway/assets/16674396/46d66399-f828-4a8a-a940-967342e98fa8)

### Crash Report or Log

https://pastebin.com/K6eQDkJw

### Operating System

linux

### Mod Version

1.5.1

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

forge 47.1.47

**Comment by IThundxr** [comment]
use 0.5.1c/d for now e isnt compatible yet
