### ISSUE TITLE
Not compatible with most recent version of Create

### ISSUE THREAD

**Issue by AlisonHuang777** [Layers-of-Railways/Railway#272]
### Describe the Bug

The game failed to initialize itself when I updated the Create mod to version 0.5.1e.

### Reproduction Steps

1. Start the game with Create 0.5.1e and S&R 1.5.1/Extended Cogwheels 2.1.0 installed.
2. Game crashes.

### Expected Result

I expected it to not crash.

### Screenshots and Videos

![screenshot](https://github.com/Layers-of-Railways/Railway/assets/51637996/9ac15ce9-4251-4fe5-b573-75ef3d851e92)

### Crash Report or Log

https://gist.github.com/AlisonHuang777/200c8ad6232670fd04c23c31481c25f9

### Operating System

Windows 11

### Mod Version

1.5.1

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

### Other Mods

![mod list](https://github.com/Layers-of-Railways/Railway/assets/51637996/9cde5c10-ee76-4e80-b883-fdf36013a0e1)

### Additional Context

_Nothing_

**Comment by SpottyTheTurtle** [comment]
Does the issue occur with just Create and SnR?

**Comment by AlisonHuang777** [comment]
Yes. The crash report of that is appended to the original gist submitted in the issue.
(Not using minimal instance though, I only removed the extended cogwheels mod.)

**Comment by IThundxr** [comment]
I'll update it shortly after I'm back from school

**Comment by SquidBoiiiiii** [comment]
yeah im getting the same errors for mine too

**Comment by IThundxr** [comment]
This was fixed in 1.5.2
