### ISSUE TITLE
The mod "steam and Rails" fails to load

### ISSUE THREAD

**Issue by JustdaFra** [Layers-of-Railways/Railway#273]
### Describe the Bug

everything works without the mod. When I put it in, Minecraft says that the mod failed to load correctly.

### Reproduction Steps

1. I open the mod folder and put the mod
2. I open the launcher andstart opening Minecraft Java
3. It doesn't work
...

### Expected Result

I was expecting to play normally and create a new world with the mod, insted it blocks me because it didn't load the mod.

### Screenshots and Videos

![Screenshot 2023-09-23 165907](https://github.com/Layers-of-Railways/Railway/assets/145855315/ca14fe30-b971-40f8-ab18-678cfed3e571)

### Crash Report or Log

---- Minecraft Crash Report ---- // Hi. I'm Minecraft, and I'm a crashaholic.  Time: 2023-09-23 16:34:49 Description: Mod loading error has occurred  java.lang.Exception: Mod Loading has failed 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.0-universal.jar%23173!/:?] {re:classloading} 	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:146) ~[forge-1.20.1-47.1.0-universal.jar%23173!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:148) ~[forge-1.20.1-47.1.0-universal.jar%23173!/:?] {re:classloading} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.0.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.0.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at com.railwayteam.railways.forge.ModSetupImpl.useBaseTab(ModSetupImpl.java:8) ~[Steam_Rails-1.5.1+forge-mc1.20.1.jar%23166!/:?] {re:classloading} -- MOD railways -- Details: 	Caused by 0: java.lang.reflect.InvocationTargetException 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {} 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {} 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {} 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {} 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {} 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.0.jar%23170!/:?] {} 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.0.jar%23169!/:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}  	Mod File: /C:/Users/dlead/curseforge/minecraft/Instances/Vanilla alone/mods/Steam_Rails-1.5.1+forge-mc1.20.1.jar 	Failure message: Create: Steam 'n' Rails (railways) has failed to load correctly 		java.lang.reflect.InvocationTargetException: null 	Mod Version: 1.5.1+forge-mc1.20.1 	Mod Issue URL: https://github.com/Layers-of-Railways/Railway/issues 	Exception message: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)' Stacktrace: 	at com.railwayteam.railways.forge.ModSetupImpl.useBaseTab(ModSetupImpl.java:8) ~[Steam_Rails-1.5.1+forge-mc1.20.1.jar%23166!/:?] {re:classloading} 	at com.railwayteam.railways.ModSetup.useBaseTab(ModSetup.java) ~[Steam_Rails-1.5.1+forge-mc1.20.1.jar%23166!/:?] {re:classloading} 	at com.railwayteam.railways.ModSetup.register(ModSetup.java:21) ~[Steam_Rails-1.5.1+forge-mc1.20.1.jar%23166!/:?] {re:classloading} 	at com.railwayteam.railways.Railways.init(Railways.java:78) ~[Steam_Rails-1.5.1+forge-mc1.20.1.jar%23166!/:?] {re:classloading,re:mixin} 	at com.railwayteam.railways.forge.RailwaysImpl.<init>(RailwaysImpl.java:36) ~[Steam_Rails-1.5.1+forge-mc1.20.1.jar%23166!/:?] {re:classloading} 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {} 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {} 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {} 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.0.jar%23170!/:?] {} 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.0.jar%23169!/:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}   -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 11 (amd64) version 10.0 	Java Version: 17.0.8, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 186523248 bytes (177 MiB) / 799014912 bytes (762 MiB) up to 4294967296 bytes (4096 MiB) 	CPUs: 24 	Processor Vendor: GenuineIntel 	Processor Name: 13th Gen Intel(R) Core(TM) i7-13700KF 	Identifier: Intel64 Family 6 Model 183 Stepping 1 	Microarchitecture: unknown 	Frequency (GHz): 3.42 	Number of physical packages: 1 	Number of physical CPUs: 16 	Number of logical CPUs: 24 	Graphics card #0 name: NVIDIA GeForce RTX 3070 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x2488 	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667 	Memory slot #0 capacity (MB): 16384.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 16384.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 34629.31 	Virtual memory used (MB): 16472.59 	Swap memory total (MB): 2048.00 	Swap memory used (MB): 97.43 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m 	ModLauncher: 10.0.9+10.0.9+main.dcd20f30 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.5.jar eventbus PLUGINSERVICE  		fmlloader-1.20.1-47.1.0.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20.1-47.1.0.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20.1-47.1.0.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20.1-47.1.0.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20.1-47.1.0.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		javafml@null 		kotlinforforge@4.3.0 		lowcodefml@null 	Mod List:  		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		kffmod-4.3.0.jar                                  |Kotlin For Forge              |kotlinforforge                |4.3.0               |COMMON_SET|Manifest: NOSIGNATURE 		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |COMMON_SET|Manifest: NOSIGNATURE 		create-1.20.1-0.5.1.e.jar                         |Create                        |create                        |0.5.1.e             |COMMON_SET|Manifest: NOSIGNATURE 		mixinextras-forge-0.2.0-beta.6.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.6        |COMMON_SET|Manifest: NOSIGNATURE 		create_dragon_lib-1.20.1-1.3.3.jar                |Create: Dragon Lib            |create_dragon_lib             |1.3.3               |COMMON_SET|Manifest: NOSIGNATURE 		Steam_Rails-1.5.1+forge-mc1.20.1.jar              |Create: Steam 'n' Rails       |railways                      |1.5.1+forge-mc1.20.1|ERROR     |Manifest: NOSIGNATURE 		valkyrienskies-1201-2.3.0-beta.4.jar              |Valkyrien Skies 2             |valkyrienskies                |2.3.0-beta.4        |COMMON_SET|Manifest: NOSIGNATURE 		eureka-1201-1.3.0-beta.2.jar                      |VS Eureka Mod                 |vs_eureka                     |1.3.0-beta.2        |COMMON_SET|Manifest: NOSIGNATURE 		cloth-config-forge-11.0.99.jar                    |Cloth Config v10 API          |cloth_config                  |11.0.99             |COMMON_SET|Manifest: NOSIGNATURE 		forge-1.20.1-47.1.0-universal.jar                 |Forge                         |forge                         |47.1.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		create_enchantment_industry-1.20.1-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.2.6.d             |COMMON_SET|Manifest: NOSIGNATURE 	Flywheel Backend: GL33 Instanced Arrays 	Crash Report UUID: 653f40fe-d064-4fb9-8c94-c9b6f9860f4b 	FML: 47.1 	Forge: net.minecraftforge:47.1.0

### Operating System

Windows 11

### Mod Version

1.5.1

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

forge 1.20.1

### Other Mods

create, create enchantment industry, eureka, kotlinforforge, valkyrienskies

### Additional Context

I tried to start it on the normal launcher and on forge (on forge making a modpack).

**Comment by IThundxr** [comment]
use 0.5.1c for now
