### ISSUE TITLE
my server crashed 

### ISSUE THREAD

**Issue by jojofenin99** [Layers-of-Railways/Railway#275]
### Describe the Bug

my server crashed and it said that steams and rails is the cause here is the log 

### Reproduction Steps

1.got steam and rails
2. got new create upd
3. loaded server 
...

### Expected Result

I expected it to load as it did before

### Crash Report or Log

[https://mclo.gs/ETJUf1v](url)

### Operating System

windows 11

### Mod Version

1.5.1

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Forge

### Other Mods

im using the newest version of create

**Comment by IThundxr** [comment]
Downgrade to 0.5.1c or 0.5.1d
