### ISSUE TITLE
Using alt with train casing crash game

### ISSUE THREAD

**Issue by vinhor** [Layers-of-Railways/Railway#276]
### Describe the Bug

When  I'm holding train casing and press alt to choose type of bogey, my game immedietaly crash with exit code -1 and this message:
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "value" is null

### Reproduction Steps

1. Hold train casing
2. Press alt
3. Game **immediately** crash

### Expected Result

That Minecraft won't crash and I can choose form of bogey

### Crash Report or Log

https://mclo.gs/dTjIj1C

### Operating System

Windows 11

### Mod Version

1.5.1

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.14.22

### Other Mods

Balm 4.5.7
Cardinal Components API 5.0.2
Create 0.5.1-b-build.1089+mc1.19.2
Create Enchantment Industry 1.0.1
Create Deco 1.3.3-1.19.2
Decorative Blocks 3.0.0
EMI 1.0.19+1.19.2+fabric
Fabric API 0.76.1+1.19.2
Farmer's Delight 1.19.2-1.3.10
Forge Config API Port 4.2.11
Forgotten Graves 1.19.2-3.2.0
Geckolib 3.1.40
Indium 1.0.9+mc1.19.2
Lithium 0.11.1
Naturalist 3.0.4
Phosphor 0.8.1
Regions Unexplored 0.4.1+1.19.2
Replay Mod 1.19.2-2.6.13
Sodium 0.4.4+build.18
TerraBlender
Traveler's Backpack 1.19.2-8.2.26
Waystones 11.4.1
Xaero's Minimap 23.6.1

### Additional Context

Singleplayer

**Comment by SpottyTheTurtle** [comment]
In the #faq section of the discord there are replacement jars for farmer's delight that you'll need.

**Comment by IThundxr** [comment]
closing since this is a issue with farmers delight
