### ISSUE TITLE
[Question]: Versions compatible with 1.19.2

### ISSUE THREAD

**Issue by michelle1574** [Layers-of-Railways/Railway#280]
Please post here versions of Create and compatible versions of Steam'n'Rails that are compatible with 1.19.2

**Comment by SpottyTheTurtle** [comment]
Create 0.5.0 - SnR 1.2.6
Create 0.5.1a, 0.5.1b - SnR 1.3.x - 1.4.3
Ceate 0.5.1c, 0.5.1d - SnR 1.5.0
Create 0.5.1e - Unsupported Currently

**Comment by michelle1574** [comment]
What is version 1.5.1 then?

**Comment by SpottyTheTurtle** [comment]
sorry, I should've specified - Create 0.5.1c and 0.5.1d work with SnR 1.5.0 **and above**
