### ISSUE TITLE
Biomes O' Plenty Tracks Don't Drop Tracks

### ISSUE THREAD

**Issue by FluxyFox** [Layers-of-Railways/Railway#282]
### Describe the Bug

Biomes O' Plenty tracks don't drop tracks when mined or wrenched, unless it's a turn or slope.

### Reproduction Steps

1. Placed all normal tracks that could be placed.
2. Mined them with a diamond pick-axe in survival.
3. Noticed only the BOP tracks didn't have a drop.
...

### Expected Result

The tracks should just drop the track that was mined.

### Operating System

Windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

forge-1.20.1-47.1.46

**Comment by IThundxr** [comment]
Hmm the files for it exist from what I can see I'll have to try reproducing this

**Comment by BamsyTheSergal** [comment]
i am also having this issue, all biomes o plenty tracks do it. no errors or anything, they also cant be picked up with a wrench. only the straight tracks, curved ones drop them fine.

Mod Version
1.5.2

Create Mod Version
0.5.1e

ModLoader and Version
forge-1.20.1-47.2.1

**Comment by IThundxr** [comment]
Unable to reproduce with 1.5.1, 0.5.1e 1.19 forge

**Comment by BamsyTheSergal** [comment]
were having the issue in 1.20... lol

**Comment by BamsyTheSergal** [comment]
https://github.com/Layers-of-Railways/Railway/assets/12705993/717ea519-7ddf-46a1-ae95-d9a428d7d9cc

**Comment by IThundxr** [comment]
Alright was able to reproduce this on .20 gonna check it out a bit more later and try to see why it actually happens
