### ISSUE TITLE
1.19.2 render ui bug

### ISSUE THREAD

**Issue by netcore10** [Layers-of-Railways/Railway#284]
### Describe the Bug

holding alt on a train casing block crashes the game when the menu pops up.

### Reproduction Steps

1. place down train casing
2. hold alt on it
3. crash
...

### Expected Result

to not crash

### Crash Report or Log

https://paste.atlauncher.com/view/f40dd151-9847-432b-a0ed-3d2070d456b9

### Operating System

windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Latest fabric

### Other Mods

a lot, but it only happens when steam and rails is loaded, probably because it's trying to select a bogey type.

**Comment by IThundxr** [comment]
go to our discord and the #faq channel and get the fixes jars farmers delight is currently broken for fabric and the dev has no interest in fixing it even though the issue on their side
