### ISSUE TITLE
Bogey Types/Width Compatabilities

### ISSUE THREAD

**Issue by Feliixtc** [Layers-of-Railways/Railway#285]
### Describe the Suggestion

Can we get the mod custom bogeys in the mod custom rail widths? It took me ages to figure out how to choose the triple bogeys only to figure out I can't use them with the wide rails. Kinda makes me sad.

**Comment by IThundxr** [comment]
We are working on more bogey types however since they need to all be made manually and coded in manually it's gonna take a little bit
