### ISSUE TITLE
Cannot use the train coupler to recognize the train

### ISSUE THREAD

**Issue by HTony03** [Layers-of-Railways/Railway#288]
### Describe the Bug

It is a bug found when trying to make an auto-coupling center:
when a track is linked to two different train coupler, only one of them would recognize the train

### Reproduction Steps

1.make one track to be linked to two train coupler(any when it is linked before the coupler is putted down or adjust the distance to that point)
2.drive any train to that track and make the bogey right above the point
3.done
pic:
![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/b354852f-9d5d-4bb3-9859-1fab99998f80)
![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/23214493-de2a-4a0d-a4d6-a89ea25c2008)

### Expected Result

the two train coupler can both recognize the train.

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/7faa18f4-fd71-4295-a3c4-288fbecc9319)
![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/c2fef54b-98bf-4ae4-8f4a-35e672e39762)

### Operating System

Windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.3.0

### Other Mods

server:
world edit, kuayue(only used the track and the bogey , just another type of the create tracks and bogeys)

**Comment by IThundxr** [comment]
The coupler "plates" need to be under the bogey's and in your pictures only the left plate is while the right one isn't

**Comment by HTony03** [comment]
I know that btw ,the right train ,does not appear in the both coupler, and the plate is right below the right train's left bogey. 
another screenshot(we did not move the scene):
![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/800f6f68-5397-4598-9d77-c168db06e3b4)
(I firmly believe that because the right train is ALMOST not moved after it is materialized, we just moved it for a little by pressing ONCE w or s to move it , let the coupler to refresh and prepare for the next time's couple. Since it is just a test to prove my guess. And I believe that move would not over 0.15 blocks. 
Also you can see the train is recognized by the coupler in the second picture means the train's bogey is at the right position. Please ignore the Screenshots and Videos section since i uploaded the wrong pictures.)
(Is it because the train is just decoupled from the another train?)

**Comment by IThundxr** [comment]
Still seems like the plates aren't under the "bogies" ponder the coupler and it'll give you more info on alignment and try reproducing it like that

**Comment by HTony03** [comment]
I changed the track to the create's track since the kuayue's bogey have a little mistake
The server is not changed and I created another similar platform, another train, and you will see that
I drove the train backwards to make the test fair, then i drove the train to the station so that the bogey is RIGHT ABOVE the plate
![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/2cff0b60-b34d-485b-9103-e803fad0ec17)
![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/03ad4bc5-1c48-476f-8623-744a0da292f5)
and i saw the result of the two coupler:(the coupler is place before the train get to the station as you can see in the first picture that there are three pates in the picture)
![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/f4564291-279a-45b4-87cc-90a65cf886c3)
![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/4a389e9b-d65f-4cef-b817-ab188f8a000b)
and i wanna to give you a suggestion: you can test it yourself before you ask me again because the crowd would not tell you this will happen for no reason at all. 
and this is not the first time I met this problem. It is the second time. I tested it in the two different minecraft forge server and comes to the same conclusion.

**Comment by IThundxr** [comment]
You need just 1 coupler and it has to have 2 trains on it like shown in the coupler ponder, couplers are one of the features that are tested before releases and haven't been changed for a few updates and still work

Below is a picture of how to use them if you aren't able to check the ponder

![image](https://github.com/Layers-of-Railways/Railway/assets/74031881/0b55d337-b429-4f33-b861-6047a6cdbd30)

**Comment by HTony03** [comment]
I know what you mean, btw that's not what i mean.
because it needs us players to adjust the distance manually.
Our purpose is to create a totally automatic coupling system and the different kinds of locomotive does not have the same distance from the train top to the train bogey.
![image](https://github.com/Layers-of-Railways/Railway/assets/80151962/e154ef02-8234-4fd0-91af-9d673f99b865)
and we have one solution is that we make the distance longer so that it would not thread up. but that haves another problem is: the gap between the locomotive and the carriage is too big and it is not like real, also not beautiful.
so that we have the idea to build this kind of test and find this problem and raised this issue. 

and this problem is also exist when you need to decouple the carriage and let the locomotive to connect the other end.

after these words , me and my friends have a suggestion:
make the coupler do not be just a pair, but just binding to two tracks, change the plate model, judge the plates separate and that will solve the problem

**Comment by HTony03** [comment]
and this problem is also exist when you need to decouple the carriage and let the locomotive to connect the other end.
add a p.s. to this line:
this may not happen when you are playing single player

**Comment by IThundxr** [comment]
Alright theres no real proper fix for this but using signals inbetween will let multiple couplers work
