### ISSUE TITLE
Incompatibility with chunk loader mod 

### ISSUE THREAD

**Issue by beppisdoggo** [Layers-of-Railways/Railway#289]
### Describe the Bug

the version was 1.20.1 and the link is https://www.curseforge.com/minecraft/mc-mods/chunk-loaders
it says it is null

### Reproduction Steps

1.open up minecrap
2.says it  has an error
3. i close it
...

### Expected Result

for it to work

### Screenshots and Videos

![image_2023-10-03_134634077](https://github.com/Layers-of-Railways/Railway/assets/146873657/bd27b069-59dd-4f64-8d8c-5ef7cfeedeb0)

### Operating System

window11

### Mod Version

1.5.2

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

forge 1.20.1

### Other Mods

create

### Additional Context

it runs withou steam n rails

**Comment by IThundxr** [comment]
Can't help you without a crash log

**Comment by RedstoneGyerek** [comment]
it worked for me with chunk loaders
but im on win 10

**Comment by IThundxr** [comment]
Closing due to no crash log, if you post the crash log feel free to reopen this
