### ISSUE TITLE
[1.18] Create: Deco vertical slabs client crash

### ISSUE THREAD

**Issue by muriplz** [Layers-of-Railways/Railway#29]
When someone places a vertical slab on a track the client will never be able to join again if the track is loaded

https://pastebin.com/p3B8EJHe

**Comment by techno-sam** [comment]
Fixed in 1.0.4

**Comment by muriplz** [comment]
Will 1.0.4 have 1.18 version? or it moved on? I'll make a fork of 1.18 if so
