### ISSUE TITLE
Crash when used with Supplementaries and place down a book

### ISSUE THREAD

**Issue by littlepianist** [Layers-of-Railways/Railway#290]
### Describe the Bug

When placed down a book or enchanted book the client crashes while the server doesn't

### Reproduction Steps

1.Place down a book or enchanted book (behavior added by supplemantaries)
2.Client crashes
3.
...

### Expected Result

To not crash

### Crash Report or Log

https://pastebin.com/R1kgnjax  https://pastebin.com/v0CSUTvB

### Operating System

Windows11

### Mod Version

1.5.2

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.1

### Other Mods

Other mods don't affect the crash, I have tried to remove the mods one by one and in the end, only supplementaries, moonlight lib, jei, create, and this mod is left.

**Comment by IThundxr** [comment]
Yep seems like it's a fault on our end however I can't fully be sure until it see where this is occurring, I'll implement a fix in a bit

**Comment by IThundxr** [comment]
This like discussed in the sup discord is a issue on their side and the fix will be implemented by them so I'll be closing this
