### ISSUE TITLE
Failed to load correctly on server side

### ISSUE THREAD

**Issue by KelvinZhang512** [Layers-of-Railways/Railway#293]
### Describe the Bug

The mod failed to load correctly on my server.

### Reproduction Steps

1. Add the mod into the mods folder of the server
2. Start the server
3. Saw the crash report and the server was unable to start

### Expected Result

Server starts successfully

### Crash Report or Log

https://mclo.gs/TpRvWcC
https://mclo.gs/Fcj5QS1

### Operating System

Ubuntu Server 22.04 LTS

### Mod Version

1.5.2

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

NeoForge 47.1.79

### Other Mods

       Mod List: 
               Homeostatic-1.20.1-2.9.5.0.jar                    |Homeostatic                   |homeostatic                   |1.20.1-2.9.5.0      |COMMON_SET|Manifest: da:bf:8b:25:96:f3:b9:28:12:15:50:54:25:99:97:10:61:cf:4e:63:30:09:40:fb:93:39:1d:7e:6b:93:9b:17
               adaptive_performance_tweaks_core_1.20.1-9.1.0.jar |APTweaks: Core                |adaptive_performance_tweaks_co|9.1.0               |COMMON_SET|Manifest: NOSIGNATURE
               createbigcannons-forge-1.20.1-0.5.2.a-nightly-5b82|Create Big Cannons            |createbigcannons              |0.5.2.a-nightly-5b82|COMMON_SET|Manifest: NOSIGNATURE
               adaptive_performance_tweaks_spawn_1.20.1-9.1.0.jar|APTweaks: Spawn               |adaptive_performance_tweaks_sp|9.1.0               |COMMON_SET|Manifest: NOSIGNATURE
               kuayue-0.3.5m-izayoi_sakuya-rc2.jar               |KuaYue                        |kuayue                        |0.3.5m-izayoi_sakuya|COMMON_SET|Manifest: NOSIGNATURE
               botarium-forge-1.20.1-2.2.0.jar                   |Botarium                      |botarium                      |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
               yesstevemodel-1.20-release-1.1.5-hotfix-2.jar     |Yes Steve Model               |yes_steve_model               |1.1.5-hotfix-2      |COMMON_SET|Manifest: NOSIGNATURE
               multimine-1.20.1.2.jar                            |Multi Mine                    |multimine                     |1.20.1.2            |COMMON_SET|Manifest: NOSIGNATURE
               immersive_aircraft-0.6.2+1.20.1-forge.jar         |Immersive Aircraft            |immersive_aircraft            |0.6.2+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
               waystones-forge-1.20-14.0.2.jar                   |Waystones                     |waystones                     |14.0.2              |COMMON_SET|Manifest: NOSIGNATURE
               XaerosWorldMap_1.34.1_Forge_1.20.jar              |Xaero's World Map             |xaeroworldmap                 |1.34.1              |COMMON_SET|Manifest: NOSIGNATURE
               modernfix-forge-5.7.2+mc1.20.1.jar                |ModernFix                     |modernfix                     |5.7.2+mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
               jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |COMMON_SET|Manifest: NOSIGNATURE
               citadel-2.4.5-1.20.1.jar                          |Citadel                       |citadel                       |2.4.5               |COMMON_SET|Manifest: NOSIGNATURE
               SereneSeasons-1.20.1-9.0.0.46.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.46            |COMMON_SET|Manifest: NOSIGNATURE
               mixinextras-forge-0.2.0-beta.9.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.9        |COMMON_SET|Manifest: NOSIGNATURE
               adaptive_performance_tweaks_gamerules_1.20.1-9.1.0|APTweaks: Gamerules           |adaptive_performance_tweaks_ga|9.1.0               |COMMON_SET|Manifest: NOSIGNATURE
               catacalysm+delight+1.20.1+-+0.1.1.jar             |cataclysm delight             |cataclysm_delight             |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
               starlight-1.1.2+forge.1cda73c.jar                 |Starlight                     |starlight                     |1.1.2+forge.1cda73c |COMMON_SET|Manifest: NOSIGNATURE
               simpleplanes-1.20.1-5.2.4.jar                     |Simple Planes                 |simpleplanes                  |1.20.1-5.2.4        |COMMON_SET|Manifest: NOSIGNATURE
               Steam_Rails-1.5.2+forge-mc1.20.1.jar              |Create: Steam 'n' Rails       |railways                      |1.5.2+forge-mc1.20.1|ERROR     |Manifest: NOSIGNATURE
               create-new-age-forge-1.20.1-1.0.1.jar             |Create: New Age               |create_new_age                |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
               balm-forge-1.20.1-7.1.4.jar                       |Balm                          |balm                          |7.1.4               |COMMON_SET|Manifest: NOSIGNATURE
               carryon-forge-1.20.1-2.1.0.1.jar                  |Carry On                      |carryon                       |2.1.0.1             |COMMON_SET|Manifest: NOSIGNATURE
               cloth-config-12.0.109-forge.jar                   |Cloth Config v12 API          |cloth_config                  |12.0.109            |COMMON_SET|Manifest: NOSIGNATURE
               forge-1.20.1-47.1.79-universal.jar                |NeoForge                      |forge                         |47.1.79             |COMMON_SET|Manifest: 5c:77:18:4b:07:f2:c9:01:60:c8:5d:d0:92:b4:aa:c0:ac:6d:8f:b0:a9:fa:62:5e:2e:0a:b9:6f:1c:d6:b4:05
               adaptive_performance_tweaks_player_1.20.1-9.1.0.ja|APTweaks: Player              |adaptive_performance_tweaks_pl|9.1.0               |COMMON_SET|Manifest: NOSIGNATURE
               supplementaries-1.20-2.6.9.jar                    |Supplementaries               |supplementaries               |1.20-2.6.9          |COMMON_SET|Manifest: NOSIGNATURE
               server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
               xaeros_waystones_compability-1.0.jar              |Xaero's Map - Waystones Compab|w2w2                          |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
               FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |COMMON_SET|Manifest: NOSIGNATURE
               ends_delight-1.20.1-1.0.1.jar                     |End's Delight                 |ends_delight                  |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
               repurposed_structures-7.1.6+1.20.1-forge.jar      |Repurposed Structures         |repurposed_structures         |7.1.6+1.20.1-forge  |COMMON_SET|Manifest: NOSIGNATURE
               TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |COMMON_SET|Manifest: NOSIGNATURE
               moonlight-1.20-2.8.45-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.8.45         |COMMON_SET|Manifest: NOSIGNATURE
               RegionsUnexploredForge-0.5.3+1.20.1.jar           |Regions Unexplored            |regions_unexplored            |0.5.3               |COMMON_SET|Manifest: NOSIGNATURE
               NoChatReports-FORGE-1.20.1-v2.2.2.jar             |No Chat Reports               |nochatreports                 |1.20.1-v2.2.2       |COMMON_SET|Manifest: NOSIGNATURE
               Jade-1.20.1-forge-11.6.1.jar                      |Jade                          |jade                          |11.6.1              |COMMON_SET|Manifest: NOSIGNATURE
               sereneseasonfix-1.20.1-1.0.8.jar                  |Sereneseasonfix               |sereneseasonfix               |1.20.1-1.0.8        |COMMON_SET|Manifest: NOSIGNATURE
               nethersdelight-1.20.1-4.0.jar                     |Nether's Delight              |nethersdelight                |1.20.1-4.0          |COMMON_SET|Manifest: NOSIGNATURE
               servercore-forge-1.3.7+1.20.1.jar                 |ServerCore                    |servercore                    |1.3.7+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
               car-1.20.1-1.0.8.jar                              |Ultimate Car Mod              |car                           |1.20.1-1.0.8        |COMMON_SET|Manifest: NOSIGNATURE
               plane-1.20.1-1.0.6.jar                            |Ultimate Plane Mod            |plane                         |1.20.1-1.0.6        |COMMON_SET|Manifest: NOSIGNATURE
               kffmod-4.5.0.jar                                  |Kotlin For Forge              |kotlinforforge                |4.5.0               |COMMON_SET|Manifest: NOSIGNATURE
               touhoulittlemaid-1.20.1-release-1.1.1.jar         |Touhou Little Maid            |touhou_little_maid            |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
               L_Enders_Cataclysm-1.38+-1.20.1.jar               |Cataclysm Mod                 |cataclysm                     |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
               flywheel-forge-1.20-0.6.9-4.jar                   |Flywheel                      |flywheel                      |0.6.9-4             |COMMON_SET|Manifest: NOSIGNATURE
               create-1.20.1-0.5.1.d.jar                         |Create                        |create                        |0.5.1.d             |COMMON_SET|Manifest: NOSIGNATURE
               Patchouli-1.20.1-81-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-81-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
               Xaeros_Minimap_23.8.2_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.8.2              |COMMON_SET|Manifest: NOSIGNATURE
               create-stuff-additions1.20.1_v2.0.4a.jar          |Create Stuff & Additions      |create_sa                     |2.0.4.              |COMMON_SET|Manifest: NOSIGNATURE
               hardcorerevival-forge-1.20-12.0.0.jar             |Hardcore Revival              |hardcorerevival               |12.0.0              |COMMON_SET|Manifest: NOSIGNATURE
               canary-mc1.20.1-0.2.7.jar                         |Canary                        |canary                        |0.2.7               |COMMON_SET|Manifest: NOSIGNATURE
               worldedit-mod-7.2.15.jar                          |WorldEdit                     |worldedit                     |7.2.15+6463-5ca4dff |COMMON_SET|Manifest: NOSIGNATURE
               architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |COMMON_SET|Manifest: NOSIGNATURE
               ferritecore-6.0.0-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.0               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
               JadeAddons-1.20.1-forge-5.2.0.jar                 |Jade Addons                   |jadeaddons                    |5.2.0               |COMMON_SET|Manifest: NOSIGNATURE
               FallingTree-1.20.1-4.3.0.jar                      |FallingTree                   |fallingtree                   |4.3.0               |COMMON_SET|Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
               KryptonReforged-0.2.3.jar                         |Krypton Reforged              |krypton                       |0.2.3               |COMMON_SET|Manifest: NOSIGNATURE
               adaptive_performance_tweaks_items_1.20.1-9.1.0.jar|APTweaks: Items               |adaptive_performance_tweaks_it|9.1.0               |COMMON_SET|Manifest: NOSIGNATURE
               ywzj_midi-1.20.1-forge-1.3.0-all.jar              |Limitless Concert             |ywzj_midi                     |1.20.1-forge-1.3.0  |COMMON_SET|Manifest: NOSIGNATURE
               createaddition-1.20.1-1.1.0.jar                   |Create Crafts & Additions     |createaddition                |1.20.1-1.1.0        |COMMON_SET|Manifest: NOSIGNATURE

**Comment by IThundxr** [comment]
Either 
a) upgrade create to 0.5.1e
b) downgrade steam n rails to 1.5.1
