### ISSUE TITLE
sequenced recipes not showing. needs wiki

### ISSUE THREAD

**Issue by SirBastol** [Layers-of-Railways/Railway#294]
### Describe the Suggestion

wiki with alter sequenced recipes. needs creating. 
some modpacks seem to not show all the sequenced recipes 
and or its a bug in .51d create. ?

regardless there son amount of google that I can find the recipes for making the different sized tracks 
or conductor caps . 
and  its very infuriating beach people on discord. troll too much 

see examples below. 
 ( can just add it to GitHub   start page too . would be nice ( any dyed ones. just put a generic dye slot  and show the root item .. like the basic conductor cap and then a dy slot I think is how it works.. 
 
 I see a lot in creative mode but no recipes unless in crafting tables 
 
 USED. REI. MEI. JEI all separately with no other mods. and still no sequenced recipes show for create or. steam and rails
 and latest release of forge... 
 
 please fix. and add wiki info 

### Screenshots and Videos

<img width="844" alt="Screenshot 2023-10-11 at 12 32 06 PM" src="https://github.com/Layers-of-Railways/Railway/assets/6295949/2cd90c00-7600-4d2b-8fc6-0f3799c15e71">
<img width="839" alt="Screenshot 2023-10-11 at 12 32 55 PM" src="https://github.com/Layers-of-Railways/Railway/assets/6295949/06cacc26-262c-4d42-915a-dc257c289ae7">

### Additional Context

PLEASE

**Comment by IThundxr** [comment]
1. Try EMI alongside JEI for the compat
2. Polartt made a video with our recipes and stuff already
3. No one on the team wants to have to maintain a wiki due to the amount of work needed for that

**Comment by SirBastol** [comment]
I have used. Emi. Jei and rei.   It doesn’t work on all of them or any


And like I said a couple of screenshots of recipes on your GitHub. Is more
than enough.  It doesn’t have to be a full blow wiki

As well.  With the in game not showing the mod becomes useless as the is no
way to make narrow or wide tracks

**Comment by SpottyTheTurtle** [comment]
1) The tracks are still craftable, you just can't see their recipes
2) You are aware there is more than just narrow and wide gauge tracks in the mod, right?

**Comment by SirBastol** [comment]
Right but I’m sure the manufacturing process is the same even though I
don’t know what they are and I can’t find them because there’s no
screenshots online anywhere when you guys release the patch and added those
features he didn’t post any screenshots on how to make them or any
information Unless you happen to get a mod that has everything working
flawlessly you have no idea Or put an endgame book that has the recipes in
it

**Comment by aronmal** [comment]
I still don't know how to make the monorails in survival mode. I have REI and its compatibility mod. Create recipes work, but the Rails addon recipes are missing.

**Comment by IThundxr** [comment]
> I still don't know how to make the monorails in survival mode. I have REI and its compatibility mod. Create recipes work, but the Rails addon recipes are missing.

EMI & REI aren't great, use EMI + JEI, also polartt has a video with our recipes if you need to see them
