### ISSUE TITLE
[Compatibility] Style Picker is broken when used with Farmer's Delight

### ISSUE THREAD

**Issue by xllifi** [Layers-of-Railways/Railway#295]
### Describe the Bug

Game crashes when trying to load bogey styles

### Reproduction Steps

1. Install Farmer's Delight
2. Set up track and station
3. Hold Alt while holding Train Casing
4. Hover over any style category

### Expected Result

Game continues to work

### Crash Report or Log

https://hst.sh/tikonekodu

### Operating System

Windows 11

### Mod Version

1.5.2

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 0.14.23

### Other Mods

https://hst.sh/anijalofal.txt

### Additional Context
Does not occur with create's toolbox

**Comment by IThundxr** [comment]
Farmers delight issue, already reported to the dev however they still haven't fixed it. There's builds in our discord of modified farmers delight jars that are fixed and don't crash either use those or remove farmers delight/report to dev in hopes they fix it
