### ISSUE TITLE
Crashing while using a train casing and pressing alt

### ISSUE THREAD

**Issue by Krinkov74u** [Layers-of-Railways/Railway#296]
### Describe the Bug

Holding Alt with a train casing while using the All of Fabric 6 Modpack crashes the game in 1.19.2. 

### Reproduction Steps

1. Play the All of Fabric 6 Modpack
2. Grab a train casing 
3. Press alt and move mouse slightly
4. Crash
...

### Expected Result

No crash after holding alt and moving mouse to different types of bogeys.

### Crash Report or Log

https://pastebin.com/eBP0pZk2

### Operating System

Windows 11

### Mod Version

1.5.1

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric Loader 14.22-1.19.2

### Other Mods

They can be seen on my crash report.

### Additional Context

This problem affects Steam 'n' Rails version 1.5.0 as well. Its probably a mod conflict Im just not sure which one. Oh and amazing work on this mod, looks like magic to me.

**Comment by IThundxr** [comment]
Farmers delight bug, check our discord server for patches jars
