### ISSUE TITLE
Conductor's Cap doesn't cover the Hat Layer

### ISSUE THREAD

**Issue by DEAFG0AT** [Layers-of-Railways/Railway#297]
### Describe the Bug

In version 1.4.3 for Minecraft 1.19.2, the Conductor's Cap does not cover the hat layer on a player's skin, resulting in this goof.

![2023-10-14_11 38 49](https://github.com/Layers-of-Railways/Railway/assets/104733108/d9af6a80-7c44-4b30-93e1-6d60a3189f90)

Tested on all hats, same result. Please fix!

### Reproduction Steps

1. Put on the Conductor's Hat
2. Observe the goof
3. ???
4. Profit

### Expected Result

The hat would be rendered ON TOP of the player's skin, hiding anything on the hat layer that it ends up covering.

### Screenshots and Videos
It appears to render properly on the sides of the head, but not the front.

![2023-10-14_11 44 45](https://github.com/Layers-of-Railways/Railway/assets/104733108/a47df555-0fd9-4297-a97b-bc6b82740d85)

### Operating System

Windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.14.21

**Comment by techno-sam** [comment]
Will be fixed in 1.6.0
![2023-12-28_12 38 32](https://github.com/Layers-of-Railways/Railway/assets/77073745/3da3640e-8af7-4b73-b1b1-45fd0ebe4482)

Conductor = budget freecam
