### ISSUE TITLE
Gauntleted tracks

### ISSUE THREAD

**Issue by Bow-Tied-Engineer** [Layers-of-Railways/Railway#299]
### Describe the Suggestion

I'd love to see muti gauge tracks. I really love being able to couple and uncouple cars to do shunting things, but it would be really cool if I could, say, have a broad gauge train that runs long distances and drops off cars in a yard, but then I could shunt the cars into the unloading platform using a narrow gauge industrial shunter. I don't think it would be too hard to implement, as trains can already run on tracks of the wrong gauge, you'd just need to model tracks with more rails on them. I'd suggest for the crafting recipes, for standard and narrow, deploy a nugget onto a standard gauge track and press it, for broad and standard deploy a nugget onto a broad gauge track and press it, for broad and narrow deploy a nugget onto a broad gauge track, poke it with a deployer, and then press it, and for all three, take either broad and narrow or broad and standard, deploy a nugget, and then press it.
And, if anyone would want such a thing, I suppose you could also do versions of all of the above where you also deploy a monorail track and press it, for if you want to have a combined normal and monorail shunting yard. Though, that would be kinda weird, and the item clutter might not be worth it if nobody requests it. While gauntleted tracks are very much a thing, I don't think anyone has ever made a combined monorail and normal rail system.
For building trains, I'd suggest adding something in the station menu to select what gauge you are building, and use that to define what wheels can spawn in, because it would be really cool to have a triple gauge workshop where you can build your rolling stock.

**Comment by techno-sam** [comment]
This would significantly explode the number of track blocks we'd have to register (and model).
