### ISSUE TITLE
[Crash] Crash with Train Casing Interface

### ISSUE THREAD

**Issue by iglee42** [Layers-of-Railways/Railway#300]
### Describe the Bug

When I tried to open sub menu from the train casing interface, I crash

### Reproduction Steps

1. Get a train casing
2. Press Alt
3. Choose a sub menu

### Expected Result

Don't crash

### Crash Report or Log

https://pastebin.com/5v3L7j7F

### Operating System

Windows 11

### Mod Version

1.4.3

### Create Mod Version

0.5.1e

### Minecraft Version

1.18.2

### ModLoader and Version

Forge 40.2.9

### Other Mods

Modpack : Create Arcane Engineering

**Comment by iglee42** [comment]
Update : Create Version : 5.1c

**Comment by IThundxr** [comment]
update steam n rails to 1.5.1

**Comment by iglee42** [comment]
> update steam n rails to 1.5.1

There no 1.5.1 with 1.18.2

**Comment by IThundxr** [comment]
Ah then update to 1.4.4
