### ISSUE TITLE
incompatibility with valkyrienskies

### ISSUE THREAD

**Issue by Laem13** [Layers-of-Railways/Railway#301]
### Describe the Bug

Everything works without valkyrienskies or Steam_Rails. When I put it in, Minecraft says that the create mod failed to load correctly.

### Reproduction Steps

1. Download create (0.5.1.c, or 0.5.1e), kotlin, Steam_Rails, valkyrienskies.
2. Put it in folder "mods"
3. Opening launcher and launch minecraft.
...

### Expected Result

I was expecting to play  and create a new world with the mod. But insted it blocks me because it didn't load the mod.

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/149257555/ba8574ce-336f-42e6-a273-156e7988621c)

### Operating System

Windows 10

### Mod Version

1.4.4

### Create Mod Version

0.5.1e

### Minecraft Version

1.18.2

### ModLoader and Version

forge-40.2.10

### Other Mods

create, kotlin, Steam_Rails, valkyrienskies
![image](https://github.com/Layers-of-Railways/Railway/assets/149257555/58cfee33-657f-4a26-a65b-6b608c670910)

**Comment by IThundxr** [comment]
valkyrien skies isnt compatible with snr, they need to fix their mixin since it conflicts with snr please report this to them
