### ISSUE TITLE
Not working with create v0.5.1e

### ISSUE THREAD

**Issue by Rockiecraft** [Layers-of-Railways/Railway#304]
### Describe the Bug

Wont load with v0.5.1e. so just wonder when the mod will be updated

### Reproduction Steps

1.
2.
3.
...
just installing it i guess

### Expected Result

Does not work with v0.5.1e yet idk what else to say. besides when will we be able to expect a update to the mod?

### Operating System

Windows 10

### Mod Version

1.5.0

### Create Mod Version

0.5.1e

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 1.19.2 43.2.14

**Comment by IThundxr** [comment]
Use snr version 1.5.1, if that doesn't work send a log

**Comment by IThundxr** [comment]
Closing due to no log

**Comment by Rockiecraft** [comment]
it doesn't create any logs.  i get exit code 1

**Comment by IThundxr** [comment]
a crash will always make logs, exist codes dont help

**Comment by IThundxr** [comment]
if you cant find a crash log then send latest.log

**Comment by Rockiecraft** [comment]
[latest.log](https://github.com/Layers-of-Railways/Railway/files/13244151/latest.log)

**Comment by IThundxr** [comment]
hmm thats a incomplete log, try launching the game and sending a new one

**Comment by Rockiecraft** [comment]
its still the same. 1.4.3 works just fine with 5.1e but when i go to newer versions it crashes
[latest.log](https://github.com/Layers-of-Railways/Railway/files/13244161/latest.log)

**Comment by Rockiecraft** [comment]
1.5.X works just fine without any mods besides the create mod itself and the addons but when i put it in my modpack it crashes. any version above 1.4.3 will crash in my modpack and i want to have those narrow and wide tracks on my server.

**Comment by IThundxr** [comment]
> 1.5.X works just fine without any mods besides the create mod itself and the addons but when i put it in my modpack it crashes. any version above 1.4.3 will crash in my modpack and i want to have those narrow and wide tracks on my server. 

1.4.3 isn't compatible with 0.5.1b+, use 1.4.4 if your under patch f & 1.4.5 if your using patch f
