### ISSUE TITLE
Conductors can't navigate directly to the station.

### ISSUE THREAD

**Issue by Akiakoss** [Layers-of-Railways/Railway#305]
### Describe the Bug

It is very annoying that conductors can't navigate directly to the station when you use the "Conductor Whistle".

It makes an error like when you want to place a train station into a train station: "Targeted track is occupied" (pic. 1)

### Reproduction Steps

1. Make a train with a conductor in the seat.
2. Bound a Whistle.
3. Summon the Conductor on a train station.

### Expected Result

It would be great if you could summon it directly to the stations so you can disasseble it quickly without moving the train manually.

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/141921963/3cbe4bb5-42d6-4b26-ae46-473e39d6a569)

### Operating System

Windows 11

### Mod Version

1.5.1

### Create Mod Version

0.5.1e

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.3.2

### Additional Context

I was doing it on an Aternos-server.

**Comment by SpottyTheTurtle** [comment]
Not a bug, just how the system was coded. In any case, I already wrote a change that makes it so you can click a station with a whistle to summon the train to said station, so you can either clone the repo and build the jar or wait for the next update.
