### ISSUE TITLE
Train is not created

### ISSUE THREAD

**Issue by MrHimera** [Layers-of-Railways/Railway#306]
### Describe the Bug

After updating Create to 0.5.1.f, when assembling a train, it simply disappears from the tracks. And if there was already an assembled train in the world before, the game crashes.

### Reproduction Steps

1. Place the rails
2. We place a railway station
3. Click to assemble the train
4. Assembling a train from blocks and gluing it together
5. Click to assemble the train again
...

### Expected Result

Fix this bug

### Crash Report or Log

https://pastebin.com/teNMhYXt

### Operating System

Windows 10

### Mod Version

1.5.2

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.1

**Comment by IThundxr** [comment]
Update to 1.5.3

**Comment by MrHimera** [comment]
ok, tnx
