### ISSUE TITLE
Game crashes when in alt screen for bogeys and hover/click on other bogeys

### ISSUE THREAD

**Issue by Rockiecraft** [Layers-of-Railways/Railway#307]
### Describe the Bug

When in the screen to choose different style bogeys when holding alt, hovering(sometimes)/clicking on different bogey types the game crashes.

### Reproduction Steps

1. hold alt when holding train casing
2. hover/click on bogey type

### Expected Result

game will crash upon clicking

### Screenshots and Videos

![Screenshot -04-09 00-11-032023](https://github.com/Layers-of-Railways/Railway/assets/55363145/6aeda95a-e377-41aa-959c-40e2363e3194)

### Crash Report or Log

https://mclo.gs/wbLSYPx

### Operating System

Windows 10

### Mod Version

1.4.3

### Create Mod Version

0.5.1e

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 1.19.2 43.3.2

### Other Mods

[Infernal Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Just Zoom [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/just-zoom-forge)
[Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Simple Shops (by wolforce)](https://www.curseforge.com/minecraft/mc-mods/simple-shops)
[Iam Music Player [Forge/Fabric] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/iammusicplayer)
[Super Mobestiary (by portakalcevheri)](https://www.curseforge.com/minecraft/mc-mods/super-mobestiary)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[AdoraBuild: Structures (by AdoraBuild)](https://www.curseforge.com/minecraft/mc-mods/adorabuild-structures)
[Respawning Shulkers (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/respawning-shulkers)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[Presence Footsteps [Forge] (by Paint_Ninja)](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Name Tag Tweaks (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/name-tag-tweaks)
[BetterRandomSourceConcurrencyCrash (by XFactHD)](https://www.curseforge.com/minecraft/mc-mods/betterrandomsourceconcurrencycrash)
[End's Phantasm (by Lyof429)](https://www.curseforge.com/minecraft/mc-mods/phantasm)
[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Create: Crystal Clear (by singularity_cyvack)](https://www.curseforge.com/minecraft/mc-mods/create-crystal-clear)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Create Cafe (by Myst)](https://www.curseforge.com/minecraft/mc-mods/create-cafe)
[Better Animals Plus (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Observable (by tasgon)](https://www.curseforge.com/minecraft/mc-mods/observable)
[Even Better Amethyst [Forge] (by betathunder1)](https://www.curseforge.com/minecraft/mc-mods/even-better-amethyst)
[Accommodations (Japanese Additions) (by Klausster01)](https://www.curseforge.com/minecraft/mc-mods/accommodations-japanese-additions)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)
[FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Time Control (by Unixkitty)](https://www.curseforge.com/minecraft/mc-mods/time-control)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Reforgium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/reforgium)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Connectedness (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/connectedness)
[Torchmaster (by xalcon)](https://www.curseforge.com/minecraft/mc-mods/torchmaster)
[Japanese Romaji Converter (Forge/Fabric) (by Meatwo310)](https://www.curseforge.com/minecraft/mc-mods/japanese-romaji-converter)
[MemoryLeakFix (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Inventorio (Forge) (by Lizard_OfOz)](https://www.curseforge.com/minecraft/mc-mods/inventorio-forge)
[Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[No Enchant Cap (by AmyMialee)](https://www.curseforge.com/minecraft/mc-mods/no-enchant-cap)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Radon (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radon)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Emotecraft (Forge) (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/emotecraft-forge)
[Simple Backups (by MelanX)](https://www.curseforge.com/minecraft/mc-mods/simple-backups)
[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[Incendium (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/incendium)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Honey Sticky Piston (by MWR____)](https://www.curseforge.com/minecraft/mc-mods/honey-sticky-piston)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Hals Enhanced Biomes (by halbear_gamez)](https://www.curseforge.com/minecraft/mc-mods/hals-enhanced-biomes)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Panda's Falling Tree's (Forge/Fabric) (by ThePandaOliver)](https://www.curseforge.com/minecraft/mc-mods/pandas-falling-trees)
[Magnesium/Rubidium Extras (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[Fetzi's Asian Decoration (by NotFetzi)](https://www.curseforge.com/minecraft/mc-mods/fetzis-asian-decoration)
[Create : Misc & Things (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Deepslate Tweaks (Forge / Fabric) (by SYCO_3)](https://www.curseforge.com/minecraft/mc-mods/deepslate-tweaks)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Japanese Emoji Commands (by Paint_Ninja)](https://www.curseforge.com/minecraft/mc-mods/japanese-emoji-commands)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Handcrafted (by kekie6)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[ConnectedTexturesMod (by tterrag1098)](https://www.curseforge.com/minecraft/mc-mods/ctm)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Pick Up Notifier [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Biome Backport (Some 1.20 Features) (by Myst)](https://www.curseforge.com/minecraft/mc-mods/biome-backport)
[Bigger Stacks (by thanksihadtosignupforthis)](https://www.curseforge.com/minecraft/mc-mods/bigger-stacks)
[Golden Hopper (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/golden-hopper)
[Tree Harvester (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Tiered Shulker Boxes (by lukegrahamlandry)](https://www.curseforge.com/minecraft/mc-mods/tiered-shulkers)
[Rubidium Extra (by dimadencep)](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[[EMF] Entity Model Features [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-model-features)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Upgrade Aquatic (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
[Beastly Beacons (by Mindthemoods)](https://www.curseforge.com/minecraft/mc-mods/beastly-beacons)
[Effective (Forge) (by BottomTextDanny)](https://www.curseforge.com/minecraft/mc-mods/effective-forge)
[CullLessLeaves Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/culllessleaves-reforged)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Duckling (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/duckling)
[Lightspeed - Launch optimizations (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/lightspeedmod)
[Plenty of Golems (by alborto06)](https://www.curseforge.com/minecraft/mc-mods/plenty-of-golems)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Easy Shulker Boxes [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-shulker-boxes)
[Otyacraft Engine [Forge/Fabric] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/otyacraft-engine)
[Dave's Building Extended (by Medic_Main_Dave)](https://www.curseforge.com/minecraft/mc-mods/daves-building-extended)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
[Create: Factory (by antopfr90)](https://www.curseforge.com/minecraft/mc-mods/create-factory)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Natural Decoration (by praizazdd7724)](https://www.curseforge.com/minecraft/mc-mods/natural-decoration)
[Konkrete [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[TexTrue's Rubidium Options (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)

**Comment by IThundxr** [comment]
Use snr version 1.4.4
