### ISSUE TITLE
Add Swedish translations

### ISSUE THREAD

**Issue by Bjorkan** [Layers-of-Railways/Railway#310]
### Describe the Suggestion

Hello! I would like to add some Swedish translations to the mod and I read in the README.md that you recommend an issue being made before forking anything!

Thank you and I will glady respond to any questions you might have!

Yours,
Bjorkan

**Comment by IThundxr** [comment]
Yeah sure! https://crowdin.com/project/create-steam-n-rails-official/sv-SE we've got a crowdin page at which you can translate the mod

**Comment by Bjorkan** [comment]
> Yeah sure! https://crowdin.com/project/create-steam-n-rails-official/sv-SE we've got a crowdin page at which you can translate the mod

Oh perfect! I am very used to Crowdin so that is a pleasent suprise! Will get to it during this evening! 🎉❤️
