### ISSUE TITLE
Remote signal function breaks base create "copy nixie tube" function

### ISSUE THREAD

**Issue by tobi-blackscale** [Layers-of-Railways/Railway#311]
### Describe the Bug

Regular nixie tubes can no longer be copied with a display link with steam and rails present.
The target nixie will turn into a signal nixie instead.

### Reproduction Steps

1.Place two separate nixie tubes 
2. select one as a target for a display link
3. attach display link to other tube.
...

### Expected Result

Copy nixie tube should work normally.

### Screenshots and Videos

![grafik](https://github.com/Layers-of-Railways/Railway/assets/71216944/75e36523-7131-4b26-9e6d-cc6b7dfe29ae)
![grafik](https://github.com/Layers-of-Railways/Railway/assets/71216944/25fc50e5-36d8-45b1-92fe-64d8f60b2ec5)
![grafik](https://github.com/Layers-of-Railways/Railway/assets/71216944/0fefda51-44df-4fd9-bd11-4b505185d72d)

### Operating System

Windows 10

### Mod Version

1.5.2

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Does not matter. just like the mod versions.

### Other Mods

None.

### Additional Context

https://discord.com/channels/706277846389227612/1150243198015381574/1150243198015381574

**Comment by IThundxr** [comment]
Yeah seems to be a EB shader conflict, closing since it's not a steam n rails issue.

**Comment by techno-sam** [comment]
this will be fixed in 1.6.0
