### ISSUE TITLE
Extended Bogeys Patch Crash

### ISSUE THREAD

**Issue by EternalBlade55** [Layers-of-Railways/Railway#312]
### Describe the Bug

When using the bogey variants Triple Axle Bogey and Invisible Bogey on a train it causes a crash. When used not together, they don't cause a crash. Crash log can be found here: 
[crash-2023-11-07_12.29.17-client.txt](https://github.com/Layers-of-Railways/Railway/files/13275552/crash-2023-11-07_12.29.17-client.txt)

### Reproduction Steps

1. First grab a station
2. Click Create new Train
3. Place both Bogey variants down on the track, (ie Triple Axle Bogey and Invisible Bogey)
4. Then assemble train 
5. This will lead to a crash to occur.

### Expected Result

The idea is to have the two bogey variants to be able to attach and not lead to a crash. 

### Crash Report or Log

Description: Rendering entity in world  java.lang.NullPointerException: Cannot read the array length because "array" is null

### Operating System

Windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Curseforge and Modrinth

### Other Mods

Extended Bogey Patch from IThundxr

**Comment by EternalBlade55** [comment]
When using shaders the crash occurs, when not using shaders the crash doesn't occur when assembling a train.

**Comment by IThundxr** [comment]
Yeah looks like a EB & shaders conflict, closing since it's a EB issue.
