### ISSUE TITLE
Train dissapearing

### ISSUE THREAD

**Issue by CaesarMeow** [Layers-of-Railways/Railway#313]
### Describe the Bug

Once the train is completed and glued, when pressing [assemble] the train dissappears /gets deleted completely 
After deactivating and checking each mod in particular that i had loaded, only when Steam'n'Rails was deactivated the issue was solved. 
I would very much like to keep the mod as it brings a lot of useful items. Any idea what can be causing this or how to fix ? 

### Reproduction Steps

1. created train
2. clicked assemble
3. train got deleted
...

### Expected Result

Train to be assembled and ready to use

### Operating System

Windows 10

### Mod Version

1.5.2

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

### Other Mods

Create
Misc & Things
Create Interiors
MrCrayfish's Furniture Mod
_Create Steam 'n' Rails_ 

### Additional Context

After deactivating and checking each mod in particular that i had loaded, only when Steam'n'Rails was deactivated the issue was solved.

**Comment by SpottyTheTurtle** [comment]
update Steam 'n Rails
