### ISSUE TITLE
ConductorCap Crashing Client

### ISSUE THREAD

**Issue by AbaDAAM** [Layers-of-Railways/Railway#314]
### Describe the Bug

ConductorCap is crashing the client after trying to create a Conductor, or simply if someone near you has the ConductorCap in their inventory just keep everyone in the same chunk to crash with the same error. If someone dies while having the ConductorCap in inventory and using a Corps mod anyone will crash while loading in the chunk that the played died in.

### Reproduction Steps

1. player one has ConductorCap in their inventory.
2. Player Two enters the area where Player One is 
3. player two keeps crashing on login with the same error 
...
has

### Expected Result

no crash

### Crash Report or Log

https://pastebin.com/FyzS637x

### Operating System

windows 10

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 1.20.1

**Comment by IThundxr** [comment]
Does this occur with just snr & create?

**Comment by IThundxr** [comment]
Actually found out which mod does this, azurelib I'll have a chat with the dev and find a fix

**Comment by IThundxr** [comment]
Update AzureLib to 2.0.x or newer
