### ISSUE TITLE
MC crashes with Ponder or when blocks placed on the ground

### ISSUE THREAD

**Issue by ExtraBigJohnson** [Layers-of-Railways/Railway#315]
### Describe the Bug

Minecraft crashes with Ponder. Or when Steam and Rails blocks placed on the ground. Also when choosing bogeys with an alt key.

### Reproduction Steps

1. Place any Steam and Rails block on the ground 
2. Or select other bogey with an alt key
3.
4.
...

### Expected Result

Not crashing

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/150387735/4aee1638-7ba4-47af-93ec-d54f932f8f95)

### Crash Report or Log

https://mclo.gs/To0yPYD

### Operating System

Windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 0.14.24

### Other Mods

![image](https://github.com/Layers-of-Railways/Railway/assets/150387735/1b6921d8-ccd7-49ae-b690-a48ca3d12687)
![image](https://github.com/Layers-of-Railways/Railway/assets/150387735/3230d195-1206-4fba-af7e-45921a4c3c5a)

### Additional Context

I found a solution to use create 0.5.1b. But there's only 0.5.1d version for Fabric on CurseForge. idk maybe i am just stupid.

**Comment by IThundxr** [comment]
create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want

**Comment by ExtraBigJohnson** [comment]
Do i need iris? It stoped crashing when i place blocks on the ground. But it still crashes when i try to select bogeys with an alt.

https://mclo.gs/XMGej0r

TY for your patience.

**Comment by IThundxr** [comment]
iris isnt needed, and the crash is due to farmers delight, check our discord for modified jars of farmers delight fabric fixing the crash

**Comment by ExtraBigJohnson** [comment]
It worked. TYSM
