### ISSUE TITLE
Villagers can open "Special" doors

### ISSUE THREAD

**Issue by SFort** [Layers-of-Railways/Railway#317]
Villagers can open doors that should have the same behaviour as an iron door

https://github.com/Creators-of-Create/Create/assets/1879846/ed272631-5098-4721-9087-75fdb995120b

This also means villigers might open a door and leave it open.

I'm assuming it might also mean zombies can break it down? but i haven't tested that

**Comment by techno-sam** [comment]
this will be fixed in 1.6.0
