### ISSUE TITLE
Game crashing while changing bogey style through ALT button.

### ISSUE THREAD

**Issue by JedaiGames** [Layers-of-Railways/Railway#319]
### Describe the Bug

If I trying to place bogeys on tracks - all working fine.
If i trying to change style through RMB - all working fine.
But as soon as i tried change style of bogeys through ALT menu - game freezes and crash instantly.

### Reproduction Steps

1. Start game
2. Create new world
3. Take train casing in hand and press ALT.
4. Game dead

### Expected Result

Not crashing, changing bogey style

### Crash Report or Log

https://mclo.gs/Mzh4m29

### Operating System

Windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.14.24

### Other Mods

Create Fabric 0.5.1c
Farmers Delight 1.3.10.1
JEI 11.6.0
Fabric API 0.76.1

**Comment by IThundxr** [comment]
Farmers delight fabric bug, get a fixed jar from our discord since the dev doesn't have any interest in fixing a issue in their mod
