### ISSUE TITLE
1.18.2 Game not opening

### ISSUE THREAD

**Issue by Edua2007** [Layers-of-Railways/Railway#322]
### Describe the Bug

[latest.log](https://github.com/Layers-of-Railways/Railway/files/13326342/latest.log)
I'm using the 1.4.6 version of the mod

### Reproduction Steps

1.Open the game
2.Start loading
3. A mensage appear saying that create has failed to open
...

### Expected Result

1. Open the game
2. Start loading
3. Game open

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/34384205/530c624d-0617-41c2-bd63-9e1c6c145bda)

### Crash Report or Log

https://github.com/Layers-of-Railways/Railway/files/13326342/latest.log

### Operating System

Windows 10

### Mod Version

1.4.5

### Create Mod Version

0.5.1f

### Minecraft Version

1.18.2

### ModLoader and Version

Forge 1.18.2 40.2.9

### Other Mods

How do a make a mod list?

**Comment by IThundxr** [comment]
VS Incompat, its been fixed in 1.6.0 but for 1.18 youll need to ask them to fix it
