### ISSUE TITLE
[Forge 1.20.1] Unexpected Crash

### ISSUE THREAD

**Issue by Starexify** [Layers-of-Railways/Railway#325]
### Describe the Bug

It crashes, I cant understand the cause in the crash log

### Reproduction Steps

1. Mod combination with other mods 

### Expected Result

Crash

### Crash Report or Log

https://pastebin.com/8s81Ap26

### Operating System

Windows 10

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.1.44

### Other Mods

player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |COMMON_SET|Manifest: NOSIGNATURE
		Galosphere-1.20.1-1.3.2-Forge.jar                 |Galosphere                    |galosphere                    |1.20.1-1.3.2        |COMMON_SET|Manifest: NOSIGNATURE
		libraryferret-forge-1.20.1-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.5.100.457.jar          |Sophisticated Core            |sophisticatedcore             |0.5.100.457         |COMMON_SET|Manifest: NOSIGNATURE
		rubidium-0.6.5.jar                                |Rubidium                      |rubidium                      |0.6.5               |COMMON_SET|Manifest: NOSIGNATURE
		MedievalCraftStructures-1.20.1-1.0.0.jar          |Medieval craft_structures     |medieval_craft_structures     |2.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		Fallingleaves-1.20.1-2.1.0.jar                    |Falling Leaves                |fallingleaves                 |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.3.jar                  |Clumps                        |clumps                        |12.0.0.3            |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.12-forge.jar                |Journeymap                    |journeymap                    |5.9.12              |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.4.7-1.20.1.jar                          |Citadel                       |citadel                       |2.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.22.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.5              |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.6.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.6        |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.20.1-3.18.65.935.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |3.18.65.935         |COMMON_SET|Manifest: NOSIGNATURE
		AnimaticaReforged-1.20.1-0.0.2.jar                |AnimaticaReforged             |animatica                     |1.20.1-0.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		simpleplanes-1.20.1-5.2.4.jar                     |Simple Planes                 |simpleplanes                  |1.20.1-5.2.4        |COMMON_SET|Manifest: NOSIGNATURE
		Steam_Rails-1.5.3+forge-mc1.20.1.jar              |Create: Steam 'n' Rails       |railways                      |1.5.3+forge-mc1.20.1|ERROR     |Manifest: NOSIGNATURE
		FpsReducer2-forge-1.20-2.5.jar                    |FPS Reducer                   |fpsreducer                    |1.20-2.5            |COMMON_SET|Manifest: NOSIGNATURE
		ShieldExpansion-1.20.1-1.1.6.jar                  |Shield Expansion              |shieldexp                     |1.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |COMMON_SET|Manifest: NOSIGNATURE
		soundphysics-forge-1.20.1-1.1.1.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.1.44-universal.jar                |Forge                         |forge                         |47.1.44             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		supplementaries-1.20-2.5.26.jar                   |Supplementaries               |supplementaries               |1.20-2.5.26         |COMMON_SET|Manifest: NOSIGNATURE
		athena-forge-1.20.1-3.0.1.jar                     |Athena                        |athena                        |3.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		MedievalCraftWeapons-1.20.1-1.0.0.jar             |Medieval_craft_weapons        |medieval_craft_weapons        |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		corpse-1.20.1-1.0.5.jar                           |Corpse                        |corpse                        |1.20.1-1.0.5        |COMMON_SET|Manifest: NOSIGNATURE
		chipped-forge-1.20.1-3.0.1.jar                    |Chipped                       |chipped                       |3.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		useless-sword-1.20.1-V1.4.1.jar                   |Useless Sword                 |useless_sword                 |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		entity_model_features_forge_1.20-0.2.13.jar       |Entity Model Features         |entity_model_features         |0.2.13              |COMMON_SET|Manifest: NOSIGNATURE
		entity_texture_features_forge_1.20-4.4.5.jar      |Entity Texture Features       |entity_texture_features       |4.4.5               |COMMON_SET|Manifest: NOSIGNATURE
		handcrafted-forge-1.20.1-3.0.1.jar                |Handcrafted                   |handcrafted                   |3.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		alexscaves-1.0.6.jar                              |Alex's Caves                  |alexscaves                    |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		libIPN-forge-1.20-3.0.2.jar                       |libIPN                        |libipn                        |3.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.20-3.0.0.163.jar             |TerraBlender                  |terrablender                  |3.0.0.163           |COMMON_SET|Manifest: NOSIGNATURE
		Physics-Mod-Pro-Forge-1.20.1.jar                  |Physics Mod                   |physicsmod                    |3.0.8               |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.20-2.8.3-forge.jar                    |Moonlight Library             |moonlight                     |1.20-2.8.3          |COMMON_SET|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.21_mc1.20.1.jar          |AmbientSounds                 |ambientsounds                 |5.2.21              |COMMON_SET|Manifest: NOSIGNATURE
		bettercombat-forge-1.7.3+1.20.1.jar               |Better Combat                 |bettercombat                  |1.7.3+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		vtaw_mw-forge-1.20.1-1.0.4.jar                    |Variant Tools and Weaponry - E|vtaw_mw                       |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		firstperson-forge-2.2.4-mc1.20.1.jar              |FirstPersonModel Mod          |firstpersonmod                |2.2.4-mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.34_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.10.34             |COMMON_SET|Manifest: NOSIGNATURE
		RoughlyEnoughItems-12.0.645.jar                   |Roughly Enough Items (REI)    |roughlyenoughitems            |12.0.645            |COMMON_SET|Manifest: NOSIGNATURE
		TextruesRubidiumOptions-1.0.0+mc1.20.jar          |TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.0+mc1.20        |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-4.4.0.jar                                  |Kotlin For Forge              |kotlinforforge                |4.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-5.4.2+1.20.1.jar                     |Curios API                    |curios                        |5.4.2+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.20-0.6.9-4.jar                   |Flywheel                      |flywheel                      |0.6.9-4             |COMMON_SET|Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.d.jar                         |Create                        |create                        |0.5.1.d             |COMMON_SET|Manifest: NOSIGNATURE
		oculus-mc1.20-1.6.4.jar                           |Oculus                        |oculus                        |1.6.4               |COMMON_SET|Manifest: NOSIGNATURE
		sit-1.20-1.3.3.jar                                |Sit                           |sit                           |1.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		FramedBlocks-9.0.3.jar                            |FramedBlocks                  |framedblocks                  |9.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		entityculling-forge-1.6.2-mc1.20.jar              |EntityCulling                 |entityculling                 |1.6.2               |COMMON_SET|Manifest: NOSIGNATURE
		bettervillage-forge-1.20.1-3.2.0.jar              |Better village                |bettervillage                 |3.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		ThirstWasTaken-1.20.1-1.3.1.jar                   |Thirst Was Taken              |thirst                        |1.20.1-1.3.1        |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.9.jar             |Resourceful Lib               |resourcefullib                |2.1.9               |COMMON_SET|Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.20-1.10.6.jar       |Inventory Profiles Next       |inventoryprofilesnext         |1.10.6              |COMMON_SET|Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |COMMON_SET|Manifest: NOSIGNATURE
		simplyswords-forge-1.51.5-1.20.1.jar              |Simply Swords                 |simplyswords                  |1.51.5-1.20.1       |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-6.0.0-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.0               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		smallships-forge-1.20.1-2.0.0-a2.3.3.jar          |Small Ships                   |smallships                    |2.0.0-a2.3.3        |COMMON_SET|Manifest: NOSIGNATURE
		KryptonReforged-0.2.3.jar                         |Krypton Reforged              |krypton                       |0.2.3               |COMMON_SET|Manifest: NOSIGNATURE

**Comment by IThundxr** [comment]
Use create 0.5.1f or use steam n rails 1.5.1
