### ISSUE TITLE
Train getting deleted on assembly

### ISSUE THREAD

**Issue by C4799** [Layers-of-Railways/Railway#326]
### Describe the Bug

Every time I try to assemble a train in the station block the whole train gets deleted instead of being converted into an entity like it should.

### Reproduction Steps

1. Place down station marker on track
2. Build train
3. Assemble train in station
4. Train gets deleted

### Expected Result

Trains should get assembled into entities and not deleted by the station block.

### Screenshots and Videos

https://youtu.be/E3mDjWX5U3s

### Operating System

Windows 10

### Mod Version

1.5.3

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.1

### Other Mods

Modpack "All the forge 10"
Create Steam n Rails
Create Crafts and Additions

**Comment by SpottyTheTurtle** [comment]
Update Create and SnR to latest versions.
