### ISSUE TITLE
custom bogey selection screen crash

### ISSUE THREAD

**Issue by DonDuran** [Layers-of-Railways/Railway#327]
### Describe the Bug

when i open the custom bogey selection screen, the game crashes.
### Reproduction Steps

1.get a train casing
2.open the custom bogey selection screen
3.and it just crashes( for me at least
...

### Expected Result

i expected to be able to just choose witch bogey i can use, but it crashes the game

### Crash Report or Log

"Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "value" is null"

### Operating System

windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

fabric 0.14.22

### Other Mods

create deco, and all the mods in the modpack better MC for fabric

**Comment by IThundxr** [comment]
Farmers delight issue check the faq channel in our discord for fixed jars

**Comment by DonDuran** [comment]
where is the discord ?

**Comment by DonDuran** [comment]
thanks for helping btw

**Comment by IThundxr** [comment]
https://discord.gg/create-steam-n-rails-706277846389227612

**Comment by DonDuran** [comment]
thanks
