### ISSUE TITLE
The train stops 'randomly'

### ISSUE THREAD

**Issue by Moongosu** [Layers-of-Railways/Railway#328]
### Describe the Bug

In another world, I set out to create the train. However, at a certain point, it started stopping in the middle of the track, and the only way to get it running again was to get out of the seat. I changed the train tracks, and while it no longer stopped in that particular area, it started stopping in another randomly designated location (it always stops in this random place designated by the train). I created a new world, and the same thing happened, as seen in the video.

(I changed the train tracks after it stopped to mark the area)

### Reproduction Steps

1.Assemble the train.
2.Make it continue its route.
3.It stops in areas randomly designated by the train.
4.Get off to restart the train.

### Expected Result

i dont know what text here

### Screenshots and Videos

https://drive.google.com/drive/folders/1DxJde6zj-RfwIZZcHvgj69VfVX3qMSTR?usp=sharing

### Operating System

Windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.6

### Other Mods

[Mods error.txt](https://github.com/Layers-of-Railways/Railway/files/13385203/Mods.error.txt)

**Comment by IThundxr** [comment]
Not a Steam 'n' Rails issue, report to create instead.

**Comment by Moongosu** [comment]
> Not a Steam 'n' Rails issue, report to create instead.

thx
