### ISSUE TITLE
Train assembly impossible

### ISSUE THREAD

**Issue by DangReceiver** [Layers-of-Railways/Railway#332]
### Describe the Bug

After installing the mod, train assembly does no longer work
removing this mod resolves the issue

mod list:
![explorer_nOhVbH0ZEE](https://github.com/Creators-of-Create/Create/assets/103147110/1dda257e-7de6-4a3d-b0ff-59fbb12017ee)

### Reproduction Steps

1. Build your train as regular
2. click assemble
3.live through a dirty server crash
...

### Expected Result

A nice and easy to use train

The version used (I cannot choose it on here though) is 1.4.6

### Crash Report or Log

https://pastebin.com/njQWrqZy

### Operating System

Windows 11

### Mod Version

1.4.5

### Create Mod Version

0.5.1c

### Minecraft Version

1.18.2

### ModLoader and Version

Forge 1.18.2 - 40.2.10

### Other Mods

![explorer_nOhVbH0ZEE](https://github.com/Layers-of-Railways/Railway/assets/103147110/3ac2c778-d2ab-4f8b-8442-890b438879b2)

**Comment by IThundxr** [comment]
https://github.com/Layers-of-Railways/Railway/wiki Mismatched versions, get the right version for your create version
