### ISSUE TITLE
[invalid] diesel engines are wayy too loud

### ISSUE THREAD

**Issue by burdoto** [Layers-of-Railways/Railway#333]
*invalid issue report*

**Comment by Szedann** [comment]
I don't think this is an SNR issue

**Comment by burdoto** [comment]
@Szedann i think it is, since the diesel engine sound comes from it.
like please at least make the sound less obnoxious

**Comment by burdoto** [comment]
wait oh damn
wrong addon github. i'm sorry

**Comment by IThundxr** [comment]
Steam n rails isn't create diesel generators

**Comment by burdoto** [comment]
yes my bad i just realized i had it very wrong. my bad

**Comment by burdoto** [comment]
(this is invalid and should be deleted)
