### ISSUE TITLE
Can you update your mod for Create v0.5.1f?

### ISSUE THREAD

**Issue by korAPUcard** [Layers-of-Railways/Railway#334]
### Describe the Suggestion

Can you update your mod for Create v0.5.1f?
When I install this mod, game has crashed with `java.lang.reflect.InvocationTargetException: null` error. Please update your mod.

### Screenshots and Videos

![mc_create_crash1](https://github.com/Layers-of-Railways/Railway/assets/25803734/bfe981fb-c51a-4b3f-bd23-2a7a818251bb)

**Comment by Szedann** [comment]
it is updated to 0.5.1.f
https://github.com/Layers-of-Railways/Railway/wiki
