### ISSUE TITLE
Monorail has no blockarea color display like other rails

### ISSUE THREAD

**Issue by MoYuan-CN** [Layers-of-Railways/Railway#335]
### Describe the Suggestion

i built a air-railway with the monorails, but after i place the track signal block i found one signal is in the 'fail' status
i want to check where let this signal in a loopback but i can't see the blockarea color display even i hold a signal in my hand
this makes it more difficult for me to identify the location of the problem

~~oh my poor english :(~~

### Additional Context

ah, how about to add the blockarea color display at the top of the monorails same as other tracks

**Comment by IThundxr** [comment]
Todo for myself: make the signal line render higher for encased tracks & monorails

**Comment by MoYuan-CN** [comment]
ummm……
i think you should move marks more higher on monorails
![image](https://github.com/Layers-of-Railways/Railway/assets/109946426/4a3ad935-9cab-4794-b495-7bf9e7a4437e)
