### ISSUE TITLE
[Suggestion] Utilise Common Tags

### ISSUE THREAD

**Issue by xanthian** [Layers-of-Railways/Railway#338]
### Describe the Suggestion

Use c:workbench for the Minecart with Workbench

There are many mods that add reskinned crafting tables but they cant be used in your mod.

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/7688001/60fcf806-970b-4d10-8c8d-3a33d3abb2b7)
![image](https://github.com/Layers-of-Railways/Railway/assets/7688001/565d6c47-d826-4da9-adf6-ad5c89114b21)

**Comment by IThundxr** [comment]
Oh yeah I'll change that up for 1.6.0 & alongside that look into if I can make the crafting table take the texture of the one it was crafted with
