### ISSUE TITLE
Bogey selection menu crash.

### ISSUE THREAD

**Issue by Xiyn89** [Layers-of-Railways/Railway#340]
### Describe the Bug

When trying to select one of this mods bogeys via the ALT menu, the game crashes to desktop when Farmer's Delight is installed.

### Reproduction Steps

1. Lay section of track
2. Place Train Station and assemble new train
3. Hold ALT and move mouse over one of the Icons.
...

### Expected Result

The game will freeze for a moment and then shut down.

### Crash Report or Log

https://pastebin.com/snCdawmy

### Operating System

Windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.15

### Other Mods

Farmer's Delight 1.3.10

### Additional Context

I discovered this crash when playing Statech Industry modpack.  I tracked it down to some kind of issue with Farmer's Delight.  Removing it lets the ALT menu work, adding it causes the crash to resume.  I tested it on a fresh 1.19.2 install with just Create, Steam and Rails, and Farmer's delight to be sure.  I use the PolyMC launcher but it also happened with MultiMC.  I haven't been able to find any mention of this crash so I'm unsure what is actually at fault.

**Comment by IThundxr** [comment]
Farmers delight is at fault, dev doesnt care about fixing it so it'll be hackily fixed in 1.6.0, for now join our discord and go to the #faq channel to get modified jars that dont have this issue
