### ISSUE TITLE
Mod not working?

### ISSUE THREAD

**Issue by Paul-AdultSwim** [Layers-of-Railways/Railway#343]
Whenever I place the mod into the Mods files it will not load, It will just instantly crash with the code : 1 ( meaning its the mod files problem )
I presume its because its not compatible with a different mod but I do not know.
![image](https://github.com/Layers-of-Railways/Railway/assets/107887279/125b288b-05b8-4285-9374-387a6ad8a2e2)

**Comment by IThundxr** [comment]
Send a log, remove optifine, use embeddium & oculus instead

**Comment by Paul-AdultSwim** [comment]
@IThundxr Does OptiFine effect the mod by just not letting it work?
[latest.log](https://github.com/Layers-of-Railways/Railway/files/13649910/latest.log)

**Comment by IThundxr** [comment]
> @IThundxr Does OptiFine effect the mod by just not letting it work?
> 
> [latest.log](https://github.com/Layers-of-Railways/Railway/files/13649910/latest.log)
> 
> 

Yes, it's not supported by us & breaks steam n rails

**Comment by Paul-AdultSwim** [comment]
Sorry to trouble you, however is there anyway that you can still have OptiFine whistle having Steam 'n' Rails?

**Comment by IThundxr** [comment]
> Sorry to trouble you, however is there anyway that you can still have OptiFine whistle having Steam 'n' Rails?

No, use embeddium + oculus as alternatives, optifine breaks a lot of mods and it being closed source makes it impossible to support it

**Comment by Paul-AdultSwim** [comment]
Would Embeddium or Oculus support my other mods as they are only compatible with Opti?
( not all are with Opti )

**Comment by IThundxr** [comment]
> Would Embeddium or Oculus support my other mods as they are only compatible with Opti? ( not all are with Opti )

Yes it will

**Comment by Paul-AdultSwim** [comment]
Thank You.

**Comment by Paul-AdultSwim** [comment]
Great new Issue :(
Still does not work. Same Code error : 1
![image](https://github.com/Layers-of-Railways/Railway/assets/107887279/084f1c36-9172-4f13-92d9-85d4be3d5fb0)
[latest.log](https://github.com/Layers-of-Railways/Railway/files/13650037/latest.log)

**Comment by IThundxr** [comment]
> Great new Issue :( Still does not work. Same Code error : 1 ![image](https://private-user-images.githubusercontent.com/107887279/289915659-084f1c36-9172-4f13-92d9-85d4be3d5fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTU2NTQsIm5iZiI6MTcwMjM5NTM1NCwicGF0aCI6Ii8xMDc4ODcyNzkvMjg5OTE1NjU5LTA4NGYxYzM2LTkxNzItNGYxMy05MmQ5LTg1ZDRiZTNkNWZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxNTM1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGQ5NDE5ZTQzNTZiNTZiMDQxOTRmMTM0NjNjODg2ZjFmZjNmZTY0NWI2ZDBlMTliZjRlNjc4NzFhZmU3MWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f-AoA3Im1MGfzksqCnyRPgPr6AOgTtOM10LLUx7N38E) [latest.log](https://github.com/Layers-of-Railways/Railway/files/13650037/latest.log)

Try with just create + steam n rails, add a few mods and find out which is conflicting

**Comment by Paul-AdultSwim** [comment]
Yeah, I thought doing so.

**Comment by Paul-AdultSwim** [comment]
Oh, Its Steam 'n' Rails crashing it.

**Comment by Paul-AdultSwim** [comment]
Ill try Steam 'n' Rails 1.5.1

**Comment by Paul-AdultSwim** [comment]
Nvm, ik what to do now :D
