### ISSUE TITLE
Bogey disassemble bug 0-6-0 bogey

### ISSUE THREAD

**Issue by Mrtrainman** [Layers-of-Railways/Railway#348]
### Describe the Bug

when i was playing minecraft the 0-6-0 boogey has not been fixed from disassemble

### Reproduction Steps

1.building a train
2.putting a 0-6-0 bogey
3.assemble the train and disassemble
...

### Expected Result

the bogey will change iinto a different one

### Crash Report or Log

none

### Operating System

windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

forge-43.2.21

### Other Mods

i have a lot of mods

### Additional Context

idk but -0-6-0 bogey is the issue

**Comment by IThundxr** [comment]
cant reproduce on any bogey.
