### ISSUE TITLE
Assembling a train does not work across track types

### ISSUE THREAD

**Issue by RosaryMala** [Layers-of-Railways/Railway#349]
### Describe the Bug

When assembling a train at a station, it only considers tracks that are the exact same type for the assembly, and any bogeys on other types of track are not considered 

### Reproduction Steps

1. Place down a straight stretch of track, using various track types of the same width, such as andesite, oak, tieless, etc.
2. Place a station on the track.
3. Attempt to assemble a train.

### Expected Result

It's expected that assembling a train should only care about the track width, and not the ties.

### Screenshots and Videos

All dark oak is fine: 
![image](https://github.com/Layers-of-Railways/Railway/assets/288477/9e8bf355-12fb-46cc-a9ff-85f3117aab1b)

If the station is dark Oak, the train can't be assembled on tieless tracks: 
![image](https://github.com/Layers-of-Railways/Railway/assets/288477/37406418-2455-4cc5-8711-779cfcc52bcd)

Putting the station onto a tieless track allows assembly only up to where the tracks change to have dark oak ties:
![image](https://github.com/Layers-of-Railways/Railway/assets/288477/b4c5a4a4-7ddf-4538-8e02-1b7ec5bb5bbf)

### Operating System

Windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

**Comment by techno-sam** [comment]
This really needs to be fixed on Create's side, there's no clean way to mixin and do this on our side.
