### ISSUE TITLE
Narrow bogeys crash game.

### ISSUE THREAD

**Issue by SAWYER12346** [Layers-of-Railways/Railway#353]
### Describe the Bug

For some reason minecraft crashes when I place a narrow bogey. Here the error code : java.lang.NoSuchMethodError: 'com.simibubi.create.content.trains.bogey.BogeyRenderer$BogeyModelData[] com.railwayteam.railways.content.custom_bogeys.CRBogeyRenderer$NarrowSmallBogeyRenderer.getTransform(com.jozufozu.flywheel.core.PartialModel, com.mojang.blaze3d.vertex.PoseStack, boolean, int)'

### Reproduction Steps

1. Make a station with narrow tracks.
2. Place a bogey.
3. And the just crashes.
...

### Expected Result

Thev game crashes.

**Comment by IThundxr** [comment]
Attach a crash log, https://github.com/Layers-of-Railways/Railway/wiki check the wiki for the correct version corresponding with your create version
