### ISSUE TITLE
Own player model does not render when Tweakeroo freecam is enabled

### ISSUE THREAD

**Issue by James103** [Layers-of-Railways/Railway#354]
### Describe the Bug

When Create: Steam and Rails is installed along with Tweakeroo, Tweakeroo's Free Camera mode allows free view of the world around the player, but the player itself does not render.

### Reproduction Steps

1. Install all mods listed below.
2. Create a new world.
3. Enable the Free Camera mode from Tweakeroo.

### Expected Result

The player model should render, as it does when the Free Camera mode is disabled and when the Remote Lens is used on a Conductor to make it look at the player.

### Operating System

Windows 10

### Mod Version

1.5.1

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric Loader 0.14.25

### Other Mods

```
create-fabric-0.5.1-c-build.1160+mc1.19.2
fabric-api-0.76.1+1.19.2
malilib-fabric-1.19.2-0.13.0
Steam_Rails-1.5.1+fabric-mc1.19.2
tweakeroo-fabric-1.19.2-0.14.3
```

**Comment by techno-sam** [comment]
Fixed in commit c45535e0754101c94f3effb9f67730ce3bf98040
