### ISSUE TITLE
[1.20.1] Particle settings from this mod messes with PNC's air particle scaling

### ISSUE THREAD

**Issue by Vectrobe** [Layers-of-Railways/Railway#357]
### Describe the Bug

The particle creation inside this mod causes the air particles from pneumaticraft to be scaled extremely large, however its not clear why this is, and whether if a fix in pnc might result in the particles in this mod being too small...
There doesnt have to be anything of this mod in the world for the issue to exist, its purely to do with how this mod and pnc either creates their particle factories or it may be a mixin conflict.

https://github.com/TeamPneumatic/pnc-repressurized/issues/1274

### Reproduction Steps

Create a simple instance with the latest 1.20.1 neoforge, pneumaticraft and create + steam'n'rails.
Make an empty flat world.
Make a simple pnc pressure chamber and venting tube comming from a creative compressor set at 4.5bar.
Observe the particles will be the wrong size, but then if you exit and disable steam'n'rails and check again, the particles will be normal

### Expected Result

Particle sizes between this mod and pnc should be correct when both these mods are enabled

### Screenshots and Videos

![Screenshot_24](https://github.com/Layers-of-Railways/Railway/assets/3912867/4eed31b4-4ff2-4799-8641-dea4079abf48)
![Screenshot_23](https://github.com/Layers-of-Railways/Railway/assets/3912867/c478beab-0848-4c32-a05b-f7bfc667c993)

### Operating System

win10

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

NeoForge 47.1.84

### Other Mods

Pneumaticraft Repressurized 6.0.12

### Additional Context

at minimum this report is intended to track the conflict between these mods

**Comment by techno-sam** [comment]
This is very odd - we do not have any particle-related mixins, as far as I am aware.
