### ISSUE TITLE
Trains stop existing when I assemble them

### ISSUE THREAD

**Issue by IDKWTNM** [Layers-of-Railways/Railway#362]
### Describe the Bug

So, after I make the engine and glue it, the engine just ceases to exist when I assemble it. it's been an issue and I don't know why it is happening.

### Reproduction Steps

1.Make station and build engine
2.glue everything together
3.assemble it, then it disappears
...

### Expected Result

Basically it vanishes after I hit 'Assemble'

### Operating System

Mac book Pro

### Mod Version

1.5.3

### Create Mod Version

0.5.1e

### Minecraft Version

1.19.2

### ModLoader and Version

Forge

### Other Mods

Create Deco, Create Alloyed, Framed blocks, DB Extended, then the create mod itself

**Comment by IThundxr** [comment]
Mismatched versions https://github.com/Layers-of-Railways/Railway/wiki
