### ISSUE TITLE
Driving a handcar causes exhaustion / consumes hunger

### ISSUE THREAD

**Issue by James103** [Layers-of-Railways/Railway#363]
### Describe the Suggestion

Currently, as far as I can tell by checking the code, driving a handcar is free, as in there is no fuel to consume and no hunger cost.
This allows unlimited travel at speeds exceeding that of sprinting, as long as the tracks are there.

This can be rectified by adding an exhaustion cost to driving a handcar, ideally based on the amount of time spent holding W or S to accelerate or decelerate the handcar. This incentivizes either bringing a significant amount of food or building and operating a proper train for trips of more than a few hundred meters.

For example, if driving a handcar adds 0.1 exhaustion per second, and therefore costs 1 food point every 40 seconds, a player can go up to 16 km before needing to eat, assuming full hunger and saturation.
If the exhaustion rate is instead 0.4 per second, driving a handcar would cost 1 food point every 10 seconds, and the maximum range between meals would be reduced to around 4 km.

For comparison, sprinting costs 1 food point every 40 meters (7 seconds), swimming costs 1 food point every 400 meters (1-2 minutes), and driving a handcar from Immersive Engineering at maximum throttle costs 1 food point every 3 seconds.

**Comment by RosaryMala** [comment]
Of note: Driving a train is also free. You can technically add fuel to go faster, but even without fuel, it's plenty fast.

**Comment by James103** [comment]
This appears to be implemented in https://github.com/Layers-of-Railways/Railway/commit/84698f17c279756623a9d9789480bede27274398. However, Extendo Grips prevent hunger loss but don't lose durability; should they in survival?

**Comment by techno-sam** [comment]
This behavior is consistent with using an Extendo Grip on a Hand Crank, so I believe it makes sense.

**Comment by IThundxr** [comment]
Implemented
