### ISSUE TITLE
PLEASE HELP URGENTLY! Create Steam n Rails fails to load correctly (not enough data)

### ISSUE THREAD

**Issue by PandoraAnimeCoder** [Layers-of-Railways/Railway#367]
### Describe the Bug

(I am a beginner to Github)
An error occurs everytime I try to use Create Steam n Rails which states that the mod has failed to load correctly, I had to uninstall the addon to use Minecraft which is a shame because I really enjoyed using it.

It states that there is not enough Data available, I allocated 8G to Minecraft but still the error persists.
I have uninstalled the mod and the game runs without it but I want the mod to function, I normally use the 1.5.2 version where the "not enough data" error occurs.

### Reproduction Steps

1.Have Create and Create Steam n Rails installed
2. Run Minecraft
3. No matter the version, mod will occur and persist
...

### Expected Result

1. I run Minecraft
2. Mods will load
3. Game will run

### Screenshots and Videos

![Screenshot 2024-01-07 153547](https://github.com/Layers-of-Railways/Railway/assets/155884701/63179529-d0ba-4970-b1b0-62e3a5658d17)

### Crash Report or Log

https://pastebin.com/3SY6Ekm7

### Operating System

Windows 11

### Mod Version

1.5.2

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.1

### Additional Context

It occured very suddenly, this is my first post on Github I just want the error gone, please help me

**Comment by IThundxr** [comment]
Delete the config files that start with railways in the config folder, they got corrupted

**Comment by PandoraAnimeCoder** [comment]
how do I do that?
nvm i found out.
Thank you so much mate!

**Comment by IThundxr** [comment]
go to the config/ folder, find any file starting with "railways-" and delete it
