### ISSUE TITLE
Train disappears with an error when trying to assemble it

### ISSUE THREAD

**Issue by semenishchev** [Layers-of-Railways/Railway#368]
### Describe the Bug

I'm using the most basic train contraption, when I click assemble in 

### Reproduction Steps

1. Enter assembly mode on train station
2. Build basic train
3. Click "Assemble"

### Expected Result

An assembled train

### Screenshots and Videos

https://github.com/Layers-of-Railways/Railway/assets/38401696/a4dc6eb1-dfa3-4ee1-8773-6a78c6216aec

### Crash Report or Log

https://pastebin.com/C0sVyDuX

### Operating System

MacOS

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.17

### Other Mods

[modrinth.index.json](https://github.com/Layers-of-Railways/Railway/files/13853468/modrinth.index.json)
This is modpack I'm using

**Comment by SpottyTheTurtle** [comment]
Read the wiki here: https://github.com/Layers-of-Railways/Railway/wiki/ and ensure your create and Steam 'n Rails versions match the table.
