### ISSUE TITLE
Mod crashes when Category opened in menu

### ISSUE THREAD

**Issue by FnafPizzaFan** [Layers-of-Railways/Railway#370]
### Describe the Bug

The mod freezes and then crashes when I open its category in the creative menu.

### Reproduction Steps

1. Load World
2. Open Creative menu
3. Click on its Tab

### Expected Result

The mod to function like every other functional mod.

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/90162306/56acf309-ecba-4717-8011-22f91529bb0f)

I'm not sure how to embed files larger than 10mb so I just uploaded it to MediaFire
https://www.mediafire.com/file/snyxni6ad4v8lc7/Base+Profile+2024.01.16+-+22.05.57.01.mp4/file

### Crash Report or Log

https://mclo.gs/kq82AK5

### Operating System

Windows 10

### Mod Version

1.4.8

### Create Mod Version

0.5.1f

### Minecraft Version

1.18.2

### ModLoader and Version

Forge 40.2.4

### Other Mods

'Dustrial Decor
Architecturay API
ChinjufuMod +JapaneseBlock
Cloth Config API
Create
Create Crafts & Additions
Create Deco
Create: Alloyed
Create: Design n' Decor
Create: Diesel Generators
Create: Modern Train Parts
Create: Steam 'n' Rails <-- 
Nucleartech
Decorative Blocks
Essential Mod
Framework
GeckoLib
JEI
Kotlin for Forge
Macaw's Doors
Macaw's Furniture
Macaw's Roof
Macaw's Trapdoors
Mapper Base
MrCrayfish's Gun Mod
Orva Alarms and Sirens
Road Stuff
Rubidium
Saro's Roadsigns
TerraBlender
UCM (Ultimate Car Mod)
WorldEdit

### Additional Context

The mod does not crash whenever I search for items and blocks individually, you can see that from the video I linked.

[Side note: I hate GitHub, I finished writing this and then accidentally exited out of my browser erasing all my progress previously]

**Comment by IThundxr** [comment]
Log doesn't really give much info so try with just create + steam n rails, chances are some other mod is doing something weird and by chance steam n rails causes a crash with it

**Comment by IThundxr** [comment]
closing since no response in 2 weeks
