### ISSUE TITLE
Direwolf20 1.19 pack fails to load with create 0.5.1f and Steam and Rails 153

### ISSUE THREAD

**Issue by wcdanh2** [Layers-of-Railways/Railway#372]
### Describe the Bug

When trying to add steam and rails to the Direwolf20 1.19 pack the pack crashes during launch.

I have another instance with the same version of create and steam and rails that is working which suggests that there is a different mod or config in the DW20 pack causing the conflict.

Thanks,
Bill

### Reproduction Steps

Steps to reproduce:

1:    Install Direwolf20 1.19 version 1.12.0
2:   Update the version of create in the pack from 0.5.1b to 0.5.1.f (https://www.curseforge.com/minecraft/mc-mods/create/files/4835190)
3:    Add Steam and rails v153 (https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails/files/4836195)
4:    Launch game and crash before launch is complete.

### Expected Result

(required field)
Game should launch successfully. 

### Crash Report or Log

https://api.paste.ee/p/Qot2a

### Operating System

Windows 10

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.14 and 43.3.0 both produced the issue

**Comment by IThundxr** [comment]
Update modernfix

**Comment by wcdanh2** [comment]
That does appear to have solved the issue.  Thanks for such a fast response.
