### ISSUE TITLE
TFC support

### ISSUE THREAD

**Issue by dudebehinddude** [Layers-of-Railways/Railway#374]
### Describe the Suggestion

[TerraFirmaCraft](https://modrinth.com/mod/terrafirmacraft) has a lot of new wood types, and it would be cool to be able to make rails out of them

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/66212375/75b99483-3c8e-40f1-b7ae-cb62f75094e3)

**Comment by IThundxr** [comment]
already exists in 1.6.0, hasnt been released yet
