### ISSUE TITLE
Missing wooden train tracks

### ISSUE THREAD

**Issue by 0Navis0** [Layers-of-Railways/Railway#380]
### Describe the Suggestion

I noticed that cherry and bamboo wooden tracks are missing. 

Also modded woods other than BOP ones are not supported, like for example Quark azalea, trumpet, and ashen woods. 

A great solution would be to automatically add wooden train tracks depending of which woods are avalaible.

**Comment by IThundxr** [comment]
Quark compat and cherry and bamboo tracks are already in the next update.

we cannot have it automatically add tracks since the textures need to be made manually

**Comment by 0Navis0** [comment]
Well then it would be great to support cherry and bamboo , and muddy oak and cypress from GoodEnding.

**Comment by 0Navis0** [comment]
It would be nice to if you kept this issue opened, so I can keep updating it as mods update and need support, like for example Abnormal mods.

**Comment by IThundxr** [comment]
> It would be nice to if you kept this issue opened, so I can keep updating it as mods update and need support, like for example Abnormal mods.

That's fine just open another suggestion issue for each mod

**Comment by IThundxr** [comment]
Makes tracking stuff much easier

**Comment by 0Navis0** [comment]
Eh ok

**Comment by BugInYourCode01** [comment]
How about "simply" adding Every Combat Support? Then all mods (at least those with Every Combat support) should have their train tracks.

**Comment by IThundxr** [comment]
> How about "simply" adding Every Combat Support? Then all mods (at least those with Every Combat support) should have their train tracks.

it isn't that easy, the textures can't be procedurally generated
