### ISSUE TITLE
Train assembaly issue

### ISSUE THREAD

**Issue by Entitydemon4028** [Layers-of-Railways/Railway#386]
### Describe the Bug

I was playing in my survival world had tracks made and placed down and got a train setup and went to go assemble it but it just dissapeared anf it is not lettting me dissasemble the train I have to make a entire new train.

### Reproduction Steps

1.place down the tracks
2.right click the tracks to make the train station 
3.Then build the train then assemble the train 
...

### Expected Result

I was expecting when I pressed assemble train the train would assemble and I would be able to use the train but it has not worked like that and it is a little frustrating because i just want to build a train to get places.

### Operating System

windows 10

### Mod Version

1.5.2

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 0.244.4

**Comment by IThundxr** [comment]
Use steam n rails 1.5.3 for patch f (0.5.1f)

**Comment by Entitydemon4028** [comment]
I have and the train disappears to but I can't go below 1.5.2 because then my game crashes

**Comment by IThundxr** [comment]
Your not on patch f then, check the wiki over at https://github.com/Layers-of-Railways/Railway/wiki and get the correct version you need

**Comment by Entitydemon4028** [comment]
I am though I might have to get a new or a different create file
