### ISSUE TITLE
Train Coupler visual glitch

### ISSUE THREAD

**Issue by BlazR21** [Layers-of-Railways/Railway#388]
### Describe the Bug

When I used the train coupler on my narrow gauge train, multiple bogies doesn't appear like they're all connected even though they are.

### Reproduction Steps

1. Make 1 main "train"
2. Make 3 carriages
3. Use the Train Coupler to attach the 1 main "train" to the 3 carriages

### Expected Result

All the bogies should appear connected.

### Screenshots and Videos

![2024-02-18_17 25 56](https://github.com/Layers-of-Railways/Railway/assets/84936768/4944bd70-c419-4826-bef1-0ec9f3511aa6)

### Operating System

Windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

**Comment by IThundxr** [comment]
if you can reproduce this on the latest version open a new issue
