### ISSUE TITLE
PLEASE MAKE OPTIFINE WORK WITH STEAM AND RAILS PLEASE

### ISSUE THREAD

**Issue by TUF-SCAR** [Layers-of-Railways/Railway#392]
### Describe the Suggestion

The time I try to make a list of mods I will play with I cannot put Optifine, It's the worst, Optifine is just too good to be left aside

**Comment by IThundxr** [comment]
Use embeddium + oculus instead, anyway optifine "compat" has been fixed for 1.6.0 but we cant guarantee it'll stay that way with the mass amounts of changes optifine makes
