### ISSUE TITLE
Boilers crash Game

### ISSUE THREAD

**Issue by redboi18** [Layers-of-Railways/Railway#396]
### Describe the Bug

Boilers in the latest version of git crash the game when placed

### Reproduction Steps

1. place boiler
2. crash
3. exit code -1
...

### Expected Result

I expected no crash

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/124214835/3690551b-5d4d-4f6e-b62a-31f48d90fb95)

### Crash Report or Log

cant

### Operating System

Idk why this matters but Windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Git forge version

### Other Mods

Just the ones that come with git

**Comment by IThundxr** [comment]
log :p

**Comment by redboi18** [comment]
[crash-2024-03-06_15.07.36-client.txt](https://github.com/Layers-of-Railways/Railway/files/14516681/crash-2024-03-06_15.07.36-client.txt)
