### ISSUE TITLE
Game crashes with sodium 1.4.10

### ISSUE THREAD

**Issue by Gust4voSSM** [Layers-of-Railways/Railway#397]
### Describe the Bug

If a modpack has sodium 1.4.10 and Steam n' Rails (1.5.1 Fabric 1.20.1 + dependencies) any time a block from this mod is placed the game crashes.

### Reproduction Steps

1. Modrinth Launcher;
2. Fabric 1.20.1 Profile;
3. Fabric API 0.92.0+1.20.1 (Latest);
4. Sodium 1.4.10;
5. Create Fabric 0.5.1-d-build.1161+mc1.20.1;
6. Steam n' Rails 1.5.1-fabric-mc1.20.1 (Latest);
7. Place steam n' rails train track or bogey.

### Expected Result

Textures fail to load (they get purple and black) and the game crashes

### Crash Report or Log

[crash-2024-03-06_17.31.56-client.txt](https://github.com/Layers-of-Railways/Railway/files/14517294/crash-2024-03-06_17.31.56-client.txt)

### Operating System

Windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric (Modrinth recommended version, no idea what it is)

### Other Mods

Cloth Config API 11.1.118+fabric
JEI 15.3.0.4
Mod Menu 7.2.2

**Comment by IThundxr** [comment]
Non SNR issue
Use the exact versions listed below
create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 indium 1.0.21

**Comment by Gust4voSSM** [comment]
Thank you for the reply!
