### ISSUE TITLE
Visual glitch/weird particles/misplaced boilers

### ISSUE THREAD

**Issue by redboi18** [Layers-of-Railways/Railway#398]
### Describe the Bug

To many particles when breaking boilers and when placing the boiler in the other way it doesnt place right when trying to stack

### Reproduction Steps

1.none needed
2.
3.
...

### Expected Result

Idk

### Screenshots and Videos

![2024-03-07_14 37 56](https://github.com/Layers-of-Railways/Railway/assets/124214835/9e4ef3bc-471d-4f7d-804e-5d11891cd1db)
![2024-03-07_14 38 04](https://github.com/Layers-of-Railways/Railway/assets/124214835/df974846-4406-47e4-8f3b-96d0c70c9b9f)
![2024-03-07_14 38 33](https://github.com/Layers-of-Railways/Railway/assets/124214835/2dca5f54-a017-4e8c-b65a-16f54d8d3368)

### Crash Report or Log

none

### Operating System

Idk why this matters but Windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Git forge version

### Other Mods

Git version stuff

**Comment by IThundxr** [comment]
The particles thing is something that affects vanilla aswell with blocks like anvils and cauldrons
