### ISSUE TITLE
Does not work with Optifine 

### ISSUE THREAD

**Issue by Pokecraft1234** [Layers-of-Railways/Railway#399]
### Describe the Bug

Hello, I have come to inform you of an incompatibility between your mode and Optifine which is normally supposed to work with the curseforge modes in fact yours displays an error window, is this coming from me? Or is this normal and can you fix it please ?

### Reproduction Steps

1.install optifine in 1.20.1
2.put optifin folder in the curseforge modpack folder
3.install create steam’n’rail 1.20.1 curseforge
4.play

### Expected Result

An error window opens

### Screenshots and Videos

![IMG_1598](https://github.com/Layers-of-Railways/Railway/assets/162625097/b0f57cac-9dd1-433d-8779-aa792660fb68)
)

### Crash Report or Log

None

### Operating System

Windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Curseforge 47.2.20

### Other Mods

Optifine 1.20.1

### Additional Context

None

**Comment by IThundxr** [comment]
You can modify the config to fix this or wait until the next update that fixes this

**Comment by Pokecraft1234** [comment]
Thank you very much for your quick response. very good but the game tells me that there is a danger of crashing, is this true?

**Comment by TyffAx** [comment]
Hello, i have the same issue, i read your answer but i don't find the config file in my Minecraft folder. Do you know where is it please ?
