### ISSUE TITLE
Hard dependency on `0.5.1-f-build.1329+mc1.20.1` causes Steam & Rails to be unable to launch with latest commit

### ISSUE THREAD

**Issue by solonovamax** [Layers-of-Railways/Railway#404]
### Describe the Bug

A hard dependency on `0.5.1-f-build.1329+mc1.20.1` causes steam & rails to be unable to launch with the latest create-fabric build, which is `0.5.1-f-build.1335+mc1.20.1`.

### Reproduction Steps

1. Compile from source
2. Add steam & rails + latest create release
3. Launch game

### Expected Result

Game is able to launch

### Screenshots and Videos

N/A

### Crash Report or Log

N/A

### Operating System

Arch Linux 6.7.4-zen1-1-zen

### Mod Version

1.6.0 (latest commit)

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 1.15.7

### Other Mods

N/A (I have other mods, but they are not the cause of this.)

### Additional Context

N/A

**Comment by IThundxr** [comment]
Hmm latest git should be depending on 0.5.1-f, therefore it should work https://github.com/Layers-of-Railways/Railway/blob/92f9205a4df730d9ec3a916fa1d24e1bd3f3f1a1/build.gradle.kts#L189

**Comment by IThundxr** [comment]
Interesting, nice catch seems like the version is actually wrong

**Comment by IThundxr** [comment]
Fixed on 1.19/dev and merged into 1.20/dev
