### ISSUE TITLE
please fix [Worker-Main-7/ERROR] [minecraft/Util]: Invalid path in pack: railways:models/block/bogey/wide/scotch_yoke/Broad_Gauge_L_0-2-0.bbmodel, ignoring exit code: 0

### ISSUE THREAD

**Issue by ff6f8d68** [Layers-of-Railways/Railway#407]
### Describe the Bug

[15:04:40] [Worker-Main-7/ERROR] [minecraft/Util]: Invalid path in pack: railways:models/block/bogey/wide/scotch_yoke/Broad_Gauge_L_0-2-0.bbmodel, ignoring exit code: 0

### Reproduction Steps

1. use macOS and prism launcher
2. create a new instance with Minecraft version 1.20.1
3. install create
4. install create steam´n rails

### Expected Result

Minecraft starts

### Crash Report or Log

https://mclo.gs/doEmmQf

### Operating System

macOS Sonoma 14.3.1

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

forge 47.2.0

### Other Mods

[Forge]ctov-3.4.2.jar
ACOFI-SkylightModding-1.20.1-1.0.jar
AmbientSounds_FORGE_v5.3.9_mc1.20.1.jar
architectury-9.2.14-forge.jar
ars_nouveau-1.20.1-4.9.0-all.jar
BagWithCreativeBlocks.jar
bellsandwhistles-0.4.3-1.20.x.jar
bigcontraptions-1.0.jar
botarium-forge-1.20.1-2.3.3.jar
bpvoid-1.0.1.jar
Builder's-Tabs-1.20.x-(v.1.4.0).jar
caelus-forge-3.1.0+1.20.jar
collective-1.20.1-7.40.jar
compressedcreativity-1.20.1-0.1.8.b.jar
copiescats-0.0.1-1.20.1.jar
craftfix.zip
Create Sweets And Treats 1.1.1.jar
create__potato_weapons(1.20.1).jar
create_aquatic_ambitions-1.20.1-1.0.0.jar
create_basic_additions-1.20.1-1.0.1a-forge.jar
create_better_smithing_templates-1.20.1.jar
create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.10.jar
create_connected-0.7.4-mc1.20.1-all.jar
create_easy_structures-0.1.1-1.20.1.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.8.jar
create_gravity-1.20.1-1.1.0.jar
create_haven-0.0.4-1.20.1.jar
create_high_pressure-1.1.0.jar
create_jetpack-forge-4.2.1.jar
create_mechanical_extruder-1.20.1-1.5.7.e-22.jar
create_mechanical_spawner-1.20.1-0.0.14.e-22.jar
create_more_armor-1.0.4.jar
create_needed_recipes-1.0.0.jar
create_oxidized-0.1.1.jar
create_power_loader-1.4.0-mc1.20.1.jar
create_prismarine_automation-1.20.1-forge.jar
create_ratatouille-1.20.1-1.0.jar
create_salt 1.20.1-1.1.0.jar
create_train_perspective-0.1.2.jar
create_trimmed.jar
create_tweaked_controllers-1.20.1-1.2.2.jar
create_wizardry-1.20.1-0.1.2.jar
create-1.20.1-0.5.1.f.jar
create-coins-1.0.2-1.20.1.jar
create-condensed-milk-forge1.20.1-1.0.1.jar
Create-Dreams-n-Desires-1.20.1-0.2c.PREBETA.jar
Create-Guardian-Beam-Defense-1.3.0b-1.20.1.jar
create-mod-trims-1.0.0.jar
create-new-age-forge-1.20.1-1.1.2.jar
create-striated-stones-fix-1.0.2.jar
create-structures-0.1.1-1.20.1-FORGE.jar
create-stuff-additions1.20.1_v2.0.4a.jar
create-track-map-1.4+mc1.20.1-neoforge.jar
createaddition-1.20.1-1.2.2.jar
createarmoryv0.6.1n.jar
createbicbit-1.20.1-0.0.70.jar
createbigcannons-forge-1.20.1-0.5.3.b.jar
CreateCasing-1.20.1-1.6.0.jar
createdieselgenerators-1.20.1-1.2h.jar
createdoener-0.1.2.1.jar
createendertransmission-2.0.7-1.20.1.jar
createframed-1.20.1-1.4.1.jar
CreateFullyAutomated.jar
creategoggles-1.20.1-0.5.5.f-[FORGE].jar
createhc-1.0.4-forge-1.20.1.jar
createimiltarized1.3.2.jar
createliquidfuel-2.1.0-1.20.1.jar
createloveandwar-0.1-1.20.1.jar
CreateMoreAutomation-1.20.1-0.4.0.jar
createmoredrillheads-2.0.3-1.20.1.jar
createmr-1.20.1-0.0.7.jar
createoreexcavation-1.20-1.4.2.jar
createpickywheels-forge-1.20.1-0.5.1.f-b.jar
createrailwaysnavigator-0.3.0-beta-1.20.1.jar
CreateUnbreakableTools-1.0+forge-1.20.1.jar
createunlimited-0.6.0.jar
createutilities-0.2.0+1.20.1.jar
CreativeCore_FORGE_v2.11.25_mc1.20.1.jar
curios-forge-5.7.2+1.20.1.jar
dall 1.7 1.20.1.jar
design_decor-0.2a-1.20.1.jar
destroy-1.20.1-0.8.jar
emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge.jar
Estrogen-4.1.0+1.20.1-forge.jar
eureka-1201-1.3.0-beta.4.jar
expandingtechnologies-1.0.2.jar
fancymenu_forge_3.1.2_MC_1.20.1.jar
FarmersDelight-1.20.1-1.2.4.jar
flansmod-1.20.1-0.4.168.jar
FramedBlocks-9.2.1.jar
fusion-1.1.1-forge-mc1.20.1.jar
garnished-1.7.2+1.20.1.jar
geckolib-forge-1.20.1-4.4.4.jar
htm-1.20.1-forge-1.0.5.jar
infiniverse-1.20.1-1.0.0.5.jar
interiors-0.5.2+mc1.20.1-FORGE.jar
irons_spellbooks-1.20.1-3.1.0.jar
ItemPhysic_FORGE_v1.7.0_mc1.20.1.jar
jei-1.20.1-forge-15.3.0.4.jar
journeymap-1.20.1-5.9.18p1-forge.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
kotlinforforge-4.10.0-all.jar
kubejs-create-forge-2001.2.5-build.2.jar
kubejs-forge-2001.6.4-build.138.jar
LibX-1.20.1-5.0.13.jar
lithostitched-forge-1.20.1-1.1.5.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
memoryleakfix-forge-1.17+-1.1.5.jar
memoryusagescreen-forge-mc1.20-1.9.0.jar
memoryusagetitle-forge-1.0.0.jar
molten_vents_custom_blocks.json
molten_vents-1.20.1-2.0.6.jar
notenoughcrashes-4.4.7+1.20.1-forge.jar
ns-cr-rc-0.0.0.jar
packmger-forge-1.20.1-v0.1.0-beta.jar
Patchouli-1.20.1-84-FORGE.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
pneumaticcraft-repressurized-6.0.14+mc1.20.1.jar
potatofirepower-1.0.jar
Reblured-1.20.1-1.3.0.jar
Recipes For Create-0.6.0-(1.20.1).jar
rhino-forge-2001.2.2-build.18.jar
salt-1.20.1-1.2.4.jar
SkyblockBuilder-1.20.1-5.0.13.jar
sliceanddice-forge-3.2.0.jar
Steam robots.jar
Steam_Rails-1.5.3+forge-mc1.20.1.jar
superflatworldnoslimes-1.20.1-3.2.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
trainperspectivefix-1.0.0-universal.jar
valkyrienskies-120-2.1.3-beta.1.jar
vintageimprovements-1.20.1-0.1.3.2.jar
Xaeros_Minimap_24.0.1_Forge_1.20.jar

**Comment by IThundxr** [comment]
Fixed in next update already, it's just a warning and you can ignore it for now

**Comment by ff6f8d68** [comment]
and can you say me what of the listed mods maked this error [Worker-Main-7/ERROR] [minecraft/Util]: Invalid path in pack: byg:textures/block/track/TODO.txt, ignoring

modid: byg

**Comment by ff6f8d68** [comment]
`@
`

**Comment by ff6f8d68** [comment]
``

**Comment by ff6f8d68** [comment]
`    `

**Comment by ff6f8d68** [comment]
` `
