### ISSUE TITLE
Trains don't get coupled if the coupler is placed after the trains arrive

### ISSUE THREAD

**Issue by sebastianolsa** [Layers-of-Railways/Railway#41]
I tried to narrate it in a video, but the coupler only seems to work when it's placed before the trains come to it. If the coupler is placed next to the trains, it doesn't couple the two trains when activating it with redstone. The video was recorded on 1.18.2 using steam n' rails 1.0.5 and create 0.5.0g as well as a bunch of other non-create QOL mods. Please let me know if I'm just being dumb.

https://www.dropbox.com/s/z23sl8u4ayilube/somethingstrangewithcouplers.mp4?dl=0

**Comment by SpottyTheTurtle** [comment]
happens with base Create stations stations as well, it's just how Create works right now

**Comment by techno-sam** [comment]
Should be fixed in next release.
