### ISSUE TITLE
Cannot select bogie styles on i3wm

### ISSUE THREAD

**Issue by EliConstructor** [Layers-of-Railways/Railway#410]
### Describe the Bug

When trying to select a bogie while running Linux with i3wm as the window manager, I cannot select bogies from the radial menu. When I try to left click, the cursor just changes to the 4 way arrows one that usually comes up for moving stuff, and nothing is actually selected. This does not happen on the same game instance on the same Linux install when using KDE Plasma instead of i3wm. I haven't tested any other environments than i3wm and KDE Plasma. 

### Reproduction Steps

1. Install Steam and Rails into a modpack and run said modpack on i3wm
2. Try to select bogie from radial menu
3. It wont let you

### Expected Result

Selecting the bogie with left click should work.

### Screenshots and Videos

My sincerest apologies for the phone photo of my monitor. I could not for the life of me get my screenshot software to include the mouse cursor in the screenshot. 
Anyway here's the cursor that appears when I left click on the icons. It changes back to the normal one when letting go of left click, but nothing gets selected.
![316575023-a3f9736f-8501-4b39-85b0-79d8dc3f8537(1)](https://github.com/Layers-of-Railways/Railway/assets/32846069/55a2e416-a09d-402b-a057-06ed9aee6923)

### Operating System

Linux (Manjaro, specifically running i3wm)

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.3.8

### Other Mods

Discovered bug with other mods, but it still happens on another instance with just Create and Steam and Rails.

**Comment by IThundxr** [comment]
Try clicking alt only once, and then selecting the bogies that should make it so i3wm doesn't enable that move screen thing. If that however doesn't work try rebinding the key to open nearby toolboxes in the keybind menu to something else, that should let you use that key to open the bogey menu and still select the categories/bogies.

**Comment by EliConstructor** [comment]
Yeah turns out I'm just a bit dumb lmao. Of course it doesn't work if alt is the mod key set in i3wm. Rebinding it fixes it, not a bug in the mod. Thanks for the near instant response.
