### ISSUE TITLE
Error Code -1

### ISSUE THREAD

**Issue by thedeadhorsey** [Layers-of-Railways/Railway#411]
### Describe the Bug

Whenever I launch 1.19.2 with Create Steam 'n' Rails 1.5.3, I get this error code
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'railways'!

### Reproduction Steps

1. Put mod into mods file
2.
3.
...

### Expected Result

Launch Minecraft

### Screenshots and Videos

![image_2024-03-25_220019540](https://github.com/Layers-of-Railways/Railway/assets/164976025/126a41a1-6ba9-4b7d-9f46-d9f7e6583646)

### Crash Report or Log

https://pastebin.com/GgXLQLwK

### Operating System

Windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.15.7

### Other Mods

![image](https://github.com/Layers-of-Railways/Railway/assets/164976025/b3be99ad-3fcd-41ba-aec7-d53dea5e3c68)
![image](https://github.com/Layers-of-Railways/Railway/assets/164976025/e4cab1a5-7f68-4e04-866e-c5a6975d10d8)

**Comment by IThundxr** [comment]
Config file got corrupted, delete all the railways-*.toml files in config/
