### ISSUE TITLE
1.20.1 Crash on assemble train, no storage blocks were used.

### ISSUE THREAD

**Issue by netcore10** [Layers-of-Railways/Railway#414]
### Describe the Bug

I assembled a train, server tick crash

### Reproduction Steps

no idea, tbh

### Expected Result

to not crash

### Crash Report or Log

https://mclo.gs/T0RyH80

### Operating System

windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

latest quilt

**Comment by IThundxr** [comment]
createdieselgenerators is crashing

**Comment by netcore10** [comment]
I removed diesel generators and it does the same thing

**Comment by IThundxr** [comment]
send a new log then

**Comment by netcore10** [comment]
Hmm. It's blank, i'll work on this in the background.

**Comment by netcore10** [comment]
Maybe it is diesel generators? is there some way to work around the issue?

**Comment by IThundxr** [comment]
it is diesel generators that has a mixin that is failing, head to their github instead

**Comment by netcore10** [comment]
Thanks for getting me this far, sorry for wasting your time.
