### ISSUE TITLE
Steam n rails crashed when starting 

### ISSUE THREAD

**Issue by Gamerkuba09hihi** [Layers-of-Railways/Railway#416]
Steam n rails crashed when starting on 1.19.2 forge

**Comment by IThundxr** [comment]
Follow the bug report template and attach a log

**Comment by Gamerkuba09hihi** [comment]
Im sorry im new Where is the bug report template I couldnt find it

**Comment by Gamerkuba09hihi** [comment]
> Follow the bug report template and attach a log

Where do I find the bug report template I am new here

**Comment by IThundxr** [comment]
Just post the log for now

**Comment by Gamerkuba09hihi** [comment]
.

**Comment by IThundxr** [comment]
Missing or unsupported mandatory dependencies:
Mod ID: 'citadel', Requested by: 'untamedwilds', Expected range: '[2,)', Actual version: '[MISSING]'
Mod ID: 'architectury', Requested by: 'vinery', Expected range: '[6.5.77,)', Actual version: '[MISSING]'
Mod ID: 'create', Requested by: 'create_enchantment_industry', Expected range: '[0.5.1.f,)', Actual version: '0.5.1.e'
Mod ID: 'moonlight', Requested by: 'sleep_tight', Expected range: '[1.19.2-2.2.16,]', Actual version: '[MISSING]'
Mod ID: 'doapi', Requested by: 'vinery', Expected range: '[1.1.0,)', Actual version: '[MISSING]'
Mod ID: 'collective', Requested by: 'stackrefill', Expected range: '[7.21,)', Actual version: '[MISSING]'


Not a steam n rails issue

**Comment by Gamerkuba09hihi** [comment]
thank you so much I was getting crazy
