### ISSUE TITLE
Train rotation visual bug 

### ISSUE THREAD

**Issue by netcore10** [Layers-of-Railways/Railway#417]
### Describe the Bug

Sometimes when traveling around, or looking at particular angles, the train will rotate at a wonky angle at random. Not sure if it's sodium. Previous version worked fine, this never happened before.

### Reproduction Steps

not really sure.

### Expected Result

not looking weird?

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/181536/0beb49b1-da7b-4fb7-9636-5e4a400fb58f)

### Crash Report or Log

not a crash

### Operating System

windows 11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

latest quilt

### Other Mods

sodium suite steam and rails and create.

**Comment by netcore10** [comment]
This sometimes happens when moving my mouse left and right too.

**Comment by IThundxr** [comment]
Try with 1.6.x, if it still occurs then it's likely your shaders or another mod not popping the stack properly after applying transformations
