### ISSUE TITLE
i cant dissasemmble a monorail train

### ISSUE THREAD

**Issue by ghost** [Layers-of-Railways/Railway#418]
### Describe the Bug

i cant dissasemmble a monorail train cuz i cant go in a train station im on 1.19.2

### Reproduction Steps

1.make a monorail
2.try going to a station

### Expected Result

the bug

### Operating System

Windows11

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge

**Comment by IThundxr** [comment]
can you attach screenshots or add more info?
