### ISSUE TITLE
smoke doesnt emit from smokestacks when assembled

### ISSUE THREAD

**Issue by ratsinatophat** [Layers-of-Railways/Railway#419]
### Describe the Bug

the smokestacks dont emit smoke when assembled in either train or regular contraption

### Reproduction Steps

1. build a regular train
2. place a smokestack on it
3. glue & assemble, and observe the lack of smoke

### Expected Result

i expected smoke to come out

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/166195805/e1d5d170-0cf3-434c-9d12-40c7b0d23fb6)

### Crash Report or Log

N/A

### Operating System

windows 10

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

0.15.7, 1.20.1

### Other Mods

![image](https://github.com/Layers-of-Railways/Railway/assets/166195805/40cb8440-796d-4e77-9b21-e238f0a3e5ce)
![image](https://github.com/Layers-of-Railways/Railway/assets/166195805/23ef098d-2773-4f5b-b4cf-388f0ed17ed6)

### Additional Context

happened after S&R was update to 1.5.3 i think, but i'm not sure

**Comment by IThundxr** [comment]
1.6.0's new particles should fix this
