### ISSUE TITLE
"Open Bogey Menu", "Open Cycle Menu", "Focus Schematic Overlay" are marked as conflicting

### ISSUE THREAD

**Issue by goteusz-maszyk** [Layers-of-Railways/Railway#421]
### Describe the Bug

Before the update, the first two were hidden behind the third one. However, after an update they became conflicting and marked red.

### Reproduction Steps

1. Go to controls settings
2. see that above keys are red

### Expected Result

They can be bound to the same key while not being marked as conflicting

### Operating System

Nobara 39

### Mod Version

1.6.0

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 0.15.7

**Comment by IThundxr** [comment]
fixed already
