### ISSUE TITLE
1.20.1 Quark Compat Track Issues

### ISSUE THREAD

**Issue by VoidLeech** [Layers-of-Railways/Railway#422]
### Describe the Bug

The Quark compat tracks can't be parsed correctly due to the incorrect id being used. The wrong id is present in the "ingredient" section of the main recipes, as well as the deploying subrecipe for the wide tracks, e.g:
https://github.com/Layers-of-Railways/Railway/blob/1f4bf1b48c4a576cea15e1cd7e4943a39616fc8a/common/src/generated/resources/data/railways/recipes/sequenced_assembly/track_quark_blossom_narrow.json#L17-L19
In 1.20.1 Quark, the slabs have id `quark:{woodtype}_planks_slab`

Additionally, in 1.20.1 Quark, Ancient wood was renamed—in lang files only, id's still use the old names—to Ashen, and Blossom wood was renamed to Trumpet, and this is not reflected in Steam 'n' Rails. The lang file should probably be updated accordingly.

### Reproduction Steps

1. Load Minecraft with both Steam 'n' Rails and Quark
2. Throw any quark wood slab into a recipe step for tracks (or check JEI)
3. Note the lack of progress/recipe

### Expected Result

Succesful recipe parsing.

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/57987812/726019ad-7f87-49df-ac9d-edf38649b4df)
Note the lack of sequenced assembly category.

### Crash Report or Log

(omitted due to the above analysis)

### Operating System

Windows 10

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

### Other Mods

Quark 4.0-439
Quark Oddities 1.20.1
Zeta 1.0-14
(more: omitted)

**Comment by IThundxr** [comment]
Thanks, seems like i forgot to test this during implementation

**Comment by IThundxr** [comment]
Gonna leave this open for the translation part, will get to that soon
