### ISSUE TITLE
Train Can't Be Moved When Come In Contact With A Track Buffer

### ISSUE THREAD

**Issue by buny690** [Layers-of-Railways/Railway#424]
### Describe the Bug

Train can't be moved backwards when it comes in contact with a track buffer in high speed.

### Reproduction Steps

1.Drive a train really fast into a track buffer.
2.Try to back up.
3.Try to back up again after destroying the track buffer.
4.After backing up just a little bit, place the track buffer again.
...

### Expected Result

The train won't be able to move backwards in step 2 and 4. But it will be able to in step 3.

### Screenshots and Videos

https://github.com/Layers-of-Railways/Railway/assets/165518001/9da58588-9ccd-40c0-81cf-12080a6a7743

### Operating System

Windows 10

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

**Comment by techno-sam** [comment]
This is fixed by https://github.com/Layers-of-Railways/Railway/commit/4bcca4f2df9e4fa5f2931f9e4f05b982f8bb5982
