### ISSUE TITLE
Crash and/or hangup when attempting to open bogey menu

### ISSUE THREAD

**Issue by praecipitator** [Layers-of-Railways/Railway#426]
### Describe the Bug

Attempted to open the new Bogey menu using a train casing by holding left alt. Game crashed. 

### Reproduction Steps

1. Aquire a Train Casing block
2. Hold Block in hand
3. Press Left Alt
4. Observe hangup and/or crash

### Expected Result

Expected a screen of sorts to pop up, I guess.

### Crash Report or Log

https://pastebin.com/YdbzzzhT

### Operating System

Xubuntu 22.04.4 LTS

### Mod Version

1.6.0

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 0.15.7

### Other Mods

  [✔] amendments-1.20-1.1.14-fabric
  [✔] architectury-9.2.14-fabric
  [✔] badpackets-fabric-0.4.3
  [✔] bclib-3.0.14
  [✔] better-end-4.0.11
  [✔] better-nether-9.0.10
  [✔] betterarcheology-1.1.6-1.20.1
  [✔] bewitchment-1.20-8
  [✔] Botania-1.20.1-443-FABRIC
  [✔] cardinal-components-api-5.2.2
  [✔] chisel-1.6.1+1.20.1
  [✔] chunkloaders-1.2.8a-fabric-mc1.20.1
  [✔] cloth-config-11.1.118-fabric
  [✔] continuity-3.0.0-beta.4+1.20.1
  [✔] convenient-mobgriefing-2.1.0
  [✔] CraftTweaker-fabric-1.20.1-14.0.38
  [✔] create_jetpack-fabric-4.1.1.jar
  [✔] create_jetpack-fabric-4.2.0
  [✔] create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
  [✔] create-fabric-0.5.1-f-build.1417+mc1.20.1
  [✔] create-sodium-fix-0.5.1-d-build.1161+mc1.20.1.jar
  [✔] create-structures-0.1.1-1.20.1-FABRIC
  [✔] cristellib-1.1.5-fabric
  [✔] dawn-5.0.0
  [✔] deeperdarker-fabric-1.20-1.2.6
  [✔] delightful-creators-1.1.8
  [✔] DisableCustomWorldsAdvice-4.1
  [✔] disenchanter-0.1.8+1.20
  [✔] DungeonsArise-1.20.1-2.1.57-fabric-release
  [✔] EasierSleeping-1.20.1-2.1.3
  [✔] enderchests-fabric-1.20.1-1.2
  [✔] expandeddelight-0.3.0.3
  [✔] ExtendedDrawers-2.1.1+mc.1.20.1
  [✔] fabric-api-0.92.0+1.20.1
  [✔] fabric-language-kotlin-1.10.19+kotlin.1.9.23
  [✔] farmers-delight-fabric-1.4.3
  [✔] ferritecore-6.0.1-fabric
  [✔] geckolib-fabric-1.20.1-4.4.4
  [✔] gravestones-1.0.3-1.20.1
  [✔] immersive_aircraft-0.7.5+1.20.1-fabric
  [✔] indium-1.0.30+mc1.20.4
  [✔] iris-mc1.20.1-1.6.17
  [✔] ironchests-5.0.2-fabric
  [✔] justhammers-fabric-2.0.3+mc1.20.1
  [✔] lambdynamiclights-2.3.2+1.20.1
  [✔] LeavesBeGone-v8.0.0-1.20.1-Fabric
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] memoryleakfix-fabric-1.17+-1.1.5
  [✔] midnightlib-fabric-1.4.1.1
  [✔] modmenu-7.2.2
  [✔] moonlight-1.20-2.11.10-fabric
  [✔] more-geodes-1.9
  [✔] mousewheelie-1.13.0+mc1.20.1
  [✔] naturalist-fabric-4.0.3-1.20.1
  [✔] owo-lib-0.11.2+1.20
  [✔] Patchouli-1.20.1-84-FABRIC
  [✔] Pehkui-3.8.0+1.14.4-1.20.4
  [✔] pneumonocore-1.1.3+1.20.1
  [✔] PortableHole-v8.0.0-1.20.1-Fabric
  [✔] promenade-4.1.1
  [✔] PuzzlesLib-v8.1.18-1.20.1-Fabric
  [✔] RoughlyEnoughItems-12.0.684-fabric
  [✔] shetiphiancore-fabric-1.20.1-1.2
  [✔] sodium-fabric-0.5.8+mc1.20.1
  [✔] Steam_Rails-1.5.1+fabric-mc1.20.1.jar
  [✔] Steam_Rails-1.6.0+fabric-mc1.20.1
  [✔] supermartijn642configlib-1.1.8a-fabric-mc1.20
  [✔] supermartijn642corelib-1.1.17-fabric-mc1.20.1
  [✔] supplementaries-1.20-2.8.10-fabric
  [✔] tectonic-fabric-1.20-2.3.4
  [✔] TerraBlender-fabric-1.20.1-3.0.1.4
  [✔] Terralith_1.20.4_v2.4.11
  [✔] terrestria-6.0.13
  [✔] the_bumblezone-7.3.4+1.20.1-fabric
  [✔] The_Graveyard_3.1_(FABRIC)_for_1.20.1
  [✔] toms_storage_fabric-1.20-1.6.6
  [✔] Towns-and-Towers-1.12-Fabric+Forge
  [✔] travelersbackpack-fabric-1.20.1-9.1.11
  [✔] trinkets-3.7.2
  [✔] Truly-Modular-Archery-1.2-1.20.1-fabric
  [✔] Truly-Modular-armory-fabric-1.6-1.20.1
  [✔] Truly-Modular-arsenal-fabric-1.6-1.20.1.jar
  [✔] Truly-Modular-arsenal-fabric-1.7-1.20.1
  [✔] Truly-Modular-miapi-fabric-1.1.12-1.20.1.jar
  [✔] Truly-Modular-miapi-fabric-1.1.14-1.20.1
  [✔] wired-redstone-0.7.7+1.20.1
  [✔] wits-1.1.0+1.20.1-fabric
  [✔] wraith-harvestscythes-2.5.6+mc1.20
  [✔] wraith-waystones-3.3.2+mc1.20.1
  [✔] wthit-fabric-8.9.0
  [✔] Xaeros_Minimap_24.0.3_Fabric_1.20
  [✔] XaerosWorldMap_1.38.1_Fabric_1.20
  [✔] yet-another-config-lib-fabric-3.2.2+1.20
  [✔] YungsApi-1.20-Fabric-4.0.4
  [✔] YungsBetterDesertTemples-1.20-Fabric-3.0.3
  [✔] YungsBetterDungeons-1.20-Fabric-4.0.3
  [✔] YungsBetterJungleTemples-1.20-Fabric-2.0.4
  [✔] YungsBetterMineshafts-1.20-Fabric-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Fabric-2.0.6
  [✔] YungsBetterOceanMonuments-1.20-Fabric-3.0.4
  [✔] YungsBetterStrongholds-1.20-Fabric-4.0.3
  [✔] YungsBetterWitchHuts-1.20-Fabric-3.0.3
  [✔] YungsExtras-1.20-Fabric-4.0.3

### Additional Context

This is the java version in use:
```
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)
```

**Comment by IThundxr** [comment]
pneumonocore$getMigrated

https://github.com/PneumonoIsNotAvailable/PneumonoCore/blob/master/src/main/java/net/pneumono/pneumonocore/mixin/MigrationBlockMixin.java

This mod should be null checking identifier, it's marked as nullable and they should be checking that
