### ISSUE TITLE
Unknown entity appear after assemble the train on monorail track

### ISSUE THREAD

**Issue by feipangjun** [Layers-of-Railways/Railway#427]
### Describe the Bug

![2024-04-09_22 01 25](https://github.com/Layers-of-Railways/Railway/assets/93204475/ecce2328-9e92-4a6c-a42d-7f62049c470f)
![2024-04-09_22 10 45](https://github.com/Layers-of-Railways/Railway/assets/93204475/2aa2a1f2-3f20-4272-814c-2c3389df19ca)
Ummmmm..... It looks like a part of monorail bogey
This entity will go where players go after player had a distance between the train.
Maybe it is a little bit hard to describe for me. I've post a video below.

### Reproduction Steps

1.build a train on monorail track whatever the size is
2.assemble a train and the entity will appear

### Expected Result

this bug will be fixed

### Screenshots and Videos

![2024-04-09_22 01 25](https://github.com/Layers-of-Railways/Railway/assets/93204475/ecce2328-9e92-4a6c-a42d-7f62049c470f)
![2024-04-09_22 10 45](https://github.com/Layers-of-Railways/Railway/assets/93204475/2aa2a1f2-3f20-4272-814c-2c3389df19ca)

https://github.com/Layers-of-Railways/Railway/assets/93204475/acd338d0-6f0f-4823-b9ff-8814034ecf21

### Operating System

Windows 11

### Mod Version

1.6.0

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

fabric 0.15.7

### Other Mods

create 0.5.1f patch 1
fabric api 0.92

**Comment by IThundxr** [comment]
fixed in dev
