### ISSUE TITLE
I can't translate the mod

### ISSUE THREAD

**Issue by QuQuShKa1205** [Layers-of-Railways/Railway#432]
### Describe the Suggestion

On the mod version 1.5.3 forge text file en_us.yml looks normal. But on 1.6.1 forge looks strange :/.
Help pls

### Screenshots and Videos

1.5.3
https://github.com/Layers-of-Railways/Railway/assets/139057741/c61e65b6-bc37-4df3-ad78-70791d101831 steam n rails 

1.6.1
(https://github.com/Layers-of-Railways/Railway/assets/139057741/899d24e0-3024-42b6-bc91-806d96505808)

**Comment by goteusz-maszyk** [comment]
https://crowdin.com/project/create-steam-n-rails-official
