### ISSUE TITLE
Pondering the Conductors cap crashed

### ISSUE THREAD

**Issue by NoodlesNerd** [Layers-of-Railways/Railway#433]
### Describe the Bug

Pondering the Conductors Cap, specifically the second part of it, crashes the game.

### Reproduction Steps

1. Ponder the Conductors Cap
2. Go to the second part

### Expected Result

To Ponder the Robot

### Screenshots and Videos

![Steam RailsBug](https://github.com/Layers-of-Railways/Railway/assets/139659372/3c32602a-c434-46c7-83fb-dc5e727c9894)

### Operating System

Windows 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.2.7

### Other Mods

![Screenshot 2024-04-09 201941](https://github.com/Layers-of-Railways/Railway/assets/139659372/9446b41d-cac6-4f81-befc-ad8dc91c4c02)

**Comment by IThundxr** [comment]
attach the crash log
