### ISSUE TITLE
Crash on using Conductor Whistle via deployer.

### ISSUE THREAD

**Issue by KennonNichols** [Layers-of-Railways/Railway#437]
### Describe the Bug

When using an unbound Conductor Whistle on a train station via deployer, the game crashes. Error message: `Cannot invoke "net.minecraft.class_2487.method_25926(String)" because "stackTag" is null`.

### Reproduction Steps

1. Place train station.
2. Spawn in whistle.
3. DO NOT bind the whistle to a conductor.
4. Place whistle in deployer.
5. Make deployer use whistle on train station.

### Expected Result

It should summon the train, and not crash the game.

### Operating System

Windows 10

### Mod Version

1.6.0

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 0.92.0

**Comment by IThundxr** [comment]
Fixed in dev already, will be in 1.6.2
