### ISSUE TITLE
Trains with fuel dont seem to have extra speed alike to ones with solid fuel

### ISSUE THREAD

**Issue by ITMoxon** [Layers-of-Railways/Railway#439]
### Describe the Bug

when i have an engine with fuel in it, it doesn't seem to gain any extra speed than when i have an unpowered train.

### Reproduction Steps

1. Get 2 engines, 1 fueled on not
2. get schedules with them running same distance, departing at identical times
3. see when they arrive how they do it in the same time
...

### Expected Result

The fuel to not give any perks of powered trains

### Operating System

Windows 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.21

**Comment by James103** [comment]
What is the track length between the two stations you are testing? If it is less than 150 meters, there is not enough distance for there to be a noticeable difference between the unfueled train and the fueled train. Ideally the track length between two stations should be at least 300-500 meters, giving both trains time to accelerate to their full speeds before stopping.

**Comment by vivvyinks** [comment]
This is a known issue and will be addressed as soon as we get around to it

**Comment by ITMoxon** [comment]
After extension of the track length from 256 to 512 block, there is now result of extra speed on the engines, with the fueled ones finishing before the unfueled one.

**Comment by IThundxr** [comment]
Closing as not being a bug, seems trains take a bit of track to speed up to top powered speed
