### ISSUE TITLE
Game doesn't run when trying to add SnR as dependencies under dev environment

### ISSUE THREAD

**Issue by ghost** [Layers-of-Railways/Railway#441]
### Describe the Bug

When I use Minecraft Development (plugin of IntelliJ IDEA) to create a Minecraft Forge Mod Project and trying to add Steam'n Rails as dependencies, the game won't run after it starts.

### Reproduction Steps

1.Use Minecraft Development to creat a project (Forge 40.2.10);
2.Add Create 0.5.1f (terrag maven) and Steam'n Rails 1.4.8 (curse maven) as dependencies;
3.Build the Gradle;
4.Run Client.

### Expected Result

The game doesn't started as usual.

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/136866591/2f7fde33-7bb4-487a-a32a-7f0310ccaf7a)
This is what the screen displayed after getting started.

### Crash Report or Log

https://mclo.gs/xLOaRt7 (log) and https://mclo.gs/p3TC2Xw (crash report)

### Operating System

Windows 11

### Mod Version

1.4.8

### Create Mod Version

0.5.1f

### Minecraft Version

1.18.2

### ModLoader and Version

Forge 40.2.10

### Additional Context

Seems it's a problem about mixin

**Comment by techno-sam** [comment]
SnR 1.4.8 does not support Create 0.5.1f.

Additionally, we do not provide support for 1.18 versions anymore.
