### ISSUE TITLE
Crash upon opening alt bogie selector wheel

### ISSUE THREAD

**Issue by fluffyxox** [Layers-of-Railways/Railway#442]
### Describe the Bug

Crash upon opening alt bogie selector wheel.

### Reproduction Steps

1. Open bogie selector wheel.
2.
3.
...

### Expected Result

Being able to change bogie styles.

### Crash Report or Log

https://pastebin.com/P6GJw4m5

### Operating System

Windows 10

### Mod Version

1.5.3

### Create Mod Version

0.5.1d

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric 0.15.9

**Comment by IThundxr** [comment]
update pneumonocore
