### ISSUE TITLE
water as fuel

### ISSUE THREAD

**Issue by Ultratoster** [Layers-of-Railways/Railway#443]
### Describe the Suggestion

water **should** work as a fuel for trains

**Comment by IThundxr** [comment]
you can do this yourself with https://github.com/Layers-of-Railways/Railway/wiki/Registering-a-fluid-as-a-Liquid-Fuel-Type and trains running on just water would be super unrealistic for a feature that was meant to be realistic

**Comment by Ultratoster** [comment]
> you can do this yourself with https://github.com/Layers-of-Railways/Railway/wiki/Registering-a-fluid-as-a-Liquid-Fuel-Type and trains running on just water would be super unrealistic for a feature that was meant to be realistic

i thought that steam trains were working on water not on lava

**Comment by goteusz-maszyk** [comment]
Steam trains get heat from burned fuel such as coal and then this heat causes water to turn to steam and powers the train.
