### ISSUE TITLE
Can't rebind bogey menu key

### ISSUE THREAD

**Issue by PORTB** [Layers-of-Railways/Railway#444]
### Describe the Bug

I'm assuming this key is supposed to appear in the controls menu, but it doesn't. 
Hence the bogey menu key cannot be rebound, making it incompatible with effortless building's default menu key.

### Reproduction Steps

1. Install effortless building
2. Try to open the bogey menu without changing the radial menu from the left alt key

### Expected Result

The key should be rebindable.

### Operating System

linux

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

forge 

### Other Mods

Effortless building

**Comment by SpottyTheTurtle** [comment]
Known issue, will be fixed in the next update.
