### ISSUE TITLE
Optifine with Create Steam And Rails

### ISSUE THREAD

**Issue by BowlingBallcool** [Layers-of-Railways/Railway#445]
### Describe the Bug

When ever i want to play minecraft with optifine and steam and rails it comes up with an error. How do i fix this
![image_2024-04-13_165910859](https://github.com/Layers-of-Railways/Railway/assets/166901086/f43f98a1-39df-4484-93b9-a829096b6402)

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Fix ASAP!!

### Screenshots and Videos

![image_2024-04-13_165944392](https://github.com/Layers-of-Railways/Railway/assets/166901086/5868efc0-9908-46f8-900a-b19eab4e15fe)

### Crash Report or Log

no

### Operating System

Win 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

None

### Other Mods

optifine

### Additional Context

no

**Comment by Marshall2439** [comment]
Bruh this is dumb asf have you even read what ti says? Use rubidium/embeddium instead they are basically sodium for forge

**Comment by Marshall2439** [comment]
This isnt bug its just thwt optifine is unstable af

**Comment by IThundxr** [comment]
you are very definitely not on 1.6.1, since this was removed in 1.6.0
