### ISSUE TITLE
Buffers with headstock seem to have no recipe

### ISSUE THREAD

**Issue by PongoSapiens** [Layers-of-Railways/Railway#447]
### Describe the Bug

Buffers with headstock (or any of the variants) have no recipe hence track buffers can't be built.
Checked the source and I can't find a recipe there either.

### Reproduction Steps

1. Look in JEI for Buffer with headstock, click it, note lack of recipe.
2. Log in to github check recipes, note no recipe.

### Expected Result

I expected a recipe.

### Operating System

Windows 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

**Comment by IThundxr** [comment]
craft a link n pin and hold alt on it to pick variants

**Comment by zen-crab** [comment]
I'm also unable to build track buffers as they seem to have no recipe. I tried what @IThundxr suggested, but I don't see the headstock variant. ![Image](https://github.com/user-attachments/assets/607c6765-d982-40a6-a969-125e0949666d)
