### ISSUE TITLE
Documentation for liquid fuel type duration

### ISSUE THREAD

**Issue by goteusz-maszyk** [Layers-of-Railways/Railway#448]
This code says that default fuel duration is 400 ticks:
https://github.com/Layers-of-Railways/Railway/blob/65af5cd456ab08bfc2e199236b44176e86b3fb59/common/src/main/java/com/railwayteam/railways/content/fuel/LiquidFuelType.java#L22

However, the docs say, that it's 40:
https://github.com/Layers-of-Railways/Railway/blob/65af5cd456ab08bfc2e199236b44176e86b3fb59/.docs/Registering-a-fluid-as-a-Liquid-Fuel-Type.md?plain=1#L9

**Comment by James103** [comment]
Caused by https://github.com/Layers-of-Railways/Railway/pull/430. I was unable to make the change in that PR because it would get overwritten by the automatic merge of the wiki page contents onto the `.docs` folder.
