### ISSUE TITLE
Update crash world

### ISSUE THREAD

**Issue by GmanAtheist** [Layers-of-Railways/Railway#449]
### Describe the Bug

Updated from Steam_Rails-1.5.1+forge-mc1.19.2 to Steam_Rails-1.6.1+forge-mc1.19.2. Now my world crashes on world load. 
Forge 43.3.5. Please help. Thanks

### Reproduction Steps

1.
2.
3.
...
Just upgraded version

### Expected Result

Game crash on world load. Worked fine with Steam_Rails-1.5.1+forge-mc1.19.2. Crashing with Steam_Rails-1.6.1+forge-mc1.19.2..

### Crash Report or Log

http://www.gmanatheist2022.co.uk/MC%201-19-2%20crash%20report%20-Forge%2043-3-5.txt

### Operating System

Windows 10

### Mod Version

1.6.1

### Create Mod Version

0.5.1e

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.3.5

### Other Mods

Name                                               
---------------------------------------------------
(1.19.2) Realism Vehicle v0.1.jar                  
1.19.2-posture.jar                                 
AdChimneys-1.19.2-9.1.11.0-build.0897.jar          
AdditionalEnchantedMiner-1.19.2-1192.3.48.jar      
additionalredstone-1.19-1.0.4.jar                  
ad_astra-forge-1.19.2-1.12.6.jar                   
aether-1.19.2-1.3.1-forge.jar                      
alexsmobs-1.21.1.jar                               
angelblockrenewed-forge-1.0-1.19.jar               
appliedenergistics2-forge-12.9.5.jar               
architectury-6.5.85-forge.jar                      
automobility-0.4.2+1.19.2-forge.jar                
AutoRegLib-1.8.2-55.jar                            
backpacked-forge-1.19.2-2.1.13.jar                 
badpackets-forge-0.2.1.jar                         
balm-forge-1.19.2-4.5.7.jar                        
Better Mob Griefing Control-Forge-1.19.2-2.2.1.jar 
betterminecarts-1.19.2-1.6.3-43.1.3.jar            
blueprint-1.19.2-6.2.0.jar                         
Bookshelf-Forge-1.19.2-16.3.20.jar                 
botarium-forge-1.19.2-1.9.0.jar                    
buildersaddition-1.19.2-20220926a.jar              
BuildingWands-mc1.19.2-2.6.8-release-forge.jar     
BuildPasteMod-1.19.2v1.9.5x.jar                    
car-1.19.2-1.0.4.jar                               
carryon-forge-1.19.2-2.0.5.17.jar                  
catalogue-1.7.0-1.19.2.jar                         
CBandB-1.6v1.19.2FORGE.jar                         
CBMultipart-1.19.2-3.2.0.139-universal.jar         
cfm-7.0.0-pre35-1.19.2.jar                         
cgm-forge-1.19.2-1.3.7.jar                         
ChickenDropFeathersMod-forge-2.0.0-rc.1-1.19.2.jar 
chipped-forge-1.19.2-2.1.5.jar                     
chisels-and-bits-forge-1.3.142.jar                 
chisel_chipped_integration_v1.0.1_1.19.2.jar       
chunkloaders-1.2.7-forge-mc1.19.jar                
citadel-2.1.3-1.19.jar                             
cloth-config-8.3.103-forge.jar                     
Cloud-1.0.0-1.19.2.jar                             
CodeChickenLib-1.19.2-4.3.2.490-universal.jar      
ColossalChests-1.19.2-1.9.0.jar                    
compressedcreativity-1.19.2-0.1.8.jar              
configured-2.1.1-1.19.2.jar                        
Controlling-forge-1.19.2-10.0+7.jar                
copycats-1.1.0-mc1.19.2-all.jar                    
CosmeticArmorReworked-1.19.2-v1a.jar               
Create+Train+Additions+0.3.0-1.19.2.jar            
create-1.19.2-0.5.1.e.jar                          
create-new-age-forge-1.19.2-1.1.2.jar              
createaddition-1.19.2-20230623a.jar                
createchunkloading-1.5.0-forge (1).jar             
createdieselgenerators-1.19.2-1.1c.jar             
createindustry-0.7.0b-1.19.2.jar                   
createliquidfuel-2.1.1-1.19.2.jar                  
createutilities-0.1.4+1.19.2.jar                   
create_connected-0.7.4-mc1.19.2-all.jar            
create_mechanical_spawner-1.19.2-0.0.14.e-44.jar   
create_villagerology-1.19.2.jar                    
creatingspace-1.19.2-1.3.1.jar                     
CTM-1.19.2-1.1.6+8.jar                             
curios-forge-1.19.2-5.1.6.0.jar                    
customcompost-1.0.0-1.19.jar                       
Cyclic-1.19.2-1.8.0.jar                            
CyclopsCore-1.19.2-1.19.0.jar                      
DarkUtilities-Forge-1.19.2-13.1.9.jar              
Decorative+Blocks-forge-1.19.2-3.0.0.jar           
Deep Dark Dimension 2.0.1 43.2.0 1.19.2.jar        
design_decor-0.3-1.19.2.jar                        
DiagonalFences-v4.2.6-1.19.2-Forge.jar             
DramaticDoors-Forge-1.19.2-2.1.3.jar               
dynamicvillage-v0.3-1.19.2.jar                     
elevatorid-1.19.2-1.8.9.jar                        
endercrop-1.19.2-1.7.0-beta.jar                    
engineersdecor-1.19.2-forge-1.3.29.jar             
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar    
eureka-1192-1.2.0-beta.1.jar                       
ExtremeReactors2-1.19.2-2.0.55.jar                 
Fallingleaves-1.19.1-1.3.1.jar                     
FastLeafDecay-30.jar                               
ferritecore-5.0.3-forge.jar                        
flib-1.19.2-0.0.3.jar                              
ForgeEndertech-1.19.2-10.0.6.1-build.0897.jar      
FPS-Monitor-1.19.2-1.3.0.jar                       
framework-forge-1.19.2-0.6.16.jar                  
furnitureexpanded-1.19.2-1.1.jar                   
gates-1.8.0.jar                                    
geckolib-forge-1.19-3.1.40.jar                     
guardvillagers-1.19.2-1.5.7.jar                    
HammerLib-1.19.2-19.3.76.jar                       
ImmersiveEngineering-1.19.2-9.2.2-165.jar          
immersive_aircraft-0.7.5+1.19.2-forge.jar          
incubation-1.19.2-3.0.1.jar                        
industrial-foregoing-1.19.2-3.3.2.3-5.jar          
infinitybuttons-1.19.2-3.1.0.jar                   
instantblocks-forge-1.19.2-1.6.5.jar               
interiors-0.5.2+mc1.19.2-FORGE.jar                 
inzheFoPCore-v.4.0.0-1.19.2.jar                    
ironchest-1.19.2-14.2.7.jar                        
itemcollectors-1.1.9-forge-mc1.19.jar              
Jade-1.19.1-forge-8.8.1.jar                        
jei-1.19.2-forge-11.6.0.1019.jar                   
jnblock2024.jar                                    
jnblocks2024-2.jar                                 
journeymap-1.19.2-5.9.8-forge.jar                  
kotlinforforge-3.12.0-all.jar                      
lios_overhauled_villages-0.0.1-1.19.2.jar          
liquidburner-1.19.2-0.4.jar                        
littlelogistics-mc1.19.2-v1.4.0.jar                
MagnumTorch-v4.2.3-1.19.2-Forge.jar                
man_of_many_planes-0.0.3+1.19.2-forge.jar          
mattertransporter-1.2-1.19.2.jar                   
MCBE 1.14.jar                                      
mcjtylib-1.19-7.2.5.jar                            
mcw-bridges-2.1.0-mc1.19.2forge.jar                
mcw-doors-1.1.0forge-mc1.19.2.jar                  
mcw-fences-1.1.1-mc1.19.2forge.jar                 
mcw-furniture-3.2.2-mc1.19.2forge.jar              
mcw-lights-1.0.6-mc1.19.2forge.jar                 
mcw-paths-1.0.4forge-mc1.19.2.jar                  
mcw-roofs-2.3.0-mc1.19.2forge.jar                  
Measurements-forge-1.19.2-1.3.1.jar                
Mekanism-1.19.2-10.3.9.13.jar                      
memoryleakfix-forge-1.17+-1.1.1.jar                
minecraft-comes-alive-7.5.3+1.19.2-universal.jar   
miningdimension-1.1.jar                            
MMCooking-1.19.2-1.0.1.jar                         
MMFarming-1.19.2-1.1.0.jar                         
MMGrinding-1.19.2-1.2.0.jar                        
MMMining-1.19.2-1.1.jar                            
MobCapturingTool-forge-1.19-2.0.2.jar              
modernfix-forge-5.15.0+mc1.19.2.jar                
modular-routers-1.19.2-10.2.0-3.jar                
moonlight-1.19.2-2.3.6-forge.jar                   
moreminecarts-1.5.7.jar                            
MoreUtilities_1.0.0_1-19-2.jar                     
more_ships_1.19.2_4.1.jar                          
movingelevators-1.4.3-forge-mc1.19.jar             
MyBlocksJGN(MC1.12.2).jar                          
NaturalDecorMod_1.19.2_V1.0.jar                    
NellBlocks2.jar                                    
NellBlocks3.jar                                    
NetherChested-v4.0.4-1.19.2-Forge.jar              
nifty-1.27.2.jar                                   
nightvision command(1.19.2) v1.0.0.jar             
obscure_api-15.jar                                 
oculus-mc1.19.2-1.6.9.jar                          
pamhc2crops-1.19.2-1.0.2.jar                       
pamhc2trees-1.19.2-1.0.1.jar                       
Patchouli-1.19.2-77.jar                            
PigPen-Forge-1.19.2-11.1.2.jar                     
pipez-1.19.2-1.2.5.jar                             
plonk-1.19.2-10.0.4.jar                            
pneumaticcraft-repressurized-1.19.2-4.3.14-49.jar  
prefab-1.9.2.5.jar                                 
productivevillagers-1.0.3.jar                      
ProjectRed-1.19.2-4.17.0-beta+13-core.jar          
ProjectRed-1.19.2-4.17.0-beta+13-expansion.jar     
ProjectRed-1.19.2-4.17.0-beta+13-exploration.jar   
ProjectRed-1.19.2-4.17.0-beta+13-integration.jar   
ProjectRed-1.19.2-4.17.0-beta+13-transmission.jar  
ProjectRed-1.19.2-4.17.0-beta+8-core.jar           
PuzzlesLib-v4.4.3-1.19.2-Forge.jar                 
Quark-3.4-418.jar                                  
QuarkOddities-1.18.jar                             
Re-Avaritia-forged-1.19.2-1.3.3.jar                
Redstone-Pen-Mod-Forge-1.19.2.jar                  
RedstoneExtras-1.19-1.0.9.jar                      
redstone_clock-1.0-1.19-1.19.2.jar                 
red_power-1.1.jar                                  
refinedstorage-1.11.6.jar                          
resourcefulconfig-forge-1.19.2-1.0.20.jar          
resourcefullib-forge-1.19.2-1.1.24.jar             
rftoolsbase-1.19-4.1.7.jar                         
rftoolsutility-1.19-5.1.8.jar                      
rsgauges-1.19.2-forge-1.2.19.jar                   
RSInfinityBooster-1.19.2-3.0+27.jar                
rubidium-mc1.19.2-0.6.2c.jar                       
Runelic-Forge-1.19.2-14.1.4.jar                    
ScalableCatsForce-2.13.10-build-10-with-library.jar
Searchables-forge-1.19.2-1.0.2.jar                 
smarterfarmers-1.19.2-1.7.1.jar                    
SolarFluxReborn-1.19.2-19.3.10.jar                 
sootychimneys-1.19.2-1.1.1.jar                     
sophisticatedbackpacks-1.19.2-3.18.53.868.jar      
sophisticatedcore-1.19.2-0.5.78.358.jar            
SpikySpikes-v4.0.8-1.19.2-Forge.jar                
Steam_Rails-1.6.1+forge-mc1.19.2.jar               
supermartijn642configlib-1.1.7-forge-mc1.19.jar    
supermartijn642corelib-1.1.10-forge-mc1.19.2.jar   
supplementaries-1.19.2-2.4.20.jar                  
SWPlanets-forge-1.19.2-1.0.6.4.jar                 
tanukidecor-19.2.0.0.jar                           
theoneprobe-1.19-6.2.2.jar                         
titanium-1.19.2-3.7.3-27.jar                       
torojimaBuildHelper-3.6.0.0.jar                    
Traffic_Plus_1.4.0_1.19.2.jar                      
trainperspectivefix-1.0.0-universal.jar            
travelersbackpack-forge-1.19.2-8.2.39.jar          
vacuumchest-4.0.0-1.19.2.jar                       
valkyrienskies-1192-2.2.0-beta.2.jar               
villagertools-1.19-1.0.3.jar                       
vintageimprovements-1.19.2-0.1.1.1.jar             
waystones-forge-1.19.2-11.4.0.jar                  
workers-1.19.2-1.7.7.jar                           
worldedit-mod-7.2.12.jar                           
wormhole-1.1.13-forge-mc1.19.jar                   
wthit-forge-5.16.2.jar                             
ZeroCore2-1.19-2.1.26.jar                          
[1.19.2]+SecurityCraft+v1.9.6.1.jar                
[CS] Library-2.0.3-1.19.2.jar                      
[CS] Roleplay-1.0.7-1.19.2-[First Update].jar      
---------------------------------------------------
211 Files - 408.088 MB

**Comment by ortiofio** [comment]
Update Create to 5.1 F patch. 5.1 E is incompatible with SNR 1.6+

**Comment by GmanAtheist** [comment]
> Update Create to 5.1 F patch. 5.1 E is incompatible with SNR 1.6+

Create update also crash world.  :/  create-1.19.2-0.5.1.e works fine with  Steam_Rails-1.5.1+forge-mc1.19.2 . But create-1.19.2-0.5.1.f crash, as well as Steam_Rails-1.6.1+forge-mc1.19.2. Would hate to lose my world.  Thanks for the reply.

**Comment by GmanAtheist** [comment]
@ortiofio  > Update Create to 5.1 F patch. 5.1 E is incompatible with SNR 1.6+

AH!. All good for now. Updated Forge, Java and started a new world. All worked fine with updated Steam and rails and latest create. Then left world and loaded old world again. It loaded and seem to be working. Thanks for your help. :-)
