### ISSUE TITLE
Steam 'n Rails tracks are the same color as normal train tracks in maps

### ISSUE THREAD

**Issue by Ch1216** [Layers-of-Railways/Railway#45]
![stmeanasrisamfwahu](https://user-images.githubusercontent.com/68875386/212195488-ff490a86-fc79-4535-9134-bd216b4684fa.png)
Reported this because the track marker for maps/fake track blocks don't match their regular track color in journeymap specially with steam n rails tracks

**Comment by IThundxr** [comment]
This is a Minecraft limitation iirc since the maps colours are based off the material property

Closing
