### ISSUE TITLE
Crash after moving a train through the portal - Entity has invalid position

### ISSUE THREAD

**Issue by McPersson** [Layers-of-Railways/Railway#450]
### Describe the Bug

It's pretty simple. A train was built in the Nether, loaded with lava and travelled through a portal to the overworld. After the player went to the overworld to check the train, the server crashed. 

Crashes every time the player goes into that area. Even when deleting chunks, nothing changes. 

### Reproduction Steps

1. Make a train
2. Load the train with lava
3. Let what through the portal
4. PROFIT

### Expected Result

^

### Crash Report or Log

https://mclo.gs/WOKwL1J

### Operating System

Windows 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.21

### Other Mods

There are quite a few of them. You can look at the end of the crash report.

**Comment by IThundxr** [comment]
This has happened with just create aswell for a few people, not a steam 'n' rails issue

**Comment by McPersson** [comment]
> This has happened with just create aswell for a few people, not a steam 'n' rails issue

When I turned off "Create: Steam 'n' Rails" it was fine. As soon as I activate it, it crashes.  ╮(￣ω￣;)╭
Can't seem to play with this mod due to some error. Eeeh.

**Comment by IThundxr** [comment]
Unless you can reproduce it with a minimal amount of mods, this is likely not caused by us, you've got tons of mods alongside connector meaning it could be anything here but it's likely just create
