### ISSUE TITLE
Missing buffer Pole

### ISSUE THREAD

**Issue by Zanman06** [Layers-of-Railways/Railway#452]
### Describe the Bug

Narrow single buffer is missing a pole on the right side, tested on 2 pc's with embeddium installed

### Reproduction Steps

1. place down a couple of pieces of narrow track
2. place a track buffer
3. cycle to

### Expected Result

Both poles to be rendered

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/Railway/assets/112818823/90b168ba-034a-4d67-af64-3b9e82fbcc3f)
![image](https://github.com/Layers-of-Railways/Railway/assets/112818823/a6428537-aa49-46fa-9e44-dc11eafb9f8b)

### Operating System

Windows 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.23

**Comment by IThundxr** [comment]
fixed in dev
