### ISSUE TITLE
It Keeps Crashing Minecraft

### ISSUE THREAD

**Issue by ashvant-sunish** [Layers-of-Railways/Railway#453]
Hi,

 I am using Minecraft Forge 1.18.2(Forge 40.2.17) and create 0.5.1e (Using Tlauncher). I added this mod to the file and run on the beginning it runs with no issues but when i tried to assemble the train using train station minecraft is crashing . After some more times minecraft didnt even opening. Can anyone help me.

I dont know whats the issue

ERROR MESSAGE:

Minecraft did not start due to an unknown error! Probably it happened for your mods, try to delete it or read below  You have installed mods. We advise you to assemble your assembly using our mod-pack system [link ](https://tlauncher.org/en/news_26/modpack-system_5100.html).  How it helps!  1) If the game breaks (crashes) with your mods, then turn off all the mods (click on the green box to the right of the installed mod) and launch the launcher (to make sure that the empty build works ), then activate (click on the gray box) a few pieces or one and start the game, so you will understand at what point the problem arises. 2) Make backups of your working assemblies. 3) Send your friends with builds.  For a more precise definition, the Use the following guidelines for working with the console: [https://tlauncher.org/en/error-start-minecraft.html ](https://tlauncher.org/en/error-start-minecraft.html)  If all else fails, then write to our group for help via the link https://vk.com/tlauncher

**Comment by IThundxr** [comment]
we don't support tlauncher
