### ISSUE TITLE
When ticking the "Limit Station" tickbox, the description text gets stuck to the cursor

### ISSUE THREAD

**Issue by SabrCat** [Layers-of-Railways/Railway#454]
### Describe the Bug

See Title and Video

### Reproduction Steps

1. Place a station (bound to a track)
2. Open the UI
3. Click on the tickbox to limit the station
4. The text box describing what said box does will get stuck on the cursor until the UI is closed

### Expected Result

The text box should disappear when the tickbox is not hovered.

### Screenshots and Videos

https://github.com/Layers-of-Railways/Railway/assets/56313836/7f6069e6-4643-48a7-841b-997ff9fa8b1e

### Operating System

Windows 10

### Mod Version

1.6.0

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric Loader 0.15.10 / API 0.92.1

### Other Mods

none

**Comment by IThundxr** [comment]
cannot reproduce with snr + create
