### ISSUE TITLE
The problem of semi-block textures with rails (optifine)

### ISSUE THREAD

**Issue by UnclePhonk** [Layers-of-Railways/Railway#456]
### Describe the Bug

I am sincerely grateful to you for the support of optifine. But I think it's worth telling you about the errors to make it easier for you to catch bugs.
When you press on the rails with a semi-block, the textures of these same semi-blocks fly off the rails, I observed this problem a long time ago on the "fabric" version of the mod. This can be fixed if you switch to "Rubidium Extra". But there are even more unpleasant problems there.
I use shaders because I want to see my locomotives ride in an incredibly beautiful world.

### Reproduction Steps

1.Put the rails at a 90 degree angle
2.Take the semi-blocks and click on the rails
3.
...

### Expected Result

I expect the correct display of the texture of the semi-blocks on the rotating rails

### Screenshots and Videos

![Снимок экрана 2024-04-19 101216](https://github.com/Layers-of-Railways/Railway/assets/110298407/a68f79af-60a7-405e-b603-0e30a3602f04)
![Снимок экрана 2024-04-19 101254](https://github.com/Layers-of-Railways/Railway/assets/110298407/a4ff9bc4-47b5-4d23-8b86-89fb88856443)

I inserted screenshots from old versions of the mod, but the problem is relevant.

### Operating System

Windows 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge (The latest version)

### Other Mods

Create, optifine

**Comment by ortiofio** [comment]
From what I know, Optifine is not supported. Use Embeddium + Oculus to use shaders

**Comment by UnclePhonk** [comment]
Optifine is now supported. (Since version 1.6). Embeddium + Oculus - this bundle really works, but it causes (personally for me) here's a bug: when I pick up an object next to a windmill or next to an already assembled train, the textures of these objects seem to be reloaded. It looks like it lies on its side for a split second and returns to its original position. It hurts my eyes from this, I'm looking for a solution.

**Comment by IThundxr** [comment]
try `/snrc clear_casing_cache`

optifine is still unsupported, you are on your own with any issues that occur when using it due to how invasive it is, all 1.6.x changed was fixing the crash on 1.19 and removing the warning screen since many people made bug reports of it even though it isn't a bug.

**Comment by UnclePhonk** [comment]
The team did not help, but the mod helped: "Iris & Oculus Flywheel Compat". He fixed everything.
