### ISSUE TITLE
Dynamic glow of train lights

### ISSUE THREAD

**Issue by UnclePhonk** [Layers-of-Railways/Railway#457]
### Describe the Bug

After the train is assembled, the outdoor lights (blocks or torches) stop emitting light. This may not be provided, but please, if someone knows the solution / mod / settings parameter, tell us how to achieve a dynamic glow of the train lights.

### Reproduction Steps

1.a
2.a
3.a
...

### Expected Result

The beautiful glow of the train's exterior lights at night. (playing with shaders)

### Operating System

Windows 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge (The latest version)

### Other Mods

- radium (optimization)

- ferrite core (optimization)

- entity culling (optimization)

- Iris & Oculus Flywheel Compatible (shader fix)

- Embedding (fork of Sodium)

- oculus (shaders support)

- create

- Create: Steam 'n' Rails

**Comment by techno-sam** [comment]
this is a Create issue.
