### ISSUE TITLE
[Suggestion] More track gauges beside Standard Gauge

### ISSUE THREAD

**Issue by Quizer9O8** [Layers-of-Railways/Railway#46]
Adding Narrow Gauge, Wide Gauge and Dual Gauge in **Create: Steam 'n Rails** would make the mod stand out more. 
By including different gauge options, players would have more flexibility in creating and designing their own rail networks, which would make the game more engaging and interesting for players.

Additionally, including narrow gauge, wide gauge and dual gauge options would also increase the creativity and replayability of the mod as players could create different and unique rail networks each time they play, which would keep the game fresh and exciting.

Overall, including Narrow Gauge, Wide Gauge and Dual Gauge options would greatly enhance the ingenuity and replayability of the game.

**Comment by stacode123** [comment]
already suggested i recommend using discord :D

**Comment by IThundxr** [comment]
Finished in dev will release with 1.5.0
