### ISSUE TITLE
Track buffers locking the trains.

### ISSUE THREAD

**Issue by RandomPersonLearningHTML** [Layers-of-Railways/Railway#460]
### Describe the Bug

When approaching an track buffer the train comes to a stop, as it should. But most of the time it get's stuck until the buffer is removed. It can't go forwards or backwards and is, like I said, stuck in position. I used mod version 1.6.3, I had to attach this here as it isn't an option in the box "Mod Version".

### Reproduction Steps

1. Approach the buffer.
2. Switch directions.
3. Watch as the train won't move at all.

### Expected Result

Normally, I think you are supposed to be able to turn around and go in the other direction once you stop the buffer, which blocks you from moving further to the end of the track.

### Screenshots and Videos

![Screenshot 2024-04-20 223032](https://github.com/Layers-of-Railways/Railway/assets/167677909/ebaed805-7f46-4134-8cfa-953484a514f6)

### Operating System

Windows 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 1.250.0

### Other Mods

![image](https://github.com/Layers-of-Railways/Railway/assets/167677909/08197ca7-e2ee-4eac-957c-224be49a22ee)

**Comment by IThundxr** [comment]
fixed already
