### ISSUE TITLE
Locometal boiler face disappears

### ISSUE THREAD

**Issue by MiloMiko** [Layers-of-Railways/Railway#464]
### Describe the Bug

When i was building a train with the new boliers (i really like them) i placed a block in front (a locometal boiled to be exact) and the entire boiler face disappeared.

Here is before placing the block:

![Zrzut ekranu 2024-04-24 170333](https://github.com/Layers-of-Railways/Railway/assets/161062432/15302296-8edc-4dc3-bf4e-00a5412fa605)

And here is after:

![Zrzut ekranu 2024-04-24 170340](https://github.com/Layers-of-Railways/Railway/assets/161062432/432276aa-04af-4f4e-b4b4-869d7074a1e3)

Please fix this, because i really want to create a normal train with a boiler face showning normally

### Reproduction Steps

1.Boot up minecraft with create and create: steam 'n' rails
2.Place a locometal boiler (any)
3.Place a random full block (not tested with not full ones)
Result: The boiler face dissapeared and you can see through it

### Expected Result

Bolier face should show up normally.

### Screenshots and Videos

Here is before placing the block:

![Zrzut ekranu 2024-04-24 170333](https://github.com/Layers-of-Railways/Railway/assets/161062432/a7d90355-934f-49d0-b948-3841b908a4d7)

And here is after:

![Zrzut ekranu 2024-04-24 170340](https://github.com/Layers-of-Railways/Railway/assets/161062432/c3e02d7e-de3f-4db7-9347-69155263aea6)

### Crash Report or Log

Sorry. It happened in-game and i dodn't paste it here because i did not know if it would be heplful and i don't know where it is.

### Operating System

Windows 11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.3.2

### Other Mods

I can't it's too much (137)

### Additional Context

IMPORTANT: I have steam 'n' rails 1.6.2+forge-mc1.19.2 not 1.6.1

**Comment by IThundxr** [comment]
attach latest.log

**Comment by Nemirel345** [comment]
This looks like a problem with culling the model. Maybe the face is set to cull if a solid block is placed obstructing the centre face of the boiler block. if it's not an issue with the model itself you may have an optimization mod which culls obstructed faces, and it's trying to cull the boiler even though it extends past the sides of the obstructed face.

**Comment by IThundxr** [comment]
it's likely caused by rubidium

**Comment by Nemirel345** [comment]
Can you confirm the model has those faces set to not cull?

**Comment by IThundxr** [comment]
> Can you confirm the model has those faces set to not cull?

forge's and by extension porting libs obj loader does not support culling properties
