### ISSUE TITLE
train not maikng and hand car*

### ISSUE THREAD

**Issue by kompor22** [Layers-of-Railways/Railway#465]
### Describe the Bug

i build the train but the train not spawn :( and no spwnd handal train *

### Reproduction Steps

1.buld train 
2.spawn
3.no train
...
*

### Expected Result

fix bug i wat play this mod:(*

### Screenshots and Videos

*

### Crash Report or Log

*

### Operating System

window 11*

### Mod Version

1.6.3

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

forge 47,2,20*

### Other Mods

botarium forge ,copycats forge, create mis and fings ,create,create new age,derocative blocks,dinamic tree,FarmersDelight,xareo's minimap ,just enought itms ,more mobs variant ,sophisticated backpacks ,sophisticatedcore.*

### Additional Context

no trains spawn and hand car*

**Comment by IThundxr** [comment]
1.6.x only supports 0.5.1-f
