### ISSUE TITLE
Train disappears after assembly. 

### ISSUE THREAD

**Issue by PossiblySlater** [Layers-of-Railways/Railway#467]
### Describe the Bug

When I build a simple train with only a seat and controls and click the assemble button, the train disappears. The station also does not exit the new train menu.

### Reproduction Steps

1. place a length of track
2. place a train station
3. build a train
4. click assemble

### Expected Result

The train assembles and works properly.

### Operating System

Windows 11

### Mod Version

1.6.3

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

### Other Mods

- Create
- Just Enough Items
- Steam N' Rails

**Comment by IThundxr** [comment]
update create to 0.5.1-f
