### ISSUE TITLE
train coupling has weird directionality

### ISSUE THREAD

**Issue by henryyuyhy** [Layers-of-Railways/Railway#468]
### Describe the Bug

two trains can only be coupled when they are in the same direction, when i turn one train around they can't be coupled.
<img width="99" alt="无标题" src="https://github.com/Layers-of-Railways/Railway/assets/109945282/8fa5acbf-9832-475d-bfe1-32714792b94e">

### Reproduction Steps

shown in the video

### Expected Result

fix it

### Screenshots and Videos

https://github.com/Layers-of-Railways/Railway/assets/109945282/b11d8c5a-c8e5-48b6-82ce-fc6234a471e9

### Operating System

windows 11 (it doesn't matter)

### Mod Version

1.6.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

-

**Comment by techno-sam** [comment]
works as intended, it is not practical to 'rotate' the carriages
