### ISSUE TITLE
Server won't start after attempting to remove SpongeForge

### ISSUE THREAD

**Issue by baritonu** [Layers-of-Railways/Railway#469]
### Describe the Bug

I'm not sure if this is the right place to post this but my server won't start after I attempted to remove some old SpongeForge folders and files from the server since they're not being used. 

### Reproduction Steps

Removing the SpongeForge folder and starting up the server will give error message: Create: Steam 'n' Rails (railways) has failed to load correctly
java.lang.reflect.InvocationTargetException: null
Exception message: java.lang.IllegalArgumentException: No enum constant net.minecraft.world.entity.vehicle.AbstractMinecart.Type.RAILWAY_WORKBENCH

### Expected Result

Server starts with no issues

### Crash Report or Log

https://pastebin.com/PsLmCHB4

### Operating System

Windows 11

### Mod Version

1.6.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.1

### Other Mods

bellsandwhistles-0.4.3-1.20.x.jar
create_misc_and_things_+1.20.1_4.0A.jar
vtaw_tas-forge-1.20.1-1.1.2.jar
gourmet-0.1.1b-1.20.1.jar 
pamhc2trees-1.20-1.0.2.jar 
geckolib-forge-1.20.1-4.3.1.jar
jei-1.20.1-forge-15.2.0.23.jar
DoggyTalentsNext-1.20.1-1.17.5.jar
journeymap-1.20.1-5.9.11-forge.jar
TravelersBackpack-1.20.1-9.1.4.jar
lightmanscurrency-1.20.1-2.2.1.3b.jar
mixinextras-forge-0.3.5.jar
devices-0.8.1-forge.jar
create-confectionery1.20.1_v1.1.0.jar
Upcycle-1.20.x-(v.1.1.0).jar
mcw-doors-1.1.0forge-mc1.20.1.jar 
rotl-4.4-1.20.1-forge.jar
Steam_Rails-1.6.1+forge-mc1.20.1.jar
interiors-0.5-30+mc1.20.1.jar
rubidium_extras-1.20.1_v1.4.3.jar
cloth-config-11.1.118-forge.jar  
forge-1.20.1-47.1.30-universal.jar
paladin-furniture-mod-1.2.1-forge-mc1.20.1.jar
supplementaries-1.20-2.5.20.jar
embeddium-0.3.14+mc1.20.1.jar 
server-1.20.1-20230612.114412-srg.jar
mcw-bridges-2.1.1-mc1.20.1forge.jar
dragonlib-946163-5071843.jar 
create_villagerology-1.20.1-b.jar 
moonlight-1.20-2.6.3-forge.jar
pamhc2crops-1.20-1.0.2.jar 
mcw-fences-1.0.7-mc1.20.1forge.jar
supermartijn642corelib-1.1.9-forge-mc1.20.jar 
Simply-Light-Mod-Forge-1.20.1.jar 
pamhc2foodextended-1.20-1.0.0.jar  
flywheel-forge-1.20.1-0.6.10-7.jar
create-1.20.1-0.5.1.f.jar
pamhc2foodcore-1.20-1.0.0.jar 
FramedBlocks-9.2.2.jar
worldedit-mod-7.2.15.jar  
mcw-roofs-2.2.4-mc1.20.1forge.jar 
createrailwaysnavigator-0.4.0-beta-1.20.1.jar
cfm-forge-1.20.1-7.0.0-pre36.jar
nfm-2024.04.07-1.20.1.jar
architectury-9.1.12-forge.jar
otyacraftengine-forge-mc1.20-3.7.0-alpha.2.jar
doapi-1.2.6-forge.jar
letsdo-candlelight-forge-1.2.2.jar
letsdo-bakery-forge-1.1.2.jar
letsdo-vinery-forge-1.4.3.jar 
letsdo-beachparty-forge-1.1.1.jar
createsongsandspeakers-forge-mc1.20-0.5
Aquaculture-1.20.1-2.5.0.jar
trainperspectivefix-1.0.0-universal.jar
ExtraGems-1.20.x-(v.2.3.2).jar
mcw-lights-1.0.6-mc1.20.1forge.jar
Better_Dogs_X_Doggy_Talents_Next_v1.2[1.20-1.20.1]

**Comment by IThundxr** [comment]
try reinstalling forge

**Comment by baritonu** [comment]
Yes that worked, thank you!
