### ISSUE TITLE
Crash when upgrading to Create 0.5.0h

### ISSUE THREAD

**Issue by sciguyryan** [Layers-of-Railways/Railway#47]
Hi.

Upgrading to Create version 0.5.0h causes a crash with Steam 'n Rails (current version, 1.0.6) when attempting to load a world. I have attached a copy of the crash report to this bug report.

[crash-2023-01-16_16.07.58-client.txt](https://github.com/Layers-of-Railways/Railway/files/10427623/crash-2023-01-16_16.07.58-client.txt)

Cheers.

**Comment by soup587** [comment]
i think a patch earlier today was supposed to fix it but it seems to still occur

**Comment by techno-sam** [comment]
make sure you download the latest steam 'n rails on curseforge: (https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails/files/4357495)

**Comment by SpottyTheTurtle** [comment]
fixed in latest version.
