### ISSUE TITLE
Train assembly and handcar

### ISSUE THREAD

**Issue by Csukas** [Layers-of-Railways/Railway#476]
### Describe the Bug

When i pressed the assembly button in trainstation, insted of making it into a train it disappered. Also when i placed the handcar the game crashed. I dont have a strong PC but the version 1.5.1 works fine. 

### Reproduction Steps

1. Make a train like normal
2. Click assemble train
3. The train disappered and in train station the text just changed to 0 bogeys

### Expected Result

It should create a train that is drivable and visable. 

### Operating System

Win 10

### Mod Version

1.6.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.3.0

### Other Mods

I have find it while playing my modpack but the same thing happened when there was only create and steam 'n' rails.

**Comment by IThundxr** [comment]
update create to 0.5.1-f and use steam n rails 1.6.4

**Comment by Csukas** [comment]
> update create to 0.5.1-f and use steam n rails 1.6.4

Thank you for quick advice. I had creaye 0.5.1-e. Now it works. Btw i thing it is the best addon for create.
