### ISSUE TITLE
"Build Train" crashed

### ISSUE THREAD

**Issue by WaterFox117** [Layers-of-Railways/Railway#477]
### Describe the Bug

When I finish building a train (using strong glue correctly) and click the "Build Train" button, the game crashes and I can no longer join this server or world

### Reproduction Steps

1.building a train
2.click the "Build Train" button
3.game crashed

### Expected Result

The train is correctly assembled and the game will not crash

### Screenshots and Videos

![a3d072896a35df31aa580136f0430d77](https://github.com/Layers-of-Railways/Railway/assets/109254595/7e46121f-3968-4caa-bf60-cbd527b53a46)

### Crash Report or Log

https://api.mclo.gs/1/raw/QejY5Ib

### Operating System

windows11

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

forge 43.3.9

### Other Mods

Create: Extended Cogwheels

### Additional Context

![image](https://github.com/Layers-of-Railways/Railway/assets/109254595/0b11bbda-bc56-42f0-8cf1-7cbbea02d0ee)

**Comment by IThundxr** [comment]
kuayue has a bad mixin, they should be using stackable injectors from mixin extras
