### ISSUE TITLE
Trains get stuck when driving close to a buffer

### ISSUE THREAD

**Issue by ImagineerDave** [Layers-of-Railways/Railway#478]
### Describe the Bug

When driving a train near a buffer block the train gets stuck and no movement is possible. As soon as you remove the buffer block it reenables the train to drive again ; See video

### Reproduction Steps

1. Place a buffer on a traintrack
2. Get a train and drive it near the buffer
3. Train gets stuck
...

### Expected Result

Trains are drivable again near bufferblocks.

### Screenshots and Videos

https://www.twitch.tv/videos/2138135283

### Operating System

Windows 11

### Mod Version

1.6.0

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Fabric loader

**Comment by IThundxr** [comment]
fixed
