### ISSUE TITLE
Semaphore lights have visual bugs

### ISSUE THREAD

**Issue by curryducker** [Layers-of-Railways/Railway#48]
sometimes they look weird
![image](https://user-images.githubusercontent.com/66020230/213295856-a00b2b17-8e7a-4be9-9da3-e3258a820c24.png)
![image](https://user-images.githubusercontent.com/66020230/213296156-7cce9a4e-d23f-453e-98ab-5a8e88f997ef.png)

i can see through the rest of the block
![image](https://user-images.githubusercontent.com/66020230/213295865-4634d63d-2b6c-4597-b19a-69b39675319e.png)
![image](https://user-images.githubusercontent.com/66020230/213296079-c6f72745-78c2-465b-a697-cbf7a5f7cf6f.png)

**Comment by curryducker** [comment]
normal nixie tubes are fine and i'm not using optifine

Mod list:
![image](https://user-images.githubusercontent.com/66020230/213296518-6259df1f-cf0f-4ac3-847f-ebfc61c671a1.png)
![image](https://user-images.githubusercontent.com/66020230/213296545-96e46a24-cc95-409f-87bf-c32c2d16161a.png)

**Comment by stacode123** [comment]
I think thats intentional

**Comment by curryducker** [comment]
How would a visual change based on a random angle or x-raying through a block be intentional

**Comment by techno-sam** [comment]
Can you show normal nixie tubes being fine? The only thing they would x-ray would be their own block

**Comment by techno-sam** [comment]
Closed due to inactivity.

**Comment by curryducker** [comment]
don't know why i never saw that comment but here is a screenshot of a normal nixie tube
![image](https://user-images.githubusercontent.com/66020230/224564309-ce753a65-978a-447b-9a88-d6a9f2e36cbc.png)
i know the issue is closed but maybe it helps

**Comment by techno-sam** [comment]
If you look closely, you can see that you are still 'xraying' through the nixie tube. it is simply less obvious because the signal is visible. This is a vanilla minecraft transparency issue, and there is not much we can do to fix it

Edit: I thought maybe there could be something weird going on if nixie tubes indeed worked correctly, but they too have this bug. (On that note, please don't make an issue for this on the Create repository, there is nothing they can do either)

**Comment by curryducker** [comment]
Oh, you're right. I thought it was the bottom of the nixie tube but it is indeed the signal block. Is there something that can be done about the other bug though? (The weird look from some angles)
