### ISSUE TITLE
Relicense to LGPLv3

### ISSUE THREAD

**Issue by IThundxr** [Layers-of-Railways/Railway#481]
Steam 'n' Rails has been under MIT since the start, however with how much we've grown and how we've encountered issues with licensing before we are deciding on relicensing to LGPLv3, Below is a list of contributors who need to approve the relicense (LOC is in what currently exists in the project and not overall)

- [x] @IThundxr (661 commits, ~12k LOC)
- [x] @techno-sam (512 commits, ~35k LOC)
- [x] @TropheusJ (64 commits, ~4k LOC)
- [x] @SpottyTheTurtle (52 commits, ~1k LOC)
- [x] @Eriksonnaren (1 commit, 900 LOC)
- [x] @jenchanws (13 commits, ~800 LOC)
- [x] @talrey (63 commits, ~800 LOC)
- [x] @rhysdh540 (4 commits, ~300 LOC)
- [x] @jeremiahwinsley (5 commits, ~100 LOC)
- [x] @SFort (1 commit, 38 LOC)
- [x] @Szedann (18 commits, 35 LOC)
- [x] @kotakotik22 (147 commits, 20 LOC)
- [x] @kurocat471 (2 commits, 19 LOC)
- [x] @LordGrimmauld (4 commits, 18 LOC)
- [x] @cvrunmin (1 commit, 3 LOC)
- [x] @James103 (1 commit, 3 LOC)

To approve the relicense everyone listed above should comment on this issue with "I, <yourname/username> give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms."

If you have any questions or concerns feel free to leave them in the comments or email me at me@ithundxr.dev

**Comment by rhysdh540** [comment]
there's no way that's 300 LOC but ok 👍

I, @rhysdh540, give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by LordGrimmauld** [comment]
Funny how i am still in git blame despite the codebase being thoroughly replaced ever since i put my hands on essentially setting up a glorified example mod XD

I, @LordGrimmauld, give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by SFort** [comment]
I, SFort give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by jeremiahwinsley** [comment]
I, @jeremiahwinsley, give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by Eriksonnaren** [comment]
I, @Eriksonnaren  give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by SpottyTheTurtle** [comment]
I, @SpottyTheTurtle, give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by James103** [comment]
I, @James103, give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by techno-sam** [comment]
I, @techno-sam give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by cvrunmin** [comment]
How come I still have 3 LOC :joy: 

I, cvrunmin, give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by kurocat471** [comment]
I, @kurocat471, give The Railways Team / Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by Szedann** [comment]
I, @Szedann give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by kotakotik22** [comment]
I, @kotakotik22 give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by talrey** [comment]
I, @talrey, give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by TropheusJ** [comment]
I, @TropheusJ, give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by jenchanws** [comment]
I, @jenchanws, give The Railways Team/Steam 'n' Rails irrevocable permission without exceptions to relicense my contributions to Steam 'n' Rails under LGPLv3 and its terms.

**Comment by IThundxr** [comment]
Completed in https://github.com/Layers-of-Railways/Railway/commit/fec03856808f213086371b78887925f544498d83
