### ISSUE TITLE
Journey integration not working

### ISSUE THREAD

**Issue by Aiq0** [Layers-of-Railways/Railway#482]
### Describe the Bug

Journey map integration is not working, no train markers are shown, neither Loaded JourneyMap plugin message is printed in log

### Reproduction Steps

1. Install JourneyMap and Create Steam n'Rails
3. Build some train
4. Open JourneyMap and try to look at trains, none are present

### Expected Result

Trains shown on map.

### Operating System

Ubuntu 22.04

### Mod Version

1.6.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

fabric-1.20.1-0.15.11

### Additional Context

I fixed it by editing modid of journeymap to journeymap and not journeymap-fabric, which I found only in some old 1.18.2 versions here: https://github.com/Layers-of-Railways/Railway/blob/a9c753ad5736b0b13f13317d99c931b3c3fe6ff0/common/src/main/java/com/railwayteam/railways/compat/Mods.java#L14

Also, after fixing, obsolete timer is not working correctly, it just clears all trains and waits for them to reappear. It could be fixed by remembering number of last tick the train was updated (by train UUID), and only deleting trains that were ticked more than x tick back, so obsolete trains would be removed, but updated trains would stay.

Also, it would be more nice if markers would also show train direction - eg. yaw of first bogey would be sent in MarkerPacket and icon would be changed to some kind of arrow or just have some kind of pointing and then using rotation of MapIcon of journey map plugin.

Another also, destination is sended in packet but not shown in marker details...

P.S.: I only discovered that there is some kind of JourneyMap integration by looking at source code, so maybe it would be nice to mention it somewhere (at least in changelog when this will be fixed)

**Comment by cai-tan** [comment]
+1 also not working in barebones install, Windows 10, Fabric 1.20.1

**Comment by IThundxr** [comment]
fixed in dev
