### ISSUE TITLE
Use Blockstates for Coloring LocoMetal to reduce amount of registered blocks

### ISSUE THREAD

**Issue by LopyLuna** [Layers-of-Railways/Railway#483]
### Describe the Suggestion

Similar to sails for applying color onto the locoMetal

This More of Issue & Suggestion at the same time

from https://discord.com/channels/706277846389227612/1243987403065266207

**Comment by techno-sam** [comment]
No. This follows the pattern of wool, concrete, terracotta, etc - different blocks get different blocks.
There is no significant internal difference between registering 16 single-state blocks and registering one 16-state block.

**Comment by LopyLuna** [comment]
I just don't wanna deal with the massive clutter of Loco metal

**Comment by LopyLuna** [comment]
Atleast add a config to make it not register on load up

**Comment by SpottyTheTurtle** [comment]
Dynamic registration isn't done generally for a very good reason

**Comment by IThundxr** [comment]
the most that could be done is a config to disable the creative tab for them and them showing up in jei but anything further wouldn't likely happen

**Comment by VladisCrafter** [comment]
How would it deal with copycats then?
