### ISSUE TITLE
Game crashes on launch with mod installed

### ISSUE THREAD

**Issue by HighInPotassium** [Layers-of-Railways/Railway#484]
### Describe the Bug

Game crashes on launch

https://pastebin.com/6AmUCUj2

https://pastebin.com/4eNsFqBz

### Reproduction Steps

Game launched fine earlier, closed game to do something else, relaunched to error

### Expected Result

Expected game to launch. Nothing had changed between this time and the last time I launched it

### Screenshots and Videos

![error](https://github.com/Layers-of-Railways/Railway/assets/51976767/cb43ee8a-a927-42e1-a0f1-23bd2a652f2a)

### Crash Report or Log

https://pastebin.com/6AmUCUj2  https://pastebin.com/4eNsFqBz

### Operating System

Windows 11

### Mod Version

1.6.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge - 47.2.0

### Other Mods

[Sildur's Enhanced Default (by SildurFX)](https://www.curseforge.com/minecraft/shaders/sildurs-enhanced-default)
[Refined Storage (by raoulvdberge)](https://www.curseforge.com/minecraft/mc-mods/refined-storage)
[[Let's Do] Candlelight (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-candlelight)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[[Let's Do] Beachparty (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-beachparty)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[The Aether (by TheAetherTeam)](https://www.curseforge.com/minecraft/mc-mods/aether)
[Embeddium/Rubidium Extras (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[MakeUp - Ultra Fast | Shaders (by XavierFST)](https://www.curseforge.com/minecraft/shaders/makeup-ultra-fast-shader)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Create: Design n' Decor (by MilkyFur)](https://www.curseforge.com/minecraft/mc-mods/create-design-n-decor)
[Embeddium/Rubidium Dynamic Lights (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Everything is Copper (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/everythingcopper)
[CodeChicken Lib 1.8.+ (by covers1624)](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8)
[Blood Magic (by WayofTime)](https://www.curseforge.com/minecraft/mc-mods/blood-magic)
[Additional Lights (by mgen256)](https://www.curseforge.com/minecraft/mc-mods/additional-lights)
[Chunk Loaders (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders)
[Sildur's Basic Shaders (by SildurFX)](https://www.curseforge.com/minecraft/shaders/sildurs-basic-shaders)
[FerriteCore ((Neo)Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[[Let's Do] API (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/do-api)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
[Chimes (by CicadaBluw)](https://www.curseforge.com/minecraft/mc-mods/chimes)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Sildur's Vibrant shaders (by SildurFX)](https://www.curseforge.com/minecraft/shaders/sildurs-vibrant-shaders)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[Simple Planes (Forge) (by przemykomo)](https://www.curseforge.com/minecraft/mc-mods/simple-planes)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[[Let's Do] Vinery (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery)
[Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[RSInfinityBooster (by hexeptiondev)](https://www.curseforge.com/minecraft/mc-mods/rsinfinitybooster)
[Create : Armory (by Chilllliii)](https://www.curseforge.com/minecraft/mc-mods/create-armory)
[Enderman Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/enderman-overhaul)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[[Let's Do] Brewery (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-brewery)
[Mob Despawn Timers (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/mob-despawn-timers)
[CC: Tweaked (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Create Central Kitchen (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-central-kitchen)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Ender Storage 1.8.+ (by covers1624)](https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8)
[Do a Barrel Roll (by enjarai)](https://www.curseforge.com/minecraft/mc-mods/do-a-barrel-roll)
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[[Let's Do] Bakery (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-bakery)
[Create: ComputerCraft (CC: Tweaked) (by EndRage)](https://www.curseforge.com/minecraft/texture-packs/create-computercraft)
[Create Jetpack (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/create-jetpack)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[[Let's Do] Meadow (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-meadow)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Complementary Shaders - Reimagined (by EminGT)](https://www.curseforge.com/minecraft/shaders/complementary-reimagined)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Paragliders (by Tictim)](https://www.curseforge.com/minecraft/mc-mods/paragliders)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Create: Bells & Whistles (by sudolev)](https://www.curseforge.com/minecraft/mc-mods/bellsandwhistles)
[Amendments (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/amendments)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[Scarecrows' Territory (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/scarecrows-territory)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[Botania (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania)
[TexTrue's Embeddium Options (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/textrues-embeddium-options)
[[Let's Do] NetherVinery (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-nethervinery)
[Complementary Shaders - Unbound (by EminGT)](https://www.curseforge.com/minecraft/shaders/complementary-unbound)
[Create: Interiors (by sudolev)](https://www.curseforge.com/minecraft/mc-mods/interiors)
[Lithostitched (by Apollo)](https://www.curseforge.com/minecraft/mc-mods/lithostitched)
[Dungeon Crawl (by xiroc_)](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl)
[Reborn Storage (by Gigabit101)](https://www.curseforge.com/minecraft/mc-mods/rebornstorage)
[[Let's Do] HerbalBrews (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-herbal-brews)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Create: Diesel Generators (by george8188262)](https://www.curseforge.com/minecraft/mc-mods/create-diesel-generators)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)

**Comment by IThundxr** [comment]
delete your config folder, forge corrupted it

**Comment by HighInPotassium** [comment]
That did it!

Thank you for your help and rapid response!
