### ISSUE TITLE
Phantom Rails renders in Map Mods

### ISSUE THREAD

**Issue by f0kx** [Layers-of-Railways/Railway#486]
### Describe the Bug

When i rail out my Phantom rails they will be visible in the Map Mods i used.

### Reproduction Steps

1. Load the world
2. build with phantom rails
3. see it on my minimap

### Expected Result

maybe there is a solution to not render them.

### Operating System

Win 11

### Mod Version

1.6.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

43.3.8

**Comment by f0kx** [comment]
![image](https://github.com/Layers-of-Railways/Railway/assets/14795020/feed1175-f93a-4d5e-a2b6-699662cf97f8)

**Comment by IThundxr** [comment]
this will be a wontfix, map colors, even with it set to NONE don't display the map color under them, it's out of scope for steam n rails to modify vanilla maps to fix this
