### ISSUE TITLE
Train disappeared 

### ISSUE THREAD

**Issue by skytyler08** [Layers-of-Railways/Railway#488]
### Describe the Bug

When I create a train, the whole thing had disappeared, when click to create the train.

### Reproduction Steps

1. Get Tracks and station.
2. build a train and glue it together.
3. Use station to create the train and the train disappeared.
...

### Expected Result

The train to be created and not be able to disappear. 

### Screenshots and Videos

None

### Crash Report or Log

none

### Operating System

Window 10

### Mod Version

1.6.4

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

47.2.0 forge

**Comment by IThundxr** [comment]
update create
