### ISSUE TITLE
Curved Monorail tracks have no collision.

### ISSUE THREAD

**Issue by NolanHewitt** [Layers-of-Railways/Railway#494]
### Describe the Bug

If monorail tracks are straight you can walk on them. If they curve/turn then they have no collision at all.

### Reproduction Steps

Make a monorail track that curves, you cant walk on it and go through it.

### Expected Result

Curved rails have collision.

### Screenshots and Videos

<img width="1920" alt="image" src="https://github.com/Layers-of-Railways/Railway/assets/52480898/571c5274-4877-4101-8b4d-ae8975b85cdb">

### Operating System

Windows 11

### Mod Version

1.6.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Newest Loader

**Comment by SpottyTheTurtle** [comment]
not a bug, that's just how Create tracks in general work
