### ISSUE TITLE
Data unavailable, why?

### ISSUE THREAD

**Issue by Demokingruler** [Layers-of-Railways/Railway#495]
### Describe the Bug

I have slaved HOURS into DAYS of trying to figure out why every time i want to use steam 'n' rails it just says "Not enough data" i tried installing fixes, testing what mods don't like it, getting different versions, using it by itself, NOTHING WORKS AT ALL. It seems like whatever system is in charge of reading the mod data (forge in this case) takes the data, clears it, and tells minecraft to read it. ABSOLUTELY NOTHING HAS WORKED SO FAR. PLEASE HELP ME WITH THIS ISSUE, I JUST WANT TO MAKE CREATE MOD TRAINS BETTER AGAIN

### Reproduction Steps

1.I have no idea how this happened
2.it has been like this for 8 MONTHS
3.it was working perfectly fine, untill it decided not to
...

### Expected Result

The Steam 'n' rails data just dissapears, again, no idea how it happened or why it is now. Nothing I have tried has been able to let me use this mod

### Screenshots and Videos

![Screenshot 2024-06-26 113819](https://github.com/Layers-of-Railways/Railway/assets/173936181/679263e6-1fff-47b2-8b17-0840a7b77ef3)
![Screenshot 2024-06-26 113538](https://github.com/Layers-of-Railways/Railway/assets/173936181/d5980e26-ec74-4944-a125-647a58a733cd)

### Crash Report or Log

com.electronwill.nightconfig.core.io.ParsingException: Not enough data available

### Operating System

Windows 10

### Mod Version

1.6.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge

### Other Mods

Just Create, and Steam 'n' rails, thats it

### Additional Context

No idea how or why it began

**Comment by IThundxr** [comment]
delete your configs folder, forge corrupted them.

try not crashing/killing the game or bluescreening since those corrupt your configs

**Comment by Demokingruler** [comment]
I did that just now, and it still says that  there is not enough data

**Comment by Demokingruler** [comment]
> delete your configs folder, forge corrupted them.
> 
> try not crashing/killing the game or bluescreening since those corrupt your configs

I did that just now, it still says not enough data, even when getting an updated config folder

**Comment by IThundxr** [comment]
did you delete all files in the config folder and make sure you did that in the right instance folder?

**Comment by Demokingruler** [comment]
> did you delete all files in the config folder and make sure you did that in the right instance folder?

Yes, I have done that, and even checked other instance folders, still the same result

**Comment by IThundxr** [comment]
i'd suggest asking for further support in the forge discord then https://discord.gg/neoforged it's their config system thats causing the crash and issues with it should be reported to them

**Comment by Demokingruler** [comment]
> i'd suggest asking for further support in the forge discord then https://discord.gg/neoforged it's their config system thats causing the crash and issues with it should be reported to them

I tried going into the server, and it tells me that i can't accept the invite
