### ISSUE TITLE
Using SnR Can Cause Items to Disappear from the JEI Ingredients List

### ISSUE THREAD

**Issue by StarliteHeart** [Layers-of-Railways/Railway#496]
### Describe the Bug

When using Steam 'n' Rails alongside JEI, users might occasionally find that a handful of items are absent from their JEI ingredient list, as if not all of them have loaded in. Missing items may include those from other mods, such as the Schematicannon from base Create. Missing items might still be found when using the Recipe viewer, they just do not show up in the ingredient list or during searches.

The range of missing items can be anywhere from about 20 to about 300+, depending on how badly it fails to load all ingredients. This seems more pronounced in larger modpacks but is still replicable in a pack containing only Create, SnR and JEI.

### Reproduction Steps

1. Create a pack that contains only Create, SnR and JEI.
2. Start Minecraft and create a new world.
3. Open your inventory menu and observe how many items are displaying within JEI's ingredient list.
4. Close the application, restart the client and boot up the world again.
5. Check the JEI ingredient list. The number of visible items may have changed. The most obvious result is when enough items have disappeared (or reappeared) such that the number of pages have changed.
6. If you do not immediately see a change, repeat steps 4-5 until the bug is observed.

### Expected Result

When using SnR with JEI, I expect the number of displayed items within the JEI menu to remain static, with all items across all mods that are meant to be displayed being present.

### Crash Report or Log

https://pastebin.com/m5PqdaMq

### Operating System

Windows 10

### Mod Version

1.6.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.17

### Other Mods

JEI v15.3.0.4 & v15.3.0.8 (both versions tested, issue happened in both)

### Additional Context

The log comes from an instance of a pack with only Create, SnR and JEI, where, in ideal circumstances and default JEI settings, I could see 18 pages of items. In the specific log, only 17 pages were displayed.

The bug can be a little stubborn to find sometimes and might only appear once in every five client startups, but at most times, it can be observed within two or three.

**Comment by IThundxr** [comment]
the cause is forge & create https://github.com/Creators-of-Create/Create/issues/6222

**Comment by StarliteHeart** [comment]
To verify, is the linked issue specifically for when items are _only_ missing from the ingredients list? Or when they are missing from both the ingredients list _and_ Creative? Because the bug I am observing does not affect Creative in any way. In this example screenshot, I am not seeing the Schematic and Quill in JEI, but it's there in Creative.

![image_2024-06-27_104905084](https://github.com/Layers-of-Railways/Railway/assets/13985801/61b4ef37-5697-40ac-879a-e9112a68d165)

**Comment by IThundxr** [comment]
the search is independent of tabs, jei pulls from tabs but not the creative tab search section

**Comment by StarliteHeart** [comment]
And that makes sense to me. My question is more about whether or not this issue is connected to the linked issue. The linked issue specifically mentions Creative tabs when Creative isn't affected in what I am observing. If you say both are connected to the same root issue, though, then I will take your word for that.
