### ISSUE TITLE
[Suggestion] Disable stations with redstone

### ISSUE THREAD

**Issue by PrototypeTrousers** [Layers-of-Railways/Railway#497]
### Describe the Suggestion

Add a way to disable train stations (basically limit the station to 0 trains, like in factorio)

### Additional Context

Redstone controlling a train station would make a logistic train network where 1 train could supply, for example, Iron Ingots to many "Iron Receiving stations" just by setting the station name, without needing to update the trains schedules

**Comment by techno-sam** [comment]
Why not just use a mechanical piston to move the station away from the track?

**Comment by PrototypeTrousers** [comment]
Wouldnt removing the station from the rail graph and adding it back be laggy ? im not that familiar how the graph is built

**Comment by techno-sam** [comment]
No. While removing tracks and re-adding them requires the graph to be rebuilt, removing and re-adding "track pad" blocks (stations, track observers, etc) is fairly cheap. An exception to this is perhaps signals, which have their own graph-like system they keep track of
