### ISSUE TITLE
Game Crash Especially While Pondering Conductor using Redstone

### ISSUE THREAD

**Issue by Bioscreeper** [Layers-of-Railways/Railway#498]
### Describe the Bug

My game keeps crashing, especially while pondering about the Create: Steam and Rails Conductor Hat

### Reproduction Steps

1. Search for Conductor in JEI
2. Open Ponder and navigate to next item (Redstone Control)
3. Game crashes.

### Expected Result

Ponder continues

### Crash Report or Log

https://pastebin.com/raw/KUwyApHe

### Operating System

OSX 14.3.1

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.3.5

### Additional Context

This is on a server.

**Comment by techno-sam** [comment]
Update SnR
