### ISSUE TITLE
Outdated compat track items

### ISSUE THREAD

**Issue by theTaeco** [Layers-of-Railways/Railway#500]
[Updated Tracks.zip](https://github.com/user-attachments/files/16134054/Updated.Tracks.zip)
here are some updated ones to fit the changes in 1.6.0, lmk if I missed anything
also contributor role on discord? 👉👈

**Comment by theTaeco** [comment]
not to be inpatient but should I make a pr for this, would that make it more convenient?

**Comment by theTaeco** [comment]
fricking github mobile is so annoying

**Comment by IThundxr** [comment]
a PR would be helpful but this is fine aswell, it'll just be added next time i open the snr project

**Comment by IThundxr** [comment]
Completed in https://github.com/Layers-of-Railways/Railway/commit/4b7d9f8363c7fc1352ae51afe7569f664fe63572 and https://github.com/Layers-of-Railways/Railway/commit/b4efb49d6461769165da1a3d8bd6e3431df7d3e3
