### ISSUE TITLE
Steam & rails causing other create mods to not load in properly

### ISSUE THREAD

**Issue by Edv9** [Layers-of-Railways/Railway#501]
### Describe the Bug

I started up a modpack using Steam and rails and when i load in the game some blocks are missing. I have a few screenshots of following problem. There are tabs in the creative menu that is missing. For example the page where all different types of rails not showing and isnt available to search up in creative invenory or in JEI (Just enough items). Its not just Steam and rails that is missing the original create mod dosn't load properly either and missing almost all items. There also another create mod add on that dosn't show up. in the menu called Create desing n' decor. I have asked the modpack creator about this issue. He claims that its caused by steam and rails because the problem gets solved by removing steam and rails. When i restart the game some items appear again. But theres always items missing when boting up the game. I can also ad that the blocks that are missing still appear  if they are placed ingame. But can not be found in the inventory. The modpack creator is a youtube content creator Link to his channel: https://www.youtube.com/@MrBeardstone
Could you look in to this issue because it sad that i cant use this amazing mod.

![2024-07-11_23 16 59](https://github.com/user-attachments/assets/b108dff7-f308-48f4-9213-0be99c06792a)
![2024-07-11_23 17 24](https://github.com/user-attachments/assets/487f49e1-7dde-4bbf-a714-a964b648cb6c)
![2024-07-11_23 17 45](https://github.com/user-attachments/assets/526283c5-9c35-4b53-9125-b59fd26515a3)

### Reproduction Steps

1. Start a modpack called "Create: a perfect world" by Mr Beardstone, link to modpage:https://www.curseforge.com/minecraft/modpacks/create-perfect-world-2
2. Start a creative world
3. Look in the inventory if you find every create tabs such as all the rails and if the create mod has loaded in all create items correctly
...

### Expected Result

When i open the game all the mods load so they show up. So i can find them when building

### Screenshots and Videos

![2024-07-11_23 16 59](https://github.com/user-attachments/assets/adf19811-f1a7-4fd7-b497-019301078283)
![2024-07-11_23 17 24](https://github.com/user-attachments/assets/54755b30-d433-4b8e-978c-f6cab553a296)
![2024-07-11_23 17 45](https://github.com/user-attachments/assets/9d8cc27d-408f-4d6e-9e36-c9acf0776436)

### Operating System

Windows 10

### Mod Version

1.6.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge - 47.2.0

### Other Mods

- Create mod
- Create Design n' Decor
- Create Extended Cogwheels

are the mods i noticed

**Comment by Bennyboy1695** [comment]
This is actually a create issue and can happen with any addon using create's tab system - https://github.com/Creators-of-Create/Create/issues/6222

**Comment by Edv9** [comment]
> This is actually a create issue and can happen with any addon using create's tab system - [Creators-of-Create/Create#6222](https://github.com/Creators-of-Create/Create/issues/6222)

But it gets fixed when removing the mod? so isnt that caused by this mod?

**Comment by IThundxr** [comment]
no, blame forge's parallel mod loading

**Comment by Edv9** [comment]
> me forge's parallel mod

Okay i understand! :)
