### ISSUE TITLE
"point.edge is null" error

### ISSUE THREAD

**Issue by Dishes4Washing** [Layers-of-Railways/Railway#502]
### Describe the Bug

Modded world no longer boots. Me and my friends play a technology based world using a mod pack that has not been updated in a while. We use another mod called e4mc to host our world on their servers. It appears that a variable was messed upon creation of a train at a station, and now the world will not boot past reading world data. This error code was only produced after multiple attempts at launching:

The game crashed whilst exception in server tick loop Error: java.lang.NullPointerException: Cannot invoke "com.simibubi.create.content.trains.graph.TrackEdge.getTrackMaterial()" because "point.edge" is null

I suspect that it is this mod causing the error, but I could be incorrect. Please correct me if I am in the wrong place. This is also my first github post, please correct me if I used this forum wrong.

### Reproduction Steps

I open the modpack, and launch the world. The world will not launch, and my instance of minecraft crashes. It appears that minecraft will read the world data, but the error occurs when I am being loaded into the world

### Expected Result

I would expect world to open as normal.

### Crash Report or Log

The game crashed whilst exception in server tick loop Error: java.lang.NullPointerException: Cannot invoke "com.simibubi.create.content.trains.graph.TrackEdge.getTrackMaterial()" because "point.edge" is null

### Operating System

Windows 11

### Mod Version

1.3.4

### Create Mod Version

0.5.1b

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 1.255.0.18685

### Other Mods

Every mod that is on the Colony: A New Odyssey: (It's huge, I am so sorry)

[Ad Astra](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[Ad Astra: Giselle Addon](https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon)
[Ad Tetra!](https://www.curseforge.com/minecraft/mc-mods/ad-tetra)
[AI Improvements](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Alchemistry](https://www.curseforge.com/minecraft/mc-mods/alchemistry)
[AlchemyLib](https://www.curseforge.com/minecraft/mc-mods/alchemylib)
[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Applied Energistics 2](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Applied Mekanistics](https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics)
[Architectury API (Fabric/Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Assembly Line Machines](https://www.curseforge.com/minecraft/mc-mods/assemblylinemachines)
[AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[AutoRegLib](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Bad Wither No Cookie - Reloaded](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)
[Balm (Forge Edition)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Bartering Station [Forge & Fabric]](https://www.curseforge.com/minecraft/mc-mods/bartering-station)
[Better Advancements](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Better Compatibility Checker](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Botania](https://www.curseforge.com/minecraft/mc-mods/botania)
[Botanic Additions](https://www.curseforge.com/minecraft/mc-mods/botanic-additions)
[Botarium](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Building Gadgets](https://www.curseforge.com/minecraft/mc-mods/building-gadgets)
[ChemLib](https://www.curseforge.com/minecraft/mc-mods/chemlib)
[Chicken Chunks 1.8.+](https://www.curseforge.com/minecraft/mc-mods/chicken-chunks-1-8)
[Chunky (Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator-forge)
[Cloth Config API (Fabric/Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps)
[CodeChicken Lib 1.8.+](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8)
[CoFH Core](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
[Configured](https://www.curseforge.com/minecraft/mc-mods/configured)
[Connectable Minecarts](https://www.curseforge.com/minecraft/mc-mods/connectable-minecarts)
[Connectivity[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Corail Tombstone](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone)
[Cosmetic Armor Reworked](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[CraftPresence](https://www.curseforge.com/minecraft/mc-mods/craftpresence)
[CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[CraftTweaker Sixik Utils FTB Quest (Outdated)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker-sixik-utils-ftb-quest)
[Create](https://www.curseforge.com/minecraft/mc-mods/create)
[Create : Armory](https://www.curseforge.com/minecraft/mc-mods/create-armory)
[Create : Misc & Things](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[Create Ad Astra Compat](https://www.curseforge.com/minecraft/mc-mods/create-ad-astra-compat)
[Create Chromatic Return](https://www.curseforge.com/minecraft/mc-mods/create-chromaticreturn)
[Create Crafts & Additions](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Create Ore Excavation](https://www.curseforge.com/minecraft/mc-mods/create-ore-excavation)
[Create Slice & Dice](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
[Create Stuff & Additions](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Create: Alloyed](https://www.curseforge.com/minecraft/mc-mods/create-alloyed)
[Create: Electric Stonks](https://www.curseforge.com/minecraft/mc-mods/create-electric-stonks)
[Create: Steam 'n' Rails](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[Create: The Factory Must Grow](https://www.curseforge.com/minecraft/mc-mods/create-industry)
[Cucumber Library](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[Cupboard](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Curios API (Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Dark Utilities](https://www.curseforge.com/minecraft/mc-mods/dark-utilities)
[Darker Depths](https://www.curseforge.com/minecraft/mc-mods/darker-depths)
[Decorative Blocks](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Diamond Nuggets](https://www.curseforge.com/minecraft/mc-mods/diamond-nuggets)
[e4mc](https://www.curseforge.com/minecraft/mc-mods/e4mc)
[Easy Villagers](https://www.curseforge.com/minecraft/mc-mods/easy-villagers)
[Ecologics](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Emojiful](https://www.curseforge.com/minecraft/mc-mods/emojiful)
[Enchantment Descriptions](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Ender Bundle](https://www.curseforge.com/minecraft/mc-mods/ender-bundle)
[Ender Storage 1.8.+](https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8)
[Entity Culling Fabric/Forge](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Extreme Reactors](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
[FancyMenu](https://www.curseforge.com/minecraft/mc-mods/fancymenu)
[Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Farsight [Forge/Neo]](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Fast Leaf Decay](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[FerriteCore ((Neo)Forge)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Flux Networks](https://www.curseforge.com/minecraft/mc-mods/flux-networks)
[FTB Chunks (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[FTB Essentials (Forge & Fabric)](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials)
[FTB Library (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[FTB Quests (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge)
[FTB Teams (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[FTB Ultimine (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[Functional Storage](https://www.curseforge.com/minecraft/mc-mods/functional-storage)
[GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[HammerLib](https://www.curseforge.com/minecraft/mc-mods/hammer-lib)
[Iceberg [Forge]](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Immersive Engineering](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
[Industrial Foregoing](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing)
[Inventory Sorter](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)
[Iron Chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Iron Jetpacks](https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks)
[Item Filters](https://www.curseforge.com/minecraft/mc-mods/item-filters)
[Jade 🔍](https://www.curseforge.com/minecraft/mc-mods/jade)
[JourneyMap](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Just Enough Items (JEI)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Just Enough Resources (JER)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Konkrete [Forge/NeoForge]](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Legendary Tooltips [Forge]](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips)
[LibX](https://www.curseforge.com/minecraft/mc-mods/libx)
[Little Contraptions](https://www.curseforge.com/minecraft/mc-mods/little-contraptions)
[Little Logistics](https://www.curseforge.com/minecraft/mc-mods/little-logistics)
[Lootr (Forge & NeoForge)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[McJtyLib](https://www.curseforge.com/minecraft/mc-mods/mcjtylib)
[Mekanism](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Mekanism Tools](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Miner's Helmet](https://www.curseforge.com/minecraft/mc-mods/miners-helmet)
[Moonlight Lib](https://www.curseforge.com/minecraft/mc-mods/selene)
[More Minecarts and Rails](https://www.curseforge.com/minecraft/mc-mods/more-minecarts)
[Morph-o-Tool](https://www.curseforge.com/minecraft/mc-mods/morph-o-tool)
[Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[MrCrayfish's Furniture Mod](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[mutil](https://www.curseforge.com/minecraft/mc-mods/mutil)
[MythicBotany](https://www.curseforge.com/minecraft/mc-mods/mythicbotany)
[Nature's Compass](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[NetherPortalFix](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
[Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Oh The Biomes You'll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[OpenBlocks Elevator](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Patchouli](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Pig Pen Cipher](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher)
[Pipez](https://www.curseforge.com/minecraft/mc-mods/pipez)
[Placebo](https://www.curseforge.com/minecraft/mc-mods/placebo)
[PneumaticCraft: Repressurized](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized)
[Polymorph (Fabric/Forge/Quilt)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Prism [Forge]](https://www.curseforge.com/minecraft/mc-mods/prism-lib)
[Productive Bees](https://www.curseforge.com/minecraft/mc-mods/productivebees)
[Propeller Hats](https://www.curseforge.com/minecraft/mc-mods/propeller-hats)
[Puzzles Lib [Forge & Fabric]](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[ReAuth](https://www.curseforge.com/minecraft/mc-mods/reauth)
[Redstone Arsenal](https://www.curseforge.com/minecraft/mc-mods/redstone-arsenal)
[Resourceful Config](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Resourceful Lib](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[RFTools Base](https://www.curseforge.com/minecraft/mc-mods/rftools-base)
[RFTools Power](https://www.curseforge.com/minecraft/mc-mods/rftools-power)
[Rhino](https://www.curseforge.com/minecraft/mc-mods/rhino)
[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Runelic](https://www.curseforge.com/minecraft/mc-mods/runelic)
[Sand Box](https://www.curseforge.com/minecraft/mc-mods/sand_box)
[Saro´s Create [Forge]](https://www.curseforge.com/minecraft/mc-mods/saro-s-create-addon-forge)
[Scalable Cat's Force](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force)
[Scuba Gear](https://www.curseforge.com/minecraft/mc-mods/scuba-gear)
[Simple Magnets](https://www.curseforge.com/minecraft/mc-mods/simple-magnets)
[Simple Spikes](https://www.curseforge.com/minecraft/mc-mods/simple-spikes)
[Solar Energy](https://www.curseforge.com/minecraft/mc-mods/solar-energy)
[Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Sophisticated Core](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[spark](https://www.curseforge.com/minecraft/mc-mods/spark)
[Spirit](https://www.curseforge.com/minecraft/mc-mods/spirit)
[Star Wars Planets [Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra)
[Superior Hammers! [ FORGE / FABRIC ]](https://www.curseforge.com/minecraft/mc-mods/hammers-extension)
[SuperMartijn642's Config Lib](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[SuperMartijn642's Core Lib](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[SwingThroughGrass](https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass)
[TerraBlender (Forge)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Tetra](https://www.curseforge.com/minecraft/mc-mods/tetra)
[Thermal Cultivation](https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation)
[Thermal Dynamics](https://www.curseforge.com/minecraft/mc-mods/thermal-dynamics)
[Thermal Expansion](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)
[Thermal Foundation](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
[Thermal Innovation](https://www.curseforge.com/minecraft/mc-mods/thermal-innovation)
[Thermal Locomotion](https://www.curseforge.com/minecraft/mc-mods/thermal-locomotion)
[Titanium](https://www.curseforge.com/minecraft/mc-mods/titanium)
[Toast Control](https://www.curseforge.com/minecraft/mc-mods/toast-control)
[Torchmaster](https://www.curseforge.com/minecraft/mc-mods/torchmaster)
[TrashSlot](https://www.curseforge.com/minecraft/mc-mods/trashslot)
[Vitalize](https://www.curseforge.com/minecraft/mc-mods/vitalize)
[Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Wireless Chargers](https://www.curseforge.com/minecraft/mc-mods/wireless-chargers)
[XNet](https://www.curseforge.com/minecraft/mc-mods/xnet)
[XNet Gases](https://www.curseforge.com/minecraft/mc-mods/xnet-gases)
[YUNG's API (Forge)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[YUNG's Better Dungeons (Forge)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[YUNG's Better Mineshafts (Forge)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[YUNG's Better Strongholds (Forge)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[ZeroCore 2](https://www.curseforge.com/minecraft/mc-mods/zerocore)

### Additional Context

In my panicked attempt to fix this very important world, I also updated Create: Steam 'n' Rails to 1.6.4. The problem still persists.

**Comment by IThundxr** [comment]
Provide the log you get when you update steam n rails to 1.6.4 and create to 0.5.1-f
