### ISSUE TITLE
Visual bug in 1.20.1

### ISSUE THREAD

**Issue by Orion2852** [Layers-of-Railways/Railway#503]
### Describe the Bug

When I put the train tracks from steam n rails mod, this thing appears that teleports to me at regular intervals like a tamed wolf. This is an entity

### Reproduction Steps

1.put any track
2.
3.
...

### Expected Result

this thing shouldn't exist

### Screenshots and Videos

![Java-runtime-gamma Screenshot 2024 07 16 - 21 21 46 75](https://github.com/user-attachments/assets/47b39095-690a-4ece-a36b-7c311f165136)

### Operating System

windows 10

### Mod Version

1.6.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

forge 47.2.0

**Comment by IThundxr** [comment]
Thats not a model added by steam n rails, another mod you are using has a messed up flywheel instance
