### ISSUE TITLE
Server crash after force-load MixinTrainHatOffsets.java

### ISSUE THREAD

**Issue by SrRapero720** [Layers-of-Railways/Railway#51]
Mod: Steam_Rails-1.18.2-1.0.6.jar
Forge: 40.2.0
Create: 0.5.0h

Little Explain: I am making a Mixin Cache clear (like MemoryLeakFix of fabric) in forge.
So to do that i load all mixins and clear cache to use less memory.

But one of your mixins causes problems with the mod after trying to load it:
https://github.com/Layers-of-Railways/Railway/blob/69548b9534bb1c9227fc6ff746c135413016783d/src/main/java/com/railwayteam/railways/mixin/MixinTrainHatOffsets.java#L12-L20

Here is the crash report
[crash-2023-01-23_00.19.06-server.txt](https://github.com/Layers-of-Railways/Railway/files/10477325/crash-2023-01-23_00.19.06-server.txt)

The problem is i dont know how to fix it (in my mod or your mod).

**Comment by SrRapero720** [comment]
Sorry, i found a duplicated
https://github.com/Layers-of-Railways/Railway/issues/47

**Comment by SrRapero720** [comment]
I no found the mixin json file in repo, so i dont know if this mixin its apply on both sides (because only crash on server but no client, and i do the same thing on both)

So probably adding a ```@OnlyIn(Dist.CLIENT)``` on the top solves it (i can't test because my internet is too bad and download all mod code + dependencies can become a hell)

I expect no cause troubles, because all clases involved in mixin are Suscribed to Client methods

**Comment by techno-sam** [comment]
Whoops, this should have been in client mixins. fixed in next release

**Comment by SrRapero720** [comment]
consider to upload to repo the `mixins.rails.json` pls, i never found file to see the problem before.
and thanks :)
