### ISSUE TITLE
steam n rails crashes upon loading into server

### ISSUE THREAD

**Issue by Jackboy317** [Layers-of-Railways/Railway#513]
### Context

I'm trying to put a modded forge server up for a friend, and steam n rails keeps wanting to crash. Any ideas?

Crash log:
[crash-2024-08-17_16.55.07-client.txt](https://github.com/user-attachments/files/16646483/crash-2024-08-17_16.55.07-client.txt)

### Crash Report

https://mclo.gs/qxKgGDc

**Comment by IThundxr** [comment]
Update steam 'n' rails to 1.6.4
