### ISSUE TITLE
Uncraftable recipes for new headstocks, buffers, and links? [FIXED! Kinda]

### ISSUE THREAD

**Issue by Demokingruler** [Layers-of-Railways/Railway#514]
I am playing a create survival world, and i would like to use the headstocks, i looked around and found how to craft it and its variants. However, nothing i use such as Mechanical crafter or crafting table will actually craft the items i need, is this an issue, intended thing, or was something not updated. im not sure but i would like to have the option of making my trains look nicer.
Shown list of recipes [https://github.com/Layers-of-Railways/Railway/wiki/Deco-Blocks](url)

Just Enough Items showing the recipe:
![Screenshot 2024-08-20 160438](https://github.com/user-attachments/assets/f6e66956-d0bc-41d7-9256-7c23c0467988)

When I try to craft it:

![Screenshot 2024-08-20 160507](https://github.com/user-attachments/assets/ecc6fadf-50f8-471c-94c0-32749c8f7b8d)

**Comment by IThundxr** [comment]
Move the items 1 row down, that recipe isn't shapeless even though it should be

**Comment by Demokingruler** [comment]
> Move the items 1 row down, that recipe isn't shapeless even though it should be

I already tried this and multiple variations, none of them work

**Comment by Demokingruler** [comment]
Found the issue, i was using industrial iron **PLATING** instead of industrial iron, its working just fine @IThundxr
