### ISSUE TITLE
Steam 'n' Rails Makes Create Large Bogey Type Inaccessible

### ISSUE THREAD

**Issue by EvilDylan** [Layers-of-Railways/Railway#516]
### Description

Mod loader: Forge 47.3.6
Create version: 0.5.1.f
Steam 'n' Rails version: 1.6.4+forge-mc1.20.1
Game version: 1.20.1

Description: In the base Create mod, bogeys has two types which can be cycled by right-clicking with a wrench; the standard type with four small wheels, and the large type with two large wheels. When Create: Steam 'n' Rails is installed, the large bogey type can no longer be cycled to with the wrench and is not accessible with the included style selection menu.

Large bogeys placed in the world prior to installing Steam 'n' Rails remain in the world.

If the rails beneath the bogey are removed, then the bogey can be cycled to the large bogey type using the wrench. However, it is labeled "standard", and appears to take the place of the standard four small wheels type in the list.

This does not appear to be a documented change, so I assume it is unintentional.

<details>
<summary>Steps to Reproduce:</summary>

   1. Install Create on a Forge instance
   2. Create a world, place a standard-sized rail, create a new train, place a bogey, right-click it with a wrench to cycle to large type
   3. Exit game, install Steam 'n' Rails on same Forge instance.
   4. Load previous world, place a new bogey, attempt to right-click it with a wrench until it matches the type of the existing bogey
   5. Use bogey menu to attempt to match the type of the existing bogey
   6. Remove the rail below a new standard type bogey and right-click 6 times with a wrench to change it to the large bogey type
</details>

Further note: This issue appears to have been noticed 6 months ago in this [detail-sparse Reddit thread](https://www.reddit.com/r/CreateMod/comments/1aslqwa/how_can_i_place_large_bogey/), but not formally reported here.

### Game Log

https://mclo.gs/8HF70qI

### Debug Information

<details>
<summary>Client Info</summary>

```
Create:
	Mod Version: 0.5.1f
	Forge Version: 47.3.6
	Minecraft Version: 1.20.1

Graphics:
	Flywheel Version: 0.6.10-7
	Flywheel Backend: INSTANCING
	OpenGL Renderer: AMD Radeon RX 6500M
	OpenGL Version: 4.6.0 Core Profile Context 24.8.1.240822
	Graphics Mode: Graphics

System Information:
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.12, Oracle Corporation
	JVM Flags: 7 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Memory: 484475360 bytes (462 MiB) / 1887436800 bytes (1800 MiB) up to 4294967296 bytes (4096 MiB)
	CPU: AMD Ryzen 7 5800H with Radeon Graphics @ 3.19 GHz; 8 cores / 16 threads on 1 socket(s)
	Graphics card #0: AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc. (0x1002)); 512.00 MB of VRAM
	Graphics card #1: AMD Radeon RX 6500M (Advanced Micro Devices, Inc. (0x1002)); 4080.00 MB of VRAM

Other Mods:
	MixinExtras: 0.3.5
	Create: Steam 'n' Rails: 1.6.4+forge-mc1.20.1
```

</details>

<details>
<summary>Server Info</summary>

```
Create:
	Mod Version: 0.5.1f
	Forge Version: 47.3.6
	Minecraft Version: 1.20.1

System Information:
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.12, Oracle Corporation
	JVM Flags: 7 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Memory: 484475360 bytes (462 MiB) / 1887436800 bytes (1800 MiB) up to 4294967296 bytes (4096 MiB)
	CPU: AMD Ryzen 7 5800H with Radeon Graphics @ 3.19 GHz; 8 cores / 16 threads on 1 socket(s)
	Graphics card #0: AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc. (0x1002)); 512.00 MB of VRAM
	Graphics card #1: AMD Radeon RX 6500M (Advanced Micro Devices, Inc. (0x1002)); 4080.00 MB of VRAM

Other Mods:
	MixinExtras: 0.3.5
	Create: Steam 'n' Rails: 1.6.4+forge-mc1.20.1
```

</details>

**Comment by IThundxr** [comment]
wrench the bogey block/track, they both have different interactions one of them changes the bogey style and another changes the bogey size
