### ISSUE TITLE
Making a 2-tall Fuel Tank on a Carriage Contraption makes it disappear upon trying to disassemble it/single fuel tanks have their content emptied.

### ISSUE THREAD

**Issue by carbonatek** [Layers-of-Railways/Railway#521]
### Description

The title is very self-descriptive.
Here's the two different scenarios; one depicts the tanks being emptied if they're just 1x1, and the other shows the train disappearing when you introduce a 2x1 tank on the carriage.

https://github.com/user-attachments/assets/d4320a9e-c332-42bd-bfb8-09b5e1b40869

https://github.com/user-attachments/assets/3de43c60-0512-4195-81d9-3f7eb24fdaf3

### Game Log

<There is nothing that will help since it doesn't log anything extra into either latest.log or debug.log>

### Debug Information

<details>
<summary>Client Info</summary>

```
Create:
	Mod Version: 0.5.1h
	Forge Version: 47.3.0
	Minecraft Version: 1.20.1

Graphics:
	Flywheel Version: 0.6.11-13
	Flywheel Backend: INSTANCING
	OpenGL Renderer: AMD Radeon RX 6650 XT (radeonsi, navi23, LLVM 18.1.8, DRM 3.54, 6.6.8-zen1-carbon)
	OpenGL Version: 4.6 (Core Profile) Mesa 24.1.6
	Graphics Mode: options.graphics.fancy

System Information:
	Operating System: Linux (amd64) version 6.6.8-zen1-carbon
	Java Version: 17.0.3, Azul Systems, Inc.
	JVM Flags: 2 total; -Xms128m -Xmx6144m
	Memory: 556213016 bytes (530 MiB) / 1904214016 bytes (1816 MiB) up to 6442450944 bytes (6144 MiB)
	Total Memory: 20820680704 bytes (19848 MiB) / 33558528000 bytes (31990 MiB)
	CPU: AMD Ryzen 7 5700X 8-Core Processor @ -0.00 GHz; 8 cores / 16 threads on 1 socket(s)
	Graphics card #0: Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] (Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)); 8448.00 MB of VRAM

Other Mods:
	MixinExtras: 0.3.5
	Create: Steam 'n' Rails: 1.6.5+forge-mc1.20.1
```

</details>

<details>
<summary>Server Info</summary>

```
Create:
	Mod Version: 0.5.1h
	Forge Version: 47.3.0
	Minecraft Version: 1.20.1

System Information:
	Operating System: Linux (amd64) version 6.6.8-zen1-carbon
	Java Version: 17.0.3, Azul Systems, Inc.
	JVM Flags: 2 total; -Xms128m -Xmx6144m
	Memory: 556213016 bytes (530 MiB) / 1904214016 bytes (1816 MiB) up to 6442450944 bytes (6144 MiB)
	Total Memory: 20820680704 bytes (19848 MiB) / 33558528000 bytes (31990 MiB)
	CPU: AMD Ryzen 7 5700X 8-Core Processor @ -0.00 GHz; 8 cores / 16 threads on 1 socket(s)
	Graphics card #0: Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] (Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)); 8448.00 MB of VRAM

Other Mods:
	MixinExtras: 0.3.5
	Create: Steam 'n' Rails: 1.6.5+forge-mc1.20.1
```

</details>

**Comment by carbonatek** [comment]
Last working version to not be broken is Create 0.5.1f + Steam 'n' Rails 1.6.1.
EDIT 1: I'll be editing this to reflect my findings, it will take a bit of time though, have some patience please.
EDIT 2: No it worked once on a pre-made train once I upgraded to patch G but then broke, so what I've written first is true.

**Comment by DankestO** [comment]
Hi! I have this same problem, but not only with the Fuel Tanks.

I have a monorail with two wagons (driver and cargo) with a liquid and object interface, apart from that, I tried to add an electricity interface from Create Crafts & Additions, when I put the latter on my monorail, and I disassemble it, sometimes the second time I try to disassemble it, the second wagon, the cargo one that included the interfaces disappears, the other wagon remains intact.

I mention it here because I was trying it with normal Create tracks, and it doesn't seem to happen in the attempts I made, so I imagine it's the same bug?

**Comment by INV-PLA** [comment]
To be precise, all dynamic structures will collapse directly when the power piston pushes the block

**Comment by INV-PLA** [comment]
[minecraft-exported-crash-info-2024-09-19T17-50-04.zip](https://github.com/user-attachments/files/17057062/minecraft-exported-crash-info-2024-09-19T17-50-04.zip)

**Comment by IThundxr** [comment]
That is caused by a issue in create, it'll be fixed next patch

**Comment by INV-PLA** [comment]
I took a glance and didn't see the fixed version, or did I use another method to solve the problem?

**Comment by IThundxr** [comment]
You'll have to wait for the next create patch, it's not out yet
