### ISSUE TITLE
Crash with fuel tanks on a train; caused by "this.wrapped" is null

### ISSUE THREAD

**Issue by waffle58** [Layers-of-Railways/Railway#523]
### Context

When attempting to fuel a train (on realistic fuel mode) with lava as fuel, the game crashes as soon as the mechanical pump is activated (into the fuel interface). This also causes the world to be inaccessible and corrupt. This crashes regardless whether the train is "interactable" via Create: Interactive

**Reproduction**

Create a simple train with fuel tanks and a fuel interface. (not intractable with Create: Interactive)
Connect to another interface
Use mechanical pump to transfer fuel (i tried lava)
Should crash

**OS**
Windows 11

**Version**

1.20.1

**Mod Version**

1.6.4

**Create Version**

0.5.1-f

**Loader**

Fabric 0.16.5

**Mods List**
advancementinfo-1.20-fabric0.83.0-1.4
animatica-0.6.1+1.20.4
antighost-1.20-fabric0.83.0-1.1.5
architectury-9.2.14-fabric
bettermounthud-1.2.2
borderless-mining-1.1.8+1.20.1
capes-1.5.2+1.20-fabric
citresewn-1.1.5+1.20.1
cloth-config-11.1.136-fabric
continuity-3.0.0-beta.5+1.20.1
create_interactive-1.0.3-beta.2+e045de2a48
createaddition-fabric+1.20.1-1.2.4
createdieselgenerators-2.1.4
create-fabric-0.5.1-f-build.1417+mc1.20.1
Debugify-1.20.1+2.0
dynamic-fps-3.7.3+minecraft-1.20.0-fabric
e4mc_minecraft-fabric-5.2.1
enhancedblockentities-0.9+1.20
entity_model_features_fabric_1.20.1-2.2.6
entity_texture_features_fabric_1.20.1-6.2.5
entityculling-fabric-1.7.0-mc1.20.1
fabric-api-0.92.2+1.20.1
fabric-language-kotlin-1.12.2+kotlin.2.0.20
fabricskyboxes-0.7.3+mc1.20.1
fabrishot-1.10.1
fadeless-1.0.1
farsight-fabric-1.20.1-4.1
fastquit-3.0.0+1.20+
ferritecore-6.0.1-fabric
fsb-interop-1.3.6+mc1.20.1-build.50
ImmediatelyFast-Fabric-1.2.21+1.20.4
indium-1.0.34+mc1.20.1
iris-1.7.2+mc1.20.1                    (Shaders were off)
kubejs-create-fabric-2024.8.12-build.1
kubejs-fabric-2001.6.5-build.14
lambdynamiclights-2.3.2+1.20.1
language-reload-1.6.1+1.20.1
lithium-fabric-mc1.20.1-0.11.2
main-menu-credits-1.1.2
memoryleakfix-fabric-1.17+-1.1.5
mixintrace-1.1.1+1.17
modelfix-1.15-fabric
modernfix-fabric-5.19.4+mc1.20.1
modmenu-7.2.2
morechathistory-1.3.0
moreculling-1.20.4-0.24.0
NoChatReports-FABRIC-1.20.1-v2.2.2
optigui-2.3.0-beta.5+1.20
puzzle-1.5.2+1.20
reeses_sodium_options-1.7.2+mc1.20.1-build.101
rhino-fabric-2001.2.3-build.6
RoughlyEnoughItems-12.1.780-fabric
rrls-4.0.6.1+mc1.20.1-fabric
sodium-extra-0.5.4+mc1.20.1-build.115
sodium-fabric-0.5.11+mc1.20.1
Steam_Rails-1.6.4+fabric-mc1.20.1
valkyrienskies-120-2.3.0-beta.5
YetAnotherConfigLib-3.5.0+1.20.1-fabric
yosbr-0.1.2
Zoomify-2.14.0+1.20.1

### Crash Report

https://mclo.gs/IpmzTUd

**Comment by IThundxr** [comment]
caused by create interactive, nothing we can do about it
