### ISSUE TITLE
Recipes using Fabric conditions in the Forge version

### ISSUE THREAD

**Issue by emihead** [Layers-of-Railways/Railway#525]
### Description

Hi, I noticed this while I was trying to troubleshoot a JEI problem. On Forge, most if not all of the compat recipes seem to be using Fabric load conditions instead of Forge load conditions. I have no idea if this is actually what's causing the issue I was having, but it's causing a lot of log spam.

### Game Log

https://mclo.gs/9y9jyXg

### Debug Information

Not relevant here

**Comment by IThundxr** [comment]
The recipes are data generated into common so they are given load conditions for both loaders https://github.com/Layers-of-Railways/Railway/blob/1.20/dev/common/src/generated/resources/data/railways/recipes/sequenced_assembly/track_biomesoplenty_dead.json

**Comment by emihead** [comment]
Oh, I didn't notice they were using both, my bad. I did find out that it wasn't causing the issue I was having anyway, even if the log spam would be nice to not have, so I guess it's not really an issue

**Comment by IThundxr** [comment]
Yeah i don't theres much we can do here
