### ISSUE TITLE
Flywheel 20.1 FORGE

### ISSUE THREAD

**Issue by itsdeadfrosty** [Layers-of-Railways/Railway#530]
### Context

no crashlog. when installed, create and minecraft freaks out cause this mod depends on Legacy Flywheel instead of bundling the modern version like every other create mod. so the create mods get mad legacy flywheel is installed, cause the version isnt ancient. and minecraft say the opposite. gotta get w the program

### Crash Report

none

**Comment by IThundxr** [comment]
Steam n rails does not mark legacy flywheel as a dependency, this is caused by you using curseforge, switch to a working launcher like prism launcher or modrinth app

**Comment by itsdeadfrosty** [comment]
curseforge works fine, if you have personal gripes with curseforge , thats on you.

if i remove legacy flywheel when your mod is installed it crashes. if i install both it crashes.

its not curseforge buddy. im know that much with certainty

**Comment by IThundxr** [comment]
> curseforge works fine, if you have personal gripes with curseforge , thats on you.
> 
> if i remove legacy flywheel when your mod is installed it crashes. if i install both it crashes.
> 
> its not curseforge buddy. im know that much with certainty

Its not a "personal gripes" issue, it's a known fact that curseforge continues to download dependencies for older versions of mods (in this case flywheel legacy for create) even if a newer version is downloaded. (This issue also occurs with mods like quark which depend on zeta now instead of autoreglib)

As for the issue where it crashes, send a log of that, without a log there is no way for anyone to know why it's crashing.

**Comment by itsdeadfrosty** [comment]
if its not a personal gripe, i apologize. too many devs are hyper-aggressive and biased. if youre the exception, its unfortunate to be stereotyped, but its the easiest default.

as for the crashlog, thatll take some time, i stripped it out from my build, will update in time.

**Comment by itsdeadfrosty** [comment]
[Latestlog](https://pastebin.com/dScVcvHP)

tested without legacy flywheel, no crashlog. i do have latest. im not sure what else i can provide.

**Comment by IThundxr** [comment]
try disabling endlessbiomes or phantasm, the last thing in the log mentions a mixin conflict which likely caused forge to just not generate a crashlog properly

**Comment by itsdeadfrosty** [comment]
endless fixed SO many mods not working, will test with steam. thank you!

**Comment by itsdeadfrosty** [comment]
[crash-2024-10-27_19.33.02-client.txt](https://github.com/user-attachments/files/17535758/crash-2024-10-27_19.33.02-client.txt)
heres a working crash report thank u

**Comment by IThundxr** [comment]
That is caused by better end, you should reach out to the connector team since it's being loaded through connector
