### ISSUE TITLE
Removing fuel thru datapacks doesn't work.

### ISSUE THREAD

**Issue by Crimssoon** [Layers-of-Railways/Railway#532]
{
  "fluids": [
    "minecraft:lava"
  ],
  "invalid": true
}

`zipfile/data/railways_liquid_fuel/remove_lava.json` (exactly this)

**Comment by techno-sam** [comment]
your pack layout is wrong. You should be doing `zipfile/data/namespace_aka_packid/railways_liquid_fuel/remove_lava.json`, not `zipfile/data/railways_liquid_fuel/remove_lava.json`

```diff
- zipfile/data/railways_liquid_fuel/remove_lava.json
+ zipfile/data/namespace_aka_packid/railways_liquid_fuel/remove_lava.json
```
