### ISSUE TITLE
[Fabric][1.20.1] - Incompat with latest Create 0.5.1-j-build.1609

### ISSUE THREAD

**Issue by Allexio** [Layers-of-Railways/Railway#537]
Hey there,
I do not know if you are aware but the latest version of Create: Steam & Rails is marked as incompatible with the latest version of Create Fabric.
![Image](https://github.com/user-attachments/assets/b0e66346-211a-4772-be6d-9db66aacd8a9)

**Comment by IThundxr** [comment]
fixed by 1.6.8 which should be uploaded to modrinth and curseforge anytime now

**Comment by Allexio** [comment]
Awesome, thanks man :)
