### ISSUE TITLE
Game Won't Open

### ISSUE THREAD

**Issue by JoshVAccount** [Layers-of-Railways/Railway#540]
Essentially, when I open this mod in a modpack, I can't even get into the game because it shows a screen that says "Mod: Steam and Rails is not loading. Reason: Not enough data." I had my father who works in IT help me, but nothing worked. I even deleted a bunch of old downloads, but still nothing. Could this be an issue from me or is it an issue with the mod?

**Comment by IThundxr** [comment]
Delete your configs folder, forge corrupted all of your configs
