### ISSUE TITLE
Train schedule lost when summoning conductor with full inventory.

### ISSUE THREAD

**Issue by tehbeard** [Layers-of-Railways/Railway#68]
Version: 1.19.2-1.1.1

When summoning a conductor controlled train using the whistle, if the train has a schedule held by the conductor (as opposed to one "applied" by a station with a schedule atop it), said schedule is given to the user.

This has some flaws when the player summoning has a full inventory.

- In creative mode, this results in the schedule being destroyed.
- In Survival mode, the schedule item is thrown out in front of the player. Said item has the potential of being missed, or falling somewhere inconvenient such as down a ravine the line traverses, into lava in the nether, etc..

This mechanic isn't really explained to the player, and is somewhat surprising if they are used to train contraptions, where a player can "pause" the schedule for manual control while the driver/conductor keeps the schedule (I do realize however, that this manual control aspect might not be applicable to switching from one schedule to another).

As a conductor whistle's only apply to the conductor mob added by Steam n' Rails, perhaps shifting the train schedule to a secondary inventory slot when summoned, with some logic to revert to this schedule when right clicked like the pause/resume mechanic in Create works, would be better?

**Comment by techno-sam** [comment]
Good idea. Perhaps in the next update we will have the schedule be stored in the conductor. Thanks for the idea
