### ISSUE TITLE
Door side selector not working

### ISSUE THREAD

**Issue by myron-obsolete-account** [Layers-of-Railways/Railway#70]
When I tell the train station to only open the right doors both doors still open. How do I stop that from happening?

**Comment by tehbeard** [comment]
Did you configure the train doors before assembling the train?

Hold a Wrench and aim at the bottom half of the door, to cycle it's modes, auto, manual,left,right.

**Comment by myron-obsolete-account** [comment]
oh no I did not. I thought the addon will automatically notice which is left and right by uh idk. But thanks for telling me
