### ISSUE TITLE
Slab-encased rails have no slab collisions

### ISSUE THREAD

**Issue by myron-obsolete-account** [Layers-of-Railways/Railway#71]
This is kind of more like a suggestion than a bug report, but I'm kinda missing the slab collisions on rails that have been slab'd.

**Comment by techno-sam** [comment]
can't be done currently - no collisions beyond 1x1x1 blocks work

**Comment by techno-sam** [comment]
Dev team has some ideas, so reopening

**Comment by IThundxr** [comment]
Finished in development will release in 1.5.0
