### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Kinasagi** [Layers-of-Railways/Railway#72]
Create 0.5.0.g it crashed with this report. Same result with version 1.0.6 Patch H

[crash-2023-02-14_05.55.52-client.txt](https://github.com/Layers-of-Railways/Railway/files/10728379/crash-2023-02-14_05.55.52-client.txt)

Tried with only create mod but no luck either
[crash-2023-02-14_06.23.29-client.txt](https://github.com/Layers-of-Railways/Railway/files/10728465/crash-2023-02-14_06.23.29-client.txt)

1.0.6 Works as intended

**Comment by LemmaEOF** [comment]
Create Steam 'n' Rails 1.1.1 *requires* Create 0.5.0h or higher, and will not work with 0.5.0g or below.
