### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by TotallNotEC24** [Layers-of-Railways/Railway#73]
So when I load into my world, it loads to 100 and crashes I don't know why but I have forge 1.19.2 and I have the cerate mod installed
I copied the error code here:

Error: java.lang.ClassFormatError: Duplicate method name "handler$zci000$setupMaterial_2$missing" with signature "(Lnet.minecraft.world.level.Level;Lnet.minecraft.world.entity.player.Player;Lnet.minecraft.core.BlockPos;Lnet.minecraft.world.level.block.state.BlockState;Lnet.minecraft.world.item.ItemStack;ZZLorg.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;Lnet.minecraft.world.phys.Vec3;ILcom.simibubi.create.content.logistics.trains.track.TrackPlacement$PlacementInfo;Lcom.simibubi.create.content.logistics.trains.ITrackBlock;Lcom.simibubi.create.foundation.utility.Pair;Lnet.minecraft.world.phys.Vec3;Lnet.minecraft.world.phys.Vec3;Lnet.minecraft.world.phys.Vec3;Lnet.minecraft.world.phys.Vec3;Lnet.minecraft.nbt.CompoundTag;Lnet.minecraft.nbt.CompoundTag;Lnet.minecraft.core.BlockPos;Lnet.minecraft.world.phys.Vec3;Lnet.minecraft.world.phys.Vec3;Lnet.minecraft.world.phys.Vec3;Lnet.minecraft.world.phys.Vec3;ZLnet.minecraft.world.level.block.state.BlockState;)V" in class file com/simibubi/create/content/logistics/trains/track/Track

**Comment by LemmaEOF** [comment]
Update to Create 0.5.0h or 0.5.0i

**Comment by TotallNotEC24** [comment]
thanks :)
