### ISSUE TITLE
⚠️𝗖𝗥𝗔𝗦𝗛⚠️𝘚𝘵𝘦𝘢𝘮 '𝘯 𝘙𝘢𝘪𝘭𝘴 𝘤𝘢𝘶𝘴𝘦𝘴 𝘮𝘺 𝘨𝘢𝘮𝘦 𝘵𝘰 𝘤𝘳𝘢𝘴𝘩!

### ISSUE THREAD

**Issue by SalmonSnakeD** [Layers-of-Railways/Railway#76]
**Create: Steam 'n Rails** mod (Steam_Rails-1.19.2-1.1.1.jar) crashes my game.

**I use Forge 43.2.4 - 1.19.2**

When I load up my game, there is a total of 13 errors

![2023-02-21_12 52 45](https://user-images.githubusercontent.com/97033682/220325743-8cfab0f9-1c9c-49ac-896f-a0e779d2409b.png)

![2023-02-21_12 54 53](https://user-images.githubusercontent.com/97033682/220325945-0ff102fb-bc47-4f3f-8ac6-bb5ca25d743a.png)

And i'm just trying to figure out how to fix each error one by one. 
(This is the fourth issue I posted today)

**Here is the latest.log**
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10792802/latest.log)
**And crash.log**
[crash-2023-02-21_12.30.33-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10792845/crash-2023-02-21_12.30.33-fml.txt)

**Below is the error message that this mod gave me. But please check the log files above to get full logs.**

> -- MOD railways --
> Details:
> Caused by 0: java.lang.reflect.InvocationTargetException
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23491!/:?] {}
> at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23490!/:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
> 
> Mod File: /C:/Users/PRIVATE/curseforge/minecraft/Instances/1.19.2 Adventure/mods/Steam_Rails-1.19.2-1.1.1.jar
> Failure message: Create: Steam 'n Rails (railways) has failed to load correctly
> java.lang.reflect.InvocationTargetException: null
> Mod Version: 1.19.2-1.1.1
> Mod Issue URL: https://github.com/Layers-of-Railways/Railway/issues
> Exception message: java.lang.NoClassDefFoundError: Could not initialize class net.minecraftforge.network.NetworkDirection
> 
> Stacktrace:
> at com.railwayteam.railways.registry.CRPackets.<clinit>(CRPackets.java:26) ~[Steam_Rails-1.19.2-1.1.1.jar%23458!/:1.19.2-1.1.1] {re:classloading}
> at com.railwayteam.railways.ModSetup.register(ModSetup.java:17) ~[Steam_Rails-1.19.2-1.1.1.jar%23458!/:1.19.2-1.1.1] {re:classloading}
> at com.railwayteam.railways.Railways.<init>(Railways.java:68) ~[Steam_Rails-1.19.2-1.1.1.jar%23458!/:1.19.2-1.1.1] {re:classloading,re:mixin}
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23491!/:?] {}
> at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23490!/:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
> 

**Please can someone help me with this, I am not sure how to fix this..**

**Comment by stacode123** [comment]
huh? it looks like something else is breaking your mods and steam an rails is just one of the mods that broken check your forge install and make sure you have the latest version
