### ISSUE TITLE
Couling direction

### ISSUE THREAD

**Issue by tobi-blackscale** [Layers-of-Railways/Railway#79]
It seems direction of trains and cars matters while coupling, but that doesn't really make sense.

Currently all trains have to face the same direction to be able to coupled (based on the building direction) =>
It is only possible to connect the last bearing on a train to the first of another and vice versa.

That makes coupling a lot more difficult and sometimes requires to turn around the locomotive to be able to couple the cars again.
(The error message is also not reflecting this, it just says that the parts are not aligned correctly) 

Minimal fix would be to display a different error message that tells the player that the trains can't be coupled, because they are facing the wrong directions (front to front or back to back)

Optimal would be to remove these restrictions all together.

**Comment by stacode123** [comment]
I would recomend you join the discord and put the idea into the ideas channel
