### ISSUE TITLE
Another Mixin loading crash on DEDICATED_SERVER

### ISSUE THREAD

**Issue by SrRapero720** [Layers-of-Railways/Railway#85]
Similar to #51 some mixins are wrong placed

[debug.log](https://github.com/Layers-of-Railways/Railway/files/11024516/debug.log)

Broken mixin:
https://github.com/Layers-of-Railways/Railway/blob/f30ce9e36b711277825ffc6ba0c7fb9c26fe3ea6/src/main/java/com/railwayteam/railways/mixin/MixinReplaceTrackCheck.java#L29

I suggest to test server builds using [WATERCoRE](https://beta.curseforge.com/minecraft/mc-mods/watercore). is the mod with the force-loading feature (checks and force load all mixins)

**Comment by techno-sam** [comment]
Thanks for the report, this is definitely a bug. We are currently working on a track api to merge into base Create that would make these mixins unnecessary (thank goodness).

**Comment by techno-sam** [comment]
1.2.4 server has been tested to work on forge & fabric, please update
