### ISSUE TITLE
steam and rails not displayed

### ISSUE THREAD

**Issue by 2231313fafca** [Layers-of-Railways/Railway#88]
items from this addon are not displayed in the tabs with mods and are not displayed through search, items can only be obtained through crafting

**Comment by techno-sam** [comment]
Known issue, not sure why it happens - if anyone can find a way to reliable reproduce this and a way to reliably have the items show up, that would be a massive help

**Comment by Daniel99j2** [comment]
Try this: https://modrinth.com/mod/block_limit_fix Explanation in description
