### ISSUE TITLE
Conflict with Automobility on Fabric

### ISSUE THREAD

**Issue by Erdragh** [Layers-of-Railways/Railway#89]
When launching an instance with this mod and Automobility installed on fabric, the game gets stuck in a "bootloop" of sorts and won't get to the main menu.

[Here's a log file](https://gist.github.com/Erdragh/126146a62cb136dee69c305c32016f5b) showing that the issue has something to do with loading models.

I've tried looking at the Automobility source code and wasn't even able to get the dev environment to run (it showed similar errors, but not exactly the same. I wasn't able to locate the actual version of ARRP mentioned in the `gradle.properties` file of Automobility tho). 

I assume it has something to do with Automobility bundling ARRP, but my extent of knowledge about ARRP is pretty much exactly what I've gathered during the debugging process so far.

---

I can reproduce the issue with the following minimal setup/instance in PolyMC:

### Versions:
- LWJGL `3.2.2`
- Minecraft `1.18.2`
- Intermediary Mappings `1.18.2`
- Fabric `1.14.14`

### Mods:
- Automobility `0.3+1.18.2`
- Create `0.5.0.i-979+1.18.2`
- Fabric API `0.75.1+1.18.2`

---

### Environment
My OS: Arch Linux updated to the latest version as of time of writing
Java version: `OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)`
Memory allocated to Minecraft: `-Xms2G -Xmx8G`

---

My skill in Modding Minecraft is not yet at a level where I'd be able to figure out what exactly is going on here alone right now.
I'm part of the team that makes the Create: Astral Modpack and we wanted to include this mod in the next version, as it now has a fabric version, but Automobility has a higher priority for us. That doesn't mean we're just gonna give up on this mod though, especially as it was just now ported to fabric.

I/We would be happy to get help resolving this issue!

**Comment by TropheusJ** [comment]
This is probably https://github.com/Fabricators-of-Create/Create/issues/452, but I can’t be sure without a complete log and crash log. If it is, this issue is not fixable. It’s not even an issue with SnR.

**Comment by Erdragh** [comment]
The provided log is as complete as it gets. The game never crashes, it is just stuck in a "bootloop" forever until closed forcibly.

**Comment by Erdragh** [comment]
Until this issue is revolved otherwise, I made a mod you can configure to use the same fix that automobility does for create with various other mods (including steam n rails).

https://modrinth.com/mod/autos_n_rails

**Comment by IThundxr** [comment]
Closing since this is a automobility bug and not snr since if it happens for create aswell then the automobility devs have some fixing to do
