### ISSUE TITLE
The open one side of the trains doors doesn't work

### ISSUE THREAD

**Issue by Redzstonemaster** [Layers-of-Railways/Railway#94]
The button in the train station UI (that I assume opens only one side of the door of the train when the train arrives at a station) doesn't seem to work. for example, when the left door button is enabled and the right door button is disabled nothing seems to happen.

**Comment by SpottyTheTurtle** [comment]
Yes it does, you just have to set specific doors as "left doors" or "right doors" by scrolling on them with a wrench in hand.
