### ISSUE TITLE
Add config to disable train icons in journeymap

### ISSUE THREAD

**Issue by FractalineHue** [Layers-of-Railways/Railway#95]
Currently the client config options for Journeymap are only update time settings.

I would like to disable the train icons in Journeymap like you can disable other entity markers on Journeymaphowever there is no config for this in the client file (for steam and rails).

As such it would be nice if there was a config option true/false to enable/disable the train icons on Journeymap, thank you.

**Comment by techno-sam** [comment]
Added in 1.2.2
