### ISSUE TITLE
Train coupler causes ghost trains to appear on Journeymap

### ISSUE THREAD

**Issue by FractalineHue** [Layers-of-Railways/Railway#96]
As title says when two trains are coupled using the Train Coupler the back train icon/marker remains on Journeymap.

Steps to reproduce:
1. Create two trains
2. Couple them
(this is it, also works with decoupling a train in first step)

**Comment by techno-sam** [comment]
Please confirm this still happens on 1.2.3 (please allow up to 10 seconds for journeymap to update, or use the command `/snrc reload_jmap`
