### ISSUE TITLE
All custom track (the wood types, monorail) curves, s-bends and arcs are replaced to the normal create track after update.

### ISSUE THREAD

**Issue by hihinkoland** [Layers-of-Railways/Railway#98]
I've just updated the version of the mod to `Steam_Rails-1.2.1+forge-mc1.18.2.jar` and loaded my world, noticing that all track splines from this mod (wooden versions and monorail) were replaced with normal create train tacks.
Normal block-placed tracks stayed the same, but the curves connecting them were replaced.
Downgrading to `Steam_Rails-1.2.0+forge-mc1.18.2-build.7.jar` caused ALL curves to be removed, even normal create tracks.

_PS: I'm **so glad**, that I made a backup **right before** opening it after updating!, so lesson for all: __always__ backup, mainly __after you update__, because you never know, what will get broken!_

**Attachements:**
*After updating to newest version:* 
![2023-04-23_20 54 59](https://user-images.githubusercontent.com/66570917/233859528-c3ef4d43-e0a3-4a67-8d88-bac8ef101d0a.png)
![2023-04-23_20 53 31](https://user-images.githubusercontent.com/66570917/233859526-c5f92219-eb15-4ccd-a8e7-8c6255990c5b.png)
*After downgrading:*
![2023-04-23_20 55 14](https://user-images.githubusercontent.com/66570917/233859513-b94c2d25-6949-461e-a843-a43f37af9675.png)
![2023-04-23_20 55 39](https://user-images.githubusercontent.com/66570917/233859517-e85fdb62-825c-4aaf-9cec-d4bc51e12b9c.png)
![2023-04-23_20 55 58](https://user-images.githubusercontent.com/66570917/233859518-eddb2aac-d6ce-4f8c-b2da-20380bc37f63.png)

**Comment by techno-sam** [comment]
Archiving these versions right now, will look into the problem

**Comment by techno-sam** [comment]
Fixed in 1.2.2
